/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the TvState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TvState{}

// TvState struct for TvState
type TvState struct {
	Integration   *TvIntegrationTypes `json:"integration,omitempty"`
	SoundSettings *TvSoundSettings    `json:"soundSettings,omitempty"`
	TvInfo        *TvProperties       `json:"tvInfo,omitempty"`
}

// NewTvState instantiates a new TvState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTvState() *TvState {
	this := TvState{}
	return &this
}

// NewTvStateWithDefaults instantiates a new TvState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTvStateWithDefaults() *TvState {
	this := TvState{}
	return &this
}

// GetIntegration returns the Integration field value if set, zero value otherwise.
func (o *TvState) GetIntegration() TvIntegrationTypes {
	if o == nil || IsNil(o.Integration) {
		var ret TvIntegrationTypes
		return ret
	}
	return *o.Integration
}

// GetIntegrationOk returns a tuple with the Integration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TvState) GetIntegrationOk() (*TvIntegrationTypes, bool) {
	if o == nil || IsNil(o.Integration) {
		return nil, false
	}
	return o.Integration, true
}

// HasIntegration returns a boolean if a field has been set.
func (o *TvState) HasIntegration() bool {
	if o != nil && !IsNil(o.Integration) {
		return true
	}

	return false
}

// SetIntegration gets a reference to the given TvIntegrationTypes and assigns it to the Integration field.
func (o *TvState) SetIntegration(v TvIntegrationTypes) {
	o.Integration = &v
}

// GetSoundSettings returns the SoundSettings field value if set, zero value otherwise.
func (o *TvState) GetSoundSettings() TvSoundSettings {
	if o == nil || IsNil(o.SoundSettings) {
		var ret TvSoundSettings
		return ret
	}
	return *o.SoundSettings
}

// GetSoundSettingsOk returns a tuple with the SoundSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TvState) GetSoundSettingsOk() (*TvSoundSettings, bool) {
	if o == nil || IsNil(o.SoundSettings) {
		return nil, false
	}
	return o.SoundSettings, true
}

// HasSoundSettings returns a boolean if a field has been set.
func (o *TvState) HasSoundSettings() bool {
	if o != nil && !IsNil(o.SoundSettings) {
		return true
	}

	return false
}

// SetSoundSettings gets a reference to the given TvSoundSettings and assigns it to the SoundSettings field.
func (o *TvState) SetSoundSettings(v TvSoundSettings) {
	o.SoundSettings = &v
}

// GetTvInfo returns the TvInfo field value if set, zero value otherwise.
func (o *TvState) GetTvInfo() TvProperties {
	if o == nil || IsNil(o.TvInfo) {
		var ret TvProperties
		return ret
	}
	return *o.TvInfo
}

// GetTvInfoOk returns a tuple with the TvInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TvState) GetTvInfoOk() (*TvProperties, bool) {
	if o == nil || IsNil(o.TvInfo) {
		return nil, false
	}
	return o.TvInfo, true
}

// HasTvInfo returns a boolean if a field has been set.
func (o *TvState) HasTvInfo() bool {
	if o != nil && !IsNil(o.TvInfo) {
		return true
	}

	return false
}

// SetTvInfo gets a reference to the given TvProperties and assigns it to the TvInfo field.
func (o *TvState) SetTvInfo(v TvProperties) {
	o.TvInfo = &v
}

func (o TvState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TvState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Integration) {
		toSerialize["integration"] = o.Integration
	}
	if !IsNil(o.SoundSettings) {
		toSerialize["soundSettings"] = o.SoundSettings
	}
	if !IsNil(o.TvInfo) {
		toSerialize["tvInfo"] = o.TvInfo
	}
	return toSerialize, nil
}

type NullableTvState struct {
	value *TvState
	isSet bool
}

func (v NullableTvState) Get() *TvState {
	return v.value
}

func (v *NullableTvState) Set(val *TvState) {
	v.value = val
	v.isSet = true
}

func (v NullableTvState) IsSet() bool {
	return v.isSet
}

func (v *NullableTvState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTvState(val *TvState) *NullableTvState {
	return &NullableTvState{value: val, isSet: true}
}

func (v NullableTvState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTvState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
