/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ContentItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentItem{}

// ContentItem struct for ContentItem
type ContentItem struct {
	Categories []string       `json:"categories,omitempty"`
	ContentUri string         `json:"contentUri"`
	Label      NullableString `json:"label,omitempty"`
	Source     SourceTypeEnum `json:"source"`
}

type _ContentItem ContentItem

// NewContentItem instantiates a new ContentItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentItem(contentUri string, source SourceTypeEnum) *ContentItem {
	this := ContentItem{}
	this.ContentUri = contentUri
	this.Source = source
	return &this
}

// NewContentItemWithDefaults instantiates a new ContentItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentItemWithDefaults() *ContentItem {
	this := ContentItem{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *ContentItem) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentItem) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *ContentItem) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *ContentItem) SetCategories(v []string) {
	o.Categories = v
}

// GetContentUri returns the ContentUri field value
func (o *ContentItem) GetContentUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentUri
}

// GetContentUriOk returns a tuple with the ContentUri field value
// and a boolean to check if the value has been set.
func (o *ContentItem) GetContentUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentUri, true
}

// SetContentUri sets field value
func (o *ContentItem) SetContentUri(v string) {
	o.ContentUri = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContentItem) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContentItem) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *ContentItem) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *ContentItem) SetLabel(v string) {
	o.Label.Set(&v)
}

// SetLabelNil sets the value for Label to be an explicit nil
func (o *ContentItem) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *ContentItem) UnsetLabel() {
	o.Label.Unset()
}

// GetSource returns the Source field value
func (o *ContentItem) GetSource() SourceTypeEnum {
	if o == nil {
		var ret SourceTypeEnum
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ContentItem) GetSourceOk() (*SourceTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ContentItem) SetSource(v SourceTypeEnum) {
	o.Source = v
}

func (o ContentItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	toSerialize["contentUri"] = o.ContentUri
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *ContentItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contentUri",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContentItem := _ContentItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContentItem)

	if err != nil {
		return err
	}

	*o = ContentItem(varContentItem)

	return err
}

type NullableContentItem struct {
	value *ContentItem
	isSet bool
}

func (v NullableContentItem) Get() *ContentItem {
	return v.value
}

func (v *NullableContentItem) Set(val *ContentItem) {
	v.value = val
	v.isSet = true
}

func (v NullableContentItem) IsSet() bool {
	return v.isSet
}

func (v *NullableContentItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentItem(val *ContentItem) *NullableContentItem {
	return &NullableContentItem{value: val, isSet: true}
}

func (v NullableContentItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
