/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpatialSurroundFeature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpatialSurroundFeature{}

// SpatialSurroundFeature struct for SpatialSurroundFeature
type SpatialSurroundFeature struct {
	// Selected spatial-surround value
	Value   float64         `json:"value"`
	Default SpatialSurround `json:"default"`
	// spatial-surround range
	Range []SpatialSurround `json:"range"`
}

type _SpatialSurroundFeature SpatialSurroundFeature

// NewSpatialSurroundFeature instantiates a new SpatialSurroundFeature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpatialSurroundFeature(value float64, default_ SpatialSurround, range_ []SpatialSurround) *SpatialSurroundFeature {
	this := SpatialSurroundFeature{}
	this.Value = value
	this.Default = default_
	this.Range = range_
	return &this
}

// NewSpatialSurroundFeatureWithDefaults instantiates a new SpatialSurroundFeature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpatialSurroundFeatureWithDefaults() *SpatialSurroundFeature {
	this := SpatialSurroundFeature{}
	return &this
}

// GetValue returns the Value field value
func (o *SpatialSurroundFeature) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SpatialSurroundFeature) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SpatialSurroundFeature) SetValue(v float64) {
	o.Value = v
}

// GetDefault returns the Default field value
func (o *SpatialSurroundFeature) GetDefault() SpatialSurround {
	if o == nil {
		var ret SpatialSurround
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *SpatialSurroundFeature) GetDefaultOk() (*SpatialSurround, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *SpatialSurroundFeature) SetDefault(v SpatialSurround) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *SpatialSurroundFeature) GetRange() []SpatialSurround {
	if o == nil {
		var ret []SpatialSurround
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *SpatialSurroundFeature) GetRangeOk() ([]SpatialSurround, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *SpatialSurroundFeature) SetRange(v []SpatialSurround) {
	o.Range = v
}

func (o SpatialSurroundFeature) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpatialSurroundFeature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *SpatialSurroundFeature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpatialSurroundFeature := _SpatialSurroundFeature{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpatialSurroundFeature)

	if err != nil {
		return err
	}

	*o = SpatialSurroundFeature(varSpatialSurroundFeature)

	return err
}

type NullableSpatialSurroundFeature struct {
	value *SpatialSurroundFeature
	isSet bool
}

func (v NullableSpatialSurroundFeature) Get() *SpatialSurroundFeature {
	return v.value
}

func (v *NullableSpatialSurroundFeature) Set(val *SpatialSurroundFeature) {
	v.value = val
	v.isSet = true
}

func (v NullableSpatialSurroundFeature) IsSet() bool {
	return v.isSet
}

func (v *NullableSpatialSurroundFeature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpatialSurroundFeature(val *SpatialSurroundFeature) *NullableSpatialSurroundFeature {
	return &NullableSpatialSurroundFeature{value: val, isSet: true}
}

func (v NullableSpatialSurroundFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpatialSurroundFeature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
