/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the ListeningModeProps type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListeningModeProps{}

// ListeningModeProps struct for ListeningModeProps
type ListeningModeProps struct {
	// An optional generic string property supplied from the client. If provided, it will be stored without changes. If not supplied, any current clientCtx will remain unchanged.
	ClientCtx NullableString         `json:"clientCtx,omitempty"`
	Features  *ListeningModeFeatures `json:"features,omitempty"`
	Id        *int32                 `json:"id,omitempty"`
	// Friendly name
	Name *string `json:"name,omitempty"`
	// User created, default or an edited default listening mode
	Origin *string `json:"origin,omitempty"`
	// Role a listening mode applies to
	Role     NullableString         `json:"role,omitempty"`
	Triggers []ListeningModeTrigger `json:"triggers,omitempty"`
}

// NewListeningModeProps instantiates a new ListeningModeProps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListeningModeProps() *ListeningModeProps {
	this := ListeningModeProps{}
	return &this
}

// NewListeningModePropsWithDefaults instantiates a new ListeningModeProps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListeningModePropsWithDefaults() *ListeningModeProps {
	this := ListeningModeProps{}
	return &this
}

// GetClientCtx returns the ClientCtx field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListeningModeProps) GetClientCtx() string {
	if o == nil || IsNil(o.ClientCtx.Get()) {
		var ret string
		return ret
	}
	return *o.ClientCtx.Get()
}

// GetClientCtxOk returns a tuple with the ClientCtx field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListeningModeProps) GetClientCtxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientCtx.Get(), o.ClientCtx.IsSet()
}

// HasClientCtx returns a boolean if a field has been set.
func (o *ListeningModeProps) HasClientCtx() bool {
	if o != nil && o.ClientCtx.IsSet() {
		return true
	}

	return false
}

// SetClientCtx gets a reference to the given NullableString and assigns it to the ClientCtx field.
func (o *ListeningModeProps) SetClientCtx(v string) {
	o.ClientCtx.Set(&v)
}

// SetClientCtxNil sets the value for ClientCtx to be an explicit nil
func (o *ListeningModeProps) SetClientCtxNil() {
	o.ClientCtx.Set(nil)
}

// UnsetClientCtx ensures that no value is present for ClientCtx, not even an explicit nil
func (o *ListeningModeProps) UnsetClientCtx() {
	o.ClientCtx.Unset()
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *ListeningModeProps) GetFeatures() ListeningModeFeatures {
	if o == nil || IsNil(o.Features) {
		var ret ListeningModeFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListeningModeProps) GetFeaturesOk() (*ListeningModeFeatures, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *ListeningModeProps) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given ListeningModeFeatures and assigns it to the Features field.
func (o *ListeningModeProps) SetFeatures(v ListeningModeFeatures) {
	o.Features = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListeningModeProps) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListeningModeProps) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListeningModeProps) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ListeningModeProps) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListeningModeProps) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListeningModeProps) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListeningModeProps) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListeningModeProps) SetName(v string) {
	o.Name = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *ListeningModeProps) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListeningModeProps) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *ListeningModeProps) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *ListeningModeProps) SetOrigin(v string) {
	o.Origin = &v
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListeningModeProps) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListeningModeProps) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *ListeningModeProps) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *ListeningModeProps) SetRole(v string) {
	o.Role.Set(&v)
}

// SetRoleNil sets the value for Role to be an explicit nil
func (o *ListeningModeProps) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *ListeningModeProps) UnsetRole() {
	o.Role.Unset()
}

// GetTriggers returns the Triggers field value if set, zero value otherwise.
func (o *ListeningModeProps) GetTriggers() []ListeningModeTrigger {
	if o == nil || IsNil(o.Triggers) {
		var ret []ListeningModeTrigger
		return ret
	}
	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListeningModeProps) GetTriggersOk() ([]ListeningModeTrigger, bool) {
	if o == nil || IsNil(o.Triggers) {
		return nil, false
	}
	return o.Triggers, true
}

// HasTriggers returns a boolean if a field has been set.
func (o *ListeningModeProps) HasTriggers() bool {
	if o != nil && !IsNil(o.Triggers) {
		return true
	}

	return false
}

// SetTriggers gets a reference to the given []ListeningModeTrigger and assigns it to the Triggers field.
func (o *ListeningModeProps) SetTriggers(v []ListeningModeTrigger) {
	o.Triggers = v
}

func (o ListeningModeProps) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListeningModeProps) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientCtx.IsSet() {
		toSerialize["clientCtx"] = o.ClientCtx.Get()
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	if !IsNil(o.Triggers) {
		toSerialize["triggers"] = o.Triggers
	}
	return toSerialize, nil
}

type NullableListeningModeProps struct {
	value *ListeningModeProps
	isSet bool
}

func (v NullableListeningModeProps) Get() *ListeningModeProps {
	return v.value
}

func (v *NullableListeningModeProps) Set(val *ListeningModeProps) {
	v.value = val
	v.isSet = true
}

func (v NullableListeningModeProps) IsSet() bool {
	return v.isSet
}

func (v *NullableListeningModeProps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListeningModeProps(val *ListeningModeProps) *NullableListeningModeProps {
	return &NullableListeningModeProps{value: val, isSet: true}
}

func (v NullableListeningModeProps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListeningModeProps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
