/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the RoomCompensationProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoomCompensationProperties{}

// RoomCompensationProperties struct for RoomCompensationProperties
type RoomCompensationProperties struct {
	// The type of roomcompensation used / to use. simple:   For speakers without external speakers. advanced:   For products with external speakers or other advanced multichannel capabilities.   This requires that at least action in the other properties of RoomCompensationProperties is set.
	Value *string `json:"value,omitempty"`
	// Must be set if room compensation type is advanced. runAll:   Do measurements on all connected speakers. continue:   Continue from and including the speaker where last interrupted (stopped or failed). useSpeakerList:   Do measurements on the speakers in the list property.
	Action NullableString `json:"action,omitempty"`
	// On failing measurement on a speaker, default behavior is to stop measurement and skip the remaining speakers. Setting continueOnError to true will make the measurement process continue and finish measurement on all speakers, even though an error ocurred on one of the speakers.
	ContinueOnError NullableBool    `json:"continueOnError,omitempty"`
	LatencyProfile  *LatencyProfile `json:"latencyProfile,omitempty"`
	// Skip calculation of automatic role assignment.
	SkipAutomaticRoleAssignment NullableBool `json:"skipAutomaticRoleAssignment,omitempty"`
	// List of speaker IDs to include in room compensation / automatic role assignment measurement. Relevant e.g. if you want to create a speaker group without the external speakers included. This can not be used for doing measurements on a partial speaker group, only on all speakers in an existing group or for all speakers in a new group.
	SpeakerList []string `json:"speakerList,omitempty"`
	// The Powerlink preset to use for the external PL/WPL speakers.
	SpeakerPreset NullableInt32 `json:"speakerPreset,omitempty"`
}

// NewRoomCompensationProperties instantiates a new RoomCompensationProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoomCompensationProperties() *RoomCompensationProperties {
	this := RoomCompensationProperties{}
	return &this
}

// NewRoomCompensationPropertiesWithDefaults instantiates a new RoomCompensationProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoomCompensationPropertiesWithDefaults() *RoomCompensationProperties {
	this := RoomCompensationProperties{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *RoomCompensationProperties) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationProperties) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *RoomCompensationProperties) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *RoomCompensationProperties) SetValue(v string) {
	o.Value = &v
}

// GetAction returns the Action field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoomCompensationProperties) GetAction() string {
	if o == nil || IsNil(o.Action.Get()) {
		var ret string
		return ret
	}
	return *o.Action.Get()
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoomCompensationProperties) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Action.Get(), o.Action.IsSet()
}

// HasAction returns a boolean if a field has been set.
func (o *RoomCompensationProperties) HasAction() bool {
	if o != nil && o.Action.IsSet() {
		return true
	}

	return false
}

// SetAction gets a reference to the given NullableString and assigns it to the Action field.
func (o *RoomCompensationProperties) SetAction(v string) {
	o.Action.Set(&v)
}

// SetActionNil sets the value for Action to be an explicit nil
func (o *RoomCompensationProperties) SetActionNil() {
	o.Action.Set(nil)
}

// UnsetAction ensures that no value is present for Action, not even an explicit nil
func (o *RoomCompensationProperties) UnsetAction() {
	o.Action.Unset()
}

// GetContinueOnError returns the ContinueOnError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoomCompensationProperties) GetContinueOnError() bool {
	if o == nil || IsNil(o.ContinueOnError.Get()) {
		var ret bool
		return ret
	}
	return *o.ContinueOnError.Get()
}

// GetContinueOnErrorOk returns a tuple with the ContinueOnError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoomCompensationProperties) GetContinueOnErrorOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContinueOnError.Get(), o.ContinueOnError.IsSet()
}

// HasContinueOnError returns a boolean if a field has been set.
func (o *RoomCompensationProperties) HasContinueOnError() bool {
	if o != nil && o.ContinueOnError.IsSet() {
		return true
	}

	return false
}

// SetContinueOnError gets a reference to the given NullableBool and assigns it to the ContinueOnError field.
func (o *RoomCompensationProperties) SetContinueOnError(v bool) {
	o.ContinueOnError.Set(&v)
}

// SetContinueOnErrorNil sets the value for ContinueOnError to be an explicit nil
func (o *RoomCompensationProperties) SetContinueOnErrorNil() {
	o.ContinueOnError.Set(nil)
}

// UnsetContinueOnError ensures that no value is present for ContinueOnError, not even an explicit nil
func (o *RoomCompensationProperties) UnsetContinueOnError() {
	o.ContinueOnError.Unset()
}

// GetLatencyProfile returns the LatencyProfile field value if set, zero value otherwise.
func (o *RoomCompensationProperties) GetLatencyProfile() LatencyProfile {
	if o == nil || IsNil(o.LatencyProfile) {
		var ret LatencyProfile
		return ret
	}
	return *o.LatencyProfile
}

// GetLatencyProfileOk returns a tuple with the LatencyProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationProperties) GetLatencyProfileOk() (*LatencyProfile, bool) {
	if o == nil || IsNil(o.LatencyProfile) {
		return nil, false
	}
	return o.LatencyProfile, true
}

// HasLatencyProfile returns a boolean if a field has been set.
func (o *RoomCompensationProperties) HasLatencyProfile() bool {
	if o != nil && !IsNil(o.LatencyProfile) {
		return true
	}

	return false
}

// SetLatencyProfile gets a reference to the given LatencyProfile and assigns it to the LatencyProfile field.
func (o *RoomCompensationProperties) SetLatencyProfile(v LatencyProfile) {
	o.LatencyProfile = &v
}

// GetSkipAutomaticRoleAssignment returns the SkipAutomaticRoleAssignment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoomCompensationProperties) GetSkipAutomaticRoleAssignment() bool {
	if o == nil || IsNil(o.SkipAutomaticRoleAssignment.Get()) {
		var ret bool
		return ret
	}
	return *o.SkipAutomaticRoleAssignment.Get()
}

// GetSkipAutomaticRoleAssignmentOk returns a tuple with the SkipAutomaticRoleAssignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoomCompensationProperties) GetSkipAutomaticRoleAssignmentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SkipAutomaticRoleAssignment.Get(), o.SkipAutomaticRoleAssignment.IsSet()
}

// HasSkipAutomaticRoleAssignment returns a boolean if a field has been set.
func (o *RoomCompensationProperties) HasSkipAutomaticRoleAssignment() bool {
	if o != nil && o.SkipAutomaticRoleAssignment.IsSet() {
		return true
	}

	return false
}

// SetSkipAutomaticRoleAssignment gets a reference to the given NullableBool and assigns it to the SkipAutomaticRoleAssignment field.
func (o *RoomCompensationProperties) SetSkipAutomaticRoleAssignment(v bool) {
	o.SkipAutomaticRoleAssignment.Set(&v)
}

// SetSkipAutomaticRoleAssignmentNil sets the value for SkipAutomaticRoleAssignment to be an explicit nil
func (o *RoomCompensationProperties) SetSkipAutomaticRoleAssignmentNil() {
	o.SkipAutomaticRoleAssignment.Set(nil)
}

// UnsetSkipAutomaticRoleAssignment ensures that no value is present for SkipAutomaticRoleAssignment, not even an explicit nil
func (o *RoomCompensationProperties) UnsetSkipAutomaticRoleAssignment() {
	o.SkipAutomaticRoleAssignment.Unset()
}

// GetSpeakerList returns the SpeakerList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoomCompensationProperties) GetSpeakerList() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SpeakerList
}

// GetSpeakerListOk returns a tuple with the SpeakerList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoomCompensationProperties) GetSpeakerListOk() ([]string, bool) {
	if o == nil || IsNil(o.SpeakerList) {
		return nil, false
	}
	return o.SpeakerList, true
}

// HasSpeakerList returns a boolean if a field has been set.
func (o *RoomCompensationProperties) HasSpeakerList() bool {
	if o != nil && !IsNil(o.SpeakerList) {
		return true
	}

	return false
}

// SetSpeakerList gets a reference to the given []string and assigns it to the SpeakerList field.
func (o *RoomCompensationProperties) SetSpeakerList(v []string) {
	o.SpeakerList = v
}

// GetSpeakerPreset returns the SpeakerPreset field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoomCompensationProperties) GetSpeakerPreset() int32 {
	if o == nil || IsNil(o.SpeakerPreset.Get()) {
		var ret int32
		return ret
	}
	return *o.SpeakerPreset.Get()
}

// GetSpeakerPresetOk returns a tuple with the SpeakerPreset field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoomCompensationProperties) GetSpeakerPresetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpeakerPreset.Get(), o.SpeakerPreset.IsSet()
}

// HasSpeakerPreset returns a boolean if a field has been set.
func (o *RoomCompensationProperties) HasSpeakerPreset() bool {
	if o != nil && o.SpeakerPreset.IsSet() {
		return true
	}

	return false
}

// SetSpeakerPreset gets a reference to the given NullableInt32 and assigns it to the SpeakerPreset field.
func (o *RoomCompensationProperties) SetSpeakerPreset(v int32) {
	o.SpeakerPreset.Set(&v)
}

// SetSpeakerPresetNil sets the value for SpeakerPreset to be an explicit nil
func (o *RoomCompensationProperties) SetSpeakerPresetNil() {
	o.SpeakerPreset.Set(nil)
}

// UnsetSpeakerPreset ensures that no value is present for SpeakerPreset, not even an explicit nil
func (o *RoomCompensationProperties) UnsetSpeakerPreset() {
	o.SpeakerPreset.Unset()
}

func (o RoomCompensationProperties) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoomCompensationProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if o.Action.IsSet() {
		toSerialize["action"] = o.Action.Get()
	}
	if o.ContinueOnError.IsSet() {
		toSerialize["continueOnError"] = o.ContinueOnError.Get()
	}
	if !IsNil(o.LatencyProfile) {
		toSerialize["latencyProfile"] = o.LatencyProfile
	}
	if o.SkipAutomaticRoleAssignment.IsSet() {
		toSerialize["skipAutomaticRoleAssignment"] = o.SkipAutomaticRoleAssignment.Get()
	}
	if o.SpeakerList != nil {
		toSerialize["speakerList"] = o.SpeakerList
	}
	if o.SpeakerPreset.IsSet() {
		toSerialize["speakerPreset"] = o.SpeakerPreset.Get()
	}
	return toSerialize, nil
}

type NullableRoomCompensationProperties struct {
	value *RoomCompensationProperties
	isSet bool
}

func (v NullableRoomCompensationProperties) Get() *RoomCompensationProperties {
	return v.value
}

func (v *NullableRoomCompensationProperties) Set(val *RoomCompensationProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableRoomCompensationProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableRoomCompensationProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoomCompensationProperties(val *RoomCompensationProperties) *NullableRoomCompensationProperties {
	return &NullableRoomCompensationProperties{value: val, isSet: true}
}

func (v NullableRoomCompensationProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoomCompensationProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
