/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpeakerGroupMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpeakerGroupMember{}

// SpeakerGroupMember struct for SpeakerGroupMember
type SpeakerGroupMember struct {
	// Distance from listening position in cm
	Distance     NullableInt32  `json:"distance,omitempty"`
	FriendlyName NullableString `json:"friendlyName,omitempty"`
	// Level in dB
	Gain     NullableFloat32                    `json:"gain,omitempty"`
	Id       string                             `json:"id"`
	Location NullableSpeakerGroupMemberLocation `json:"location,omitempty"`
	// Redirection level for bass management in dB
	RedirectionLevel NullableInt32  `json:"redirectionLevel,omitempty"`
	Role             NullableString `json:"role,omitempty"`
	Type             NullableString `json:"type,omitempty"`
}

type _SpeakerGroupMember SpeakerGroupMember

// NewSpeakerGroupMember instantiates a new SpeakerGroupMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpeakerGroupMember(id string) *SpeakerGroupMember {
	this := SpeakerGroupMember{}
	this.Id = id
	return &this
}

// NewSpeakerGroupMemberWithDefaults instantiates a new SpeakerGroupMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpeakerGroupMemberWithDefaults() *SpeakerGroupMember {
	this := SpeakerGroupMember{}
	return &this
}

// GetDistance returns the Distance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpeakerGroupMember) GetDistance() int32 {
	if o == nil || IsNil(o.Distance.Get()) {
		var ret int32
		return ret
	}
	return *o.Distance.Get()
}

// GetDistanceOk returns a tuple with the Distance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpeakerGroupMember) GetDistanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Distance.Get(), o.Distance.IsSet()
}

// HasDistance returns a boolean if a field has been set.
func (o *SpeakerGroupMember) HasDistance() bool {
	if o != nil && o.Distance.IsSet() {
		return true
	}

	return false
}

// SetDistance gets a reference to the given NullableInt32 and assigns it to the Distance field.
func (o *SpeakerGroupMember) SetDistance(v int32) {
	o.Distance.Set(&v)
}

// SetDistanceNil sets the value for Distance to be an explicit nil
func (o *SpeakerGroupMember) SetDistanceNil() {
	o.Distance.Set(nil)
}

// UnsetDistance ensures that no value is present for Distance, not even an explicit nil
func (o *SpeakerGroupMember) UnsetDistance() {
	o.Distance.Unset()
}

// GetFriendlyName returns the FriendlyName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpeakerGroupMember) GetFriendlyName() string {
	if o == nil || IsNil(o.FriendlyName.Get()) {
		var ret string
		return ret
	}
	return *o.FriendlyName.Get()
}

// GetFriendlyNameOk returns a tuple with the FriendlyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpeakerGroupMember) GetFriendlyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FriendlyName.Get(), o.FriendlyName.IsSet()
}

// HasFriendlyName returns a boolean if a field has been set.
func (o *SpeakerGroupMember) HasFriendlyName() bool {
	if o != nil && o.FriendlyName.IsSet() {
		return true
	}

	return false
}

// SetFriendlyName gets a reference to the given NullableString and assigns it to the FriendlyName field.
func (o *SpeakerGroupMember) SetFriendlyName(v string) {
	o.FriendlyName.Set(&v)
}

// SetFriendlyNameNil sets the value for FriendlyName to be an explicit nil
func (o *SpeakerGroupMember) SetFriendlyNameNil() {
	o.FriendlyName.Set(nil)
}

// UnsetFriendlyName ensures that no value is present for FriendlyName, not even an explicit nil
func (o *SpeakerGroupMember) UnsetFriendlyName() {
	o.FriendlyName.Unset()
}

// GetGain returns the Gain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpeakerGroupMember) GetGain() float32 {
	if o == nil || IsNil(o.Gain.Get()) {
		var ret float32
		return ret
	}
	return *o.Gain.Get()
}

// GetGainOk returns a tuple with the Gain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpeakerGroupMember) GetGainOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gain.Get(), o.Gain.IsSet()
}

// HasGain returns a boolean if a field has been set.
func (o *SpeakerGroupMember) HasGain() bool {
	if o != nil && o.Gain.IsSet() {
		return true
	}

	return false
}

// SetGain gets a reference to the given NullableFloat32 and assigns it to the Gain field.
func (o *SpeakerGroupMember) SetGain(v float32) {
	o.Gain.Set(&v)
}

// SetGainNil sets the value for Gain to be an explicit nil
func (o *SpeakerGroupMember) SetGainNil() {
	o.Gain.Set(nil)
}

// UnsetGain ensures that no value is present for Gain, not even an explicit nil
func (o *SpeakerGroupMember) UnsetGain() {
	o.Gain.Unset()
}

// GetId returns the Id field value
func (o *SpeakerGroupMember) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SpeakerGroupMember) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SpeakerGroupMember) SetId(v string) {
	o.Id = v
}

// GetLocation returns the Location field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpeakerGroupMember) GetLocation() SpeakerGroupMemberLocation {
	if o == nil || IsNil(o.Location.Get()) {
		var ret SpeakerGroupMemberLocation
		return ret
	}
	return *o.Location.Get()
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpeakerGroupMember) GetLocationOk() (*SpeakerGroupMemberLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Location.Get(), o.Location.IsSet()
}

// HasLocation returns a boolean if a field has been set.
func (o *SpeakerGroupMember) HasLocation() bool {
	if o != nil && o.Location.IsSet() {
		return true
	}

	return false
}

// SetLocation gets a reference to the given NullableSpeakerGroupMemberLocation and assigns it to the Location field.
func (o *SpeakerGroupMember) SetLocation(v SpeakerGroupMemberLocation) {
	o.Location.Set(&v)
}

// SetLocationNil sets the value for Location to be an explicit nil
func (o *SpeakerGroupMember) SetLocationNil() {
	o.Location.Set(nil)
}

// UnsetLocation ensures that no value is present for Location, not even an explicit nil
func (o *SpeakerGroupMember) UnsetLocation() {
	o.Location.Unset()
}

// GetRedirectionLevel returns the RedirectionLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpeakerGroupMember) GetRedirectionLevel() int32 {
	if o == nil || IsNil(o.RedirectionLevel.Get()) {
		var ret int32
		return ret
	}
	return *o.RedirectionLevel.Get()
}

// GetRedirectionLevelOk returns a tuple with the RedirectionLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpeakerGroupMember) GetRedirectionLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RedirectionLevel.Get(), o.RedirectionLevel.IsSet()
}

// HasRedirectionLevel returns a boolean if a field has been set.
func (o *SpeakerGroupMember) HasRedirectionLevel() bool {
	if o != nil && o.RedirectionLevel.IsSet() {
		return true
	}

	return false
}

// SetRedirectionLevel gets a reference to the given NullableInt32 and assigns it to the RedirectionLevel field.
func (o *SpeakerGroupMember) SetRedirectionLevel(v int32) {
	o.RedirectionLevel.Set(&v)
}

// SetRedirectionLevelNil sets the value for RedirectionLevel to be an explicit nil
func (o *SpeakerGroupMember) SetRedirectionLevelNil() {
	o.RedirectionLevel.Set(nil)
}

// UnsetRedirectionLevel ensures that no value is present for RedirectionLevel, not even an explicit nil
func (o *SpeakerGroupMember) UnsetRedirectionLevel() {
	o.RedirectionLevel.Unset()
}

// GetRole returns the Role field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpeakerGroupMember) GetRole() string {
	if o == nil || IsNil(o.Role.Get()) {
		var ret string
		return ret
	}
	return *o.Role.Get()
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpeakerGroupMember) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Role.Get(), o.Role.IsSet()
}

// HasRole returns a boolean if a field has been set.
func (o *SpeakerGroupMember) HasRole() bool {
	if o != nil && o.Role.IsSet() {
		return true
	}

	return false
}

// SetRole gets a reference to the given NullableString and assigns it to the Role field.
func (o *SpeakerGroupMember) SetRole(v string) {
	o.Role.Set(&v)
}

// SetRoleNil sets the value for Role to be an explicit nil
func (o *SpeakerGroupMember) SetRoleNil() {
	o.Role.Set(nil)
}

// UnsetRole ensures that no value is present for Role, not even an explicit nil
func (o *SpeakerGroupMember) UnsetRole() {
	o.Role.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SpeakerGroupMember) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SpeakerGroupMember) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *SpeakerGroupMember) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *SpeakerGroupMember) SetType(v string) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *SpeakerGroupMember) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *SpeakerGroupMember) UnsetType() {
	o.Type.Unset()
}

func (o SpeakerGroupMember) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpeakerGroupMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Distance.IsSet() {
		toSerialize["distance"] = o.Distance.Get()
	}
	if o.FriendlyName.IsSet() {
		toSerialize["friendlyName"] = o.FriendlyName.Get()
	}
	if o.Gain.IsSet() {
		toSerialize["gain"] = o.Gain.Get()
	}
	toSerialize["id"] = o.Id
	if o.Location.IsSet() {
		toSerialize["location"] = o.Location.Get()
	}
	if o.RedirectionLevel.IsSet() {
		toSerialize["redirectionLevel"] = o.RedirectionLevel.Get()
	}
	if o.Role.IsSet() {
		toSerialize["role"] = o.Role.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	return toSerialize, nil
}

func (o *SpeakerGroupMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpeakerGroupMember := _SpeakerGroupMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpeakerGroupMember)

	if err != nil {
		return err
	}

	*o = SpeakerGroupMember(varSpeakerGroupMember)

	return err
}

type NullableSpeakerGroupMember struct {
	value *SpeakerGroupMember
	isSet bool
}

func (v NullableSpeakerGroupMember) Get() *SpeakerGroupMember {
	return v.value
}

func (v *NullableSpeakerGroupMember) Set(val *SpeakerGroupMember) {
	v.value = val
	v.isSet = true
}

func (v NullableSpeakerGroupMember) IsSet() bool {
	return v.isSet
}

func (v *NullableSpeakerGroupMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpeakerGroupMember(val *SpeakerGroupMember) *NullableSpeakerGroupMember {
	return &NullableSpeakerGroupMember{value: val, isSet: true}
}

func (v NullableSpeakerGroupMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpeakerGroupMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
