/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RoomCompensationRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoomCompensationRange{}

// RoomCompensationRange struct for RoomCompensationRange
type RoomCompensationRange struct {
	// List of room compensation sweeps to combine. No room compensation is done if this list is empty. The maximum length of this list is product specific.
	Default []string `json:"default"`
	// Maximum number of items in the `value` field
	MaxItems *int32 `json:"maxItems,omitempty"`
	// Possible values for the `value` field
	Range []string `json:"range"`
}

type _RoomCompensationRange RoomCompensationRange

// NewRoomCompensationRange instantiates a new RoomCompensationRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoomCompensationRange(default_ []string, range_ []string) *RoomCompensationRange {
	this := RoomCompensationRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewRoomCompensationRangeWithDefaults instantiates a new RoomCompensationRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoomCompensationRangeWithDefaults() *RoomCompensationRange {
	this := RoomCompensationRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *RoomCompensationRange) GetDefault() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *RoomCompensationRange) GetDefaultOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Default, true
}

// SetDefault sets field value
func (o *RoomCompensationRange) SetDefault(v []string) {
	o.Default = v
}

// GetMaxItems returns the MaxItems field value if set, zero value otherwise.
func (o *RoomCompensationRange) GetMaxItems() int32 {
	if o == nil || IsNil(o.MaxItems) {
		var ret int32
		return ret
	}
	return *o.MaxItems
}

// GetMaxItemsOk returns a tuple with the MaxItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationRange) GetMaxItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxItems) {
		return nil, false
	}
	return o.MaxItems, true
}

// HasMaxItems returns a boolean if a field has been set.
func (o *RoomCompensationRange) HasMaxItems() bool {
	if o != nil && !IsNil(o.MaxItems) {
		return true
	}

	return false
}

// SetMaxItems gets a reference to the given int32 and assigns it to the MaxItems field.
func (o *RoomCompensationRange) SetMaxItems(v int32) {
	o.MaxItems = &v
}

// GetRange returns the Range field value
func (o *RoomCompensationRange) GetRange() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *RoomCompensationRange) GetRangeOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *RoomCompensationRange) SetRange(v []string) {
	o.Range = v
}

func (o RoomCompensationRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoomCompensationRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	if !IsNil(o.MaxItems) {
		toSerialize["maxItems"] = o.MaxItems
	}
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *RoomCompensationRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoomCompensationRange := _RoomCompensationRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRoomCompensationRange)

	if err != nil {
		return err
	}

	*o = RoomCompensationRange(varRoomCompensationRange)

	return err
}

type NullableRoomCompensationRange struct {
	value *RoomCompensationRange
	isSet bool
}

func (v NullableRoomCompensationRange) Get() *RoomCompensationRange {
	return v.value
}

func (v *NullableRoomCompensationRange) Set(val *RoomCompensationRange) {
	v.value = val
	v.isSet = true
}

func (v NullableRoomCompensationRange) IsSet() bool {
	return v.isSet
}

func (v *NullableRoomCompensationRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoomCompensationRange(val *RoomCompensationRange) *NullableRoomCompensationRange {
	return &NullableRoomCompensationRange{value: val, isSet: true}
}

func (v NullableRoomCompensationRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoomCompensationRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
