/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BeolinkPeer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeolinkPeer{}

// BeolinkPeer struct for BeolinkPeer
type BeolinkPeer struct {
	// Specifies the audio transport protocol in use. Can be:   - `\"v1\"`: Use protocol version 1.   - `\"v2\"`: Use protocol version 2.
	AudioTransport string `json:"audioTransport"`
	FriendlyName   string `json:"friendlyName"`
	// IP address
	IpAddress string `json:"ipAddress"`
	// Beolink peer ID
	Jid string `json:"jid"`
}

type _BeolinkPeer BeolinkPeer

// NewBeolinkPeer instantiates a new BeolinkPeer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeolinkPeer(audioTransport string, friendlyName string, ipAddress string, jid string) *BeolinkPeer {
	this := BeolinkPeer{}
	this.AudioTransport = audioTransport
	this.FriendlyName = friendlyName
	this.IpAddress = ipAddress
	this.Jid = jid
	return &this
}

// NewBeolinkPeerWithDefaults instantiates a new BeolinkPeer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeolinkPeerWithDefaults() *BeolinkPeer {
	this := BeolinkPeer{}
	return &this
}

// GetAudioTransport returns the AudioTransport field value
func (o *BeolinkPeer) GetAudioTransport() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AudioTransport
}

// GetAudioTransportOk returns a tuple with the AudioTransport field value
// and a boolean to check if the value has been set.
func (o *BeolinkPeer) GetAudioTransportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudioTransport, true
}

// SetAudioTransport sets field value
func (o *BeolinkPeer) SetAudioTransport(v string) {
	o.AudioTransport = v
}

// GetFriendlyName returns the FriendlyName field value
func (o *BeolinkPeer) GetFriendlyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FriendlyName
}

// GetFriendlyNameOk returns a tuple with the FriendlyName field value
// and a boolean to check if the value has been set.
func (o *BeolinkPeer) GetFriendlyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FriendlyName, true
}

// SetFriendlyName sets field value
func (o *BeolinkPeer) SetFriendlyName(v string) {
	o.FriendlyName = v
}

// GetIpAddress returns the IpAddress field value
func (o *BeolinkPeer) GetIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *BeolinkPeer) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpAddress, true
}

// SetIpAddress sets field value
func (o *BeolinkPeer) SetIpAddress(v string) {
	o.IpAddress = v
}

// GetJid returns the Jid field value
func (o *BeolinkPeer) GetJid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jid
}

// GetJidOk returns a tuple with the Jid field value
// and a boolean to check if the value has been set.
func (o *BeolinkPeer) GetJidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jid, true
}

// SetJid sets field value
func (o *BeolinkPeer) SetJid(v string) {
	o.Jid = v
}

func (o BeolinkPeer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeolinkPeer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audioTransport"] = o.AudioTransport
	toSerialize["friendlyName"] = o.FriendlyName
	toSerialize["ipAddress"] = o.IpAddress
	toSerialize["jid"] = o.Jid
	return toSerialize, nil
}

func (o *BeolinkPeer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"audioTransport",
		"friendlyName",
		"ipAddress",
		"jid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBeolinkPeer := _BeolinkPeer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBeolinkPeer)

	if err != nil {
		return err
	}

	*o = BeolinkPeer(varBeolinkPeer)

	return err
}

type NullableBeolinkPeer struct {
	value *BeolinkPeer
	isSet bool
}

func (v NullableBeolinkPeer) Get() *BeolinkPeer {
	return v.value
}

func (v *NullableBeolinkPeer) Set(val *BeolinkPeer) {
	v.value = val
	v.isSet = true
}

func (v NullableBeolinkPeer) IsSet() bool {
	return v.isSet
}

func (v *NullableBeolinkPeer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeolinkPeer(val *BeolinkPeer) *NullableBeolinkPeer {
	return &NullableBeolinkPeer{value: val, isSet: true}
}

func (v NullableBeolinkPeer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeolinkPeer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
