/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BassFeature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BassFeature{}

// BassFeature struct for BassFeature
type BassFeature struct {
	// Selected bass value
	Value   int32 `json:"value"`
	Default Bass  `json:"default"`
	// Product and role specific bass range
	Range []Bass `json:"range"`
}

type _BassFeature BassFeature

// NewBassFeature instantiates a new BassFeature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBassFeature(value int32, default_ Bass, range_ []Bass) *BassFeature {
	this := BassFeature{}
	this.Value = value
	this.Default = default_
	this.Range = range_
	return &this
}

// NewBassFeatureWithDefaults instantiates a new BassFeature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBassFeatureWithDefaults() *BassFeature {
	this := BassFeature{}
	return &this
}

// GetValue returns the Value field value
func (o *BassFeature) GetValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BassFeature) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BassFeature) SetValue(v int32) {
	o.Value = v
}

// GetDefault returns the Default field value
func (o *BassFeature) GetDefault() Bass {
	if o == nil {
		var ret Bass
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *BassFeature) GetDefaultOk() (*Bass, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *BassFeature) SetDefault(v Bass) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *BassFeature) GetRange() []Bass {
	if o == nil {
		var ret []Bass
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *BassFeature) GetRangeOk() ([]Bass, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *BassFeature) SetRange(v []Bass) {
	o.Range = v
}

func (o BassFeature) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BassFeature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *BassFeature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBassFeature := _BassFeature{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBassFeature)

	if err != nil {
		return err
	}

	*o = BassFeature(varBassFeature)

	return err
}

type NullableBassFeature struct {
	value *BassFeature
	isSet bool
}

func (v NullableBassFeature) Get() *BassFeature {
	return v.value
}

func (v *NullableBassFeature) Set(val *BassFeature) {
	v.value = val
	v.isSet = true
}

func (v NullableBassFeature) IsSet() bool {
	return v.isSet
}

func (v *NullableBassFeature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBassFeature(val *BassFeature) *NullableBassFeature {
	return &NullableBassFeature{value: val, isSet: true}
}

func (v NullableBassFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBassFeature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
