/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventActiveSpeakerGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventActiveSpeakerGroup{}

// WebSocketEventActiveSpeakerGroup struct for WebSocketEventActiveSpeakerGroup
type WebSocketEventActiveSpeakerGroup struct {
	EventData *SpeakerGroupOverview `json:"eventData,omitempty"`
	EventType *string               `json:"eventType,omitempty"`
}

// NewWebSocketEventActiveSpeakerGroup instantiates a new WebSocketEventActiveSpeakerGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventActiveSpeakerGroup() *WebSocketEventActiveSpeakerGroup {
	this := WebSocketEventActiveSpeakerGroup{}
	return &this
}

// NewWebSocketEventActiveSpeakerGroupWithDefaults instantiates a new WebSocketEventActiveSpeakerGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventActiveSpeakerGroupWithDefaults() *WebSocketEventActiveSpeakerGroup {
	this := WebSocketEventActiveSpeakerGroup{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventActiveSpeakerGroup) GetEventData() SpeakerGroupOverview {
	if o == nil || IsNil(o.EventData) {
		var ret SpeakerGroupOverview
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventActiveSpeakerGroup) GetEventDataOk() (*SpeakerGroupOverview, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventActiveSpeakerGroup) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given SpeakerGroupOverview and assigns it to the EventData field.
func (o *WebSocketEventActiveSpeakerGroup) SetEventData(v SpeakerGroupOverview) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventActiveSpeakerGroup) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventActiveSpeakerGroup) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventActiveSpeakerGroup) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventActiveSpeakerGroup) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventActiveSpeakerGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventActiveSpeakerGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventActiveSpeakerGroup struct {
	value *WebSocketEventActiveSpeakerGroup
	isSet bool
}

func (v NullableWebSocketEventActiveSpeakerGroup) Get() *WebSocketEventActiveSpeakerGroup {
	return v.value
}

func (v *NullableWebSocketEventActiveSpeakerGroup) Set(val *WebSocketEventActiveSpeakerGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventActiveSpeakerGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventActiveSpeakerGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventActiveSpeakerGroup(val *WebSocketEventActiveSpeakerGroup) *NullableWebSocketEventActiveSpeakerGroup {
	return &NullableWebSocketEventActiveSpeakerGroup{value: val, isSet: true}
}

func (v NullableWebSocketEventActiveSpeakerGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventActiveSpeakerGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
