/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ToneTouchXFeature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToneTouchXFeature{}

// ToneTouchXFeature struct for ToneTouchXFeature
type ToneTouchXFeature struct {
	Value   float64       `json:"value"`
	Default ToneTouchType `json:"default"`
	// Product and role specific tone touch X or Y range
	Range []ToneTouchType `json:"range"`
}

type _ToneTouchXFeature ToneTouchXFeature

// NewToneTouchXFeature instantiates a new ToneTouchXFeature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToneTouchXFeature(value float64, default_ ToneTouchType, range_ []ToneTouchType) *ToneTouchXFeature {
	this := ToneTouchXFeature{}
	this.Value = value
	this.Default = default_
	this.Range = range_
	return &this
}

// NewToneTouchXFeatureWithDefaults instantiates a new ToneTouchXFeature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToneTouchXFeatureWithDefaults() *ToneTouchXFeature {
	this := ToneTouchXFeature{}
	return &this
}

// GetValue returns the Value field value
func (o *ToneTouchXFeature) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ToneTouchXFeature) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ToneTouchXFeature) SetValue(v float64) {
	o.Value = v
}

// GetDefault returns the Default field value
func (o *ToneTouchXFeature) GetDefault() ToneTouchType {
	if o == nil {
		var ret ToneTouchType
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *ToneTouchXFeature) GetDefaultOk() (*ToneTouchType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *ToneTouchXFeature) SetDefault(v ToneTouchType) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *ToneTouchXFeature) GetRange() []ToneTouchType {
	if o == nil {
		var ret []ToneTouchType
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *ToneTouchXFeature) GetRangeOk() ([]ToneTouchType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *ToneTouchXFeature) SetRange(v []ToneTouchType) {
	o.Range = v
}

func (o ToneTouchXFeature) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToneTouchXFeature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *ToneTouchXFeature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToneTouchXFeature := _ToneTouchXFeature{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToneTouchXFeature)

	if err != nil {
		return err
	}

	*o = ToneTouchXFeature(varToneTouchXFeature)

	return err
}

type NullableToneTouchXFeature struct {
	value *ToneTouchXFeature
	isSet bool
}

func (v NullableToneTouchXFeature) Get() *ToneTouchXFeature {
	return v.value
}

func (v *NullableToneTouchXFeature) Set(val *ToneTouchXFeature) {
	v.value = val
	v.isSet = true
}

func (v NullableToneTouchXFeature) IsSet() bool {
	return v.isSet
}

func (v *NullableToneTouchXFeature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToneTouchXFeature(val *ToneTouchXFeature) *NullableToneTouchXFeature {
	return &NullableToneTouchXFeature{value: val, isSet: true}
}

func (v NullableToneTouchXFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToneTouchXFeature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
