/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventPowerState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventPowerState{}

// WebSocketEventPowerState struct for WebSocketEventPowerState
type WebSocketEventPowerState struct {
	EventData *PowerStateEnum `json:"eventData,omitempty"`
	EventType *string         `json:"eventType,omitempty"`
}

// NewWebSocketEventPowerState instantiates a new WebSocketEventPowerState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventPowerState() *WebSocketEventPowerState {
	this := WebSocketEventPowerState{}
	return &this
}

// NewWebSocketEventPowerStateWithDefaults instantiates a new WebSocketEventPowerState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventPowerStateWithDefaults() *WebSocketEventPowerState {
	this := WebSocketEventPowerState{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventPowerState) GetEventData() PowerStateEnum {
	if o == nil || IsNil(o.EventData) {
		var ret PowerStateEnum
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventPowerState) GetEventDataOk() (*PowerStateEnum, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventPowerState) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given PowerStateEnum and assigns it to the EventData field.
func (o *WebSocketEventPowerState) SetEventData(v PowerStateEnum) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventPowerState) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventPowerState) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventPowerState) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventPowerState) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventPowerState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventPowerState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventPowerState struct {
	value *WebSocketEventPowerState
	isSet bool
}

func (v NullableWebSocketEventPowerState) Get() *WebSocketEventPowerState {
	return v.value
}

func (v *NullableWebSocketEventPowerState) Set(val *WebSocketEventPowerState) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventPowerState) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventPowerState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventPowerState(val *WebSocketEventPowerState) *NullableWebSocketEventPowerState {
	return &NullableWebSocketEventPowerState{value: val, isSet: true}
}

func (v NullableWebSocketEventPowerState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventPowerState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
