/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BeoShapeStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeoShapeStatus{}

// BeoShapeStatus Status
type BeoShapeStatus struct {
	// Number of amplifier Shape titles currently configured
	AmplifierTilesConfigured int32 `json:"amplifierTilesConfigured"`
	// Number of amplifier Shape tiles currently connected
	AmplifierTilesOnline int32                       `json:"amplifierTilesOnline"`
	DesignId             *string                     `json:"designId,omitempty"`
	DesignName           *string                     `json:"designName,omitempty"`
	SoundProfile         *BeoShapeStatusSoundProfile `json:"soundProfile,omitempty"`
	// Number of speaker Shape titles currently configured
	SpeakerTilesConfigured int32  `json:"speakerTilesConfigured"`
	State                  string `json:"state"`
}

type _BeoShapeStatus BeoShapeStatus

// NewBeoShapeStatus instantiates a new BeoShapeStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeoShapeStatus(amplifierTilesConfigured int32, amplifierTilesOnline int32, speakerTilesConfigured int32, state string) *BeoShapeStatus {
	this := BeoShapeStatus{}
	this.AmplifierTilesConfigured = amplifierTilesConfigured
	this.AmplifierTilesOnline = amplifierTilesOnline
	this.SpeakerTilesConfigured = speakerTilesConfigured
	this.State = state
	return &this
}

// NewBeoShapeStatusWithDefaults instantiates a new BeoShapeStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeoShapeStatusWithDefaults() *BeoShapeStatus {
	this := BeoShapeStatus{}
	return &this
}

// GetAmplifierTilesConfigured returns the AmplifierTilesConfigured field value
func (o *BeoShapeStatus) GetAmplifierTilesConfigured() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AmplifierTilesConfigured
}

// GetAmplifierTilesConfiguredOk returns a tuple with the AmplifierTilesConfigured field value
// and a boolean to check if the value has been set.
func (o *BeoShapeStatus) GetAmplifierTilesConfiguredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmplifierTilesConfigured, true
}

// SetAmplifierTilesConfigured sets field value
func (o *BeoShapeStatus) SetAmplifierTilesConfigured(v int32) {
	o.AmplifierTilesConfigured = v
}

// GetAmplifierTilesOnline returns the AmplifierTilesOnline field value
func (o *BeoShapeStatus) GetAmplifierTilesOnline() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AmplifierTilesOnline
}

// GetAmplifierTilesOnlineOk returns a tuple with the AmplifierTilesOnline field value
// and a boolean to check if the value has been set.
func (o *BeoShapeStatus) GetAmplifierTilesOnlineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmplifierTilesOnline, true
}

// SetAmplifierTilesOnline sets field value
func (o *BeoShapeStatus) SetAmplifierTilesOnline(v int32) {
	o.AmplifierTilesOnline = v
}

// GetDesignId returns the DesignId field value if set, zero value otherwise.
func (o *BeoShapeStatus) GetDesignId() string {
	if o == nil || IsNil(o.DesignId) {
		var ret string
		return ret
	}
	return *o.DesignId
}

// GetDesignIdOk returns a tuple with the DesignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeoShapeStatus) GetDesignIdOk() (*string, bool) {
	if o == nil || IsNil(o.DesignId) {
		return nil, false
	}
	return o.DesignId, true
}

// HasDesignId returns a boolean if a field has been set.
func (o *BeoShapeStatus) HasDesignId() bool {
	if o != nil && !IsNil(o.DesignId) {
		return true
	}

	return false
}

// SetDesignId gets a reference to the given string and assigns it to the DesignId field.
func (o *BeoShapeStatus) SetDesignId(v string) {
	o.DesignId = &v
}

// GetDesignName returns the DesignName field value if set, zero value otherwise.
func (o *BeoShapeStatus) GetDesignName() string {
	if o == nil || IsNil(o.DesignName) {
		var ret string
		return ret
	}
	return *o.DesignName
}

// GetDesignNameOk returns a tuple with the DesignName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeoShapeStatus) GetDesignNameOk() (*string, bool) {
	if o == nil || IsNil(o.DesignName) {
		return nil, false
	}
	return o.DesignName, true
}

// HasDesignName returns a boolean if a field has been set.
func (o *BeoShapeStatus) HasDesignName() bool {
	if o != nil && !IsNil(o.DesignName) {
		return true
	}

	return false
}

// SetDesignName gets a reference to the given string and assigns it to the DesignName field.
func (o *BeoShapeStatus) SetDesignName(v string) {
	o.DesignName = &v
}

// GetSoundProfile returns the SoundProfile field value if set, zero value otherwise.
func (o *BeoShapeStatus) GetSoundProfile() BeoShapeStatusSoundProfile {
	if o == nil || IsNil(o.SoundProfile) {
		var ret BeoShapeStatusSoundProfile
		return ret
	}
	return *o.SoundProfile
}

// GetSoundProfileOk returns a tuple with the SoundProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeoShapeStatus) GetSoundProfileOk() (*BeoShapeStatusSoundProfile, bool) {
	if o == nil || IsNil(o.SoundProfile) {
		return nil, false
	}
	return o.SoundProfile, true
}

// HasSoundProfile returns a boolean if a field has been set.
func (o *BeoShapeStatus) HasSoundProfile() bool {
	if o != nil && !IsNil(o.SoundProfile) {
		return true
	}

	return false
}

// SetSoundProfile gets a reference to the given BeoShapeStatusSoundProfile and assigns it to the SoundProfile field.
func (o *BeoShapeStatus) SetSoundProfile(v BeoShapeStatusSoundProfile) {
	o.SoundProfile = &v
}

// GetSpeakerTilesConfigured returns the SpeakerTilesConfigured field value
func (o *BeoShapeStatus) GetSpeakerTilesConfigured() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SpeakerTilesConfigured
}

// GetSpeakerTilesConfiguredOk returns a tuple with the SpeakerTilesConfigured field value
// and a boolean to check if the value has been set.
func (o *BeoShapeStatus) GetSpeakerTilesConfiguredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpeakerTilesConfigured, true
}

// SetSpeakerTilesConfigured sets field value
func (o *BeoShapeStatus) SetSpeakerTilesConfigured(v int32) {
	o.SpeakerTilesConfigured = v
}

// GetState returns the State field value
func (o *BeoShapeStatus) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *BeoShapeStatus) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *BeoShapeStatus) SetState(v string) {
	o.State = v
}

func (o BeoShapeStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeoShapeStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amplifierTilesConfigured"] = o.AmplifierTilesConfigured
	toSerialize["amplifierTilesOnline"] = o.AmplifierTilesOnline
	if !IsNil(o.DesignId) {
		toSerialize["designId"] = o.DesignId
	}
	if !IsNil(o.DesignName) {
		toSerialize["designName"] = o.DesignName
	}
	if !IsNil(o.SoundProfile) {
		toSerialize["soundProfile"] = o.SoundProfile
	}
	toSerialize["speakerTilesConfigured"] = o.SpeakerTilesConfigured
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *BeoShapeStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amplifierTilesConfigured",
		"amplifierTilesOnline",
		"speakerTilesConfigured",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBeoShapeStatus := _BeoShapeStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBeoShapeStatus)

	if err != nil {
		return err
	}

	*o = BeoShapeStatus(varBeoShapeStatus)

	return err
}

type NullableBeoShapeStatus struct {
	value *BeoShapeStatus
	isSet bool
}

func (v NullableBeoShapeStatus) Get() *BeoShapeStatus {
	return v.value
}

func (v *NullableBeoShapeStatus) Set(val *BeoShapeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBeoShapeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBeoShapeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeoShapeStatus(val *BeoShapeStatus) *NullableBeoShapeStatus {
	return &NullableBeoShapeStatus{value: val, isSet: true}
}

func (v NullableBeoShapeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeoShapeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
