/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpatialSurroundRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpatialSurroundRange{}

// SpatialSurroundRange struct for SpatialSurroundRange
type SpatialSurroundRange struct {
	Default SpatialSurround `json:"default"`
	// spatial-surround range
	Range []SpatialSurround `json:"range"`
}

type _SpatialSurroundRange SpatialSurroundRange

// NewSpatialSurroundRange instantiates a new SpatialSurroundRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpatialSurroundRange(default_ SpatialSurround, range_ []SpatialSurround) *SpatialSurroundRange {
	this := SpatialSurroundRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewSpatialSurroundRangeWithDefaults instantiates a new SpatialSurroundRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpatialSurroundRangeWithDefaults() *SpatialSurroundRange {
	this := SpatialSurroundRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *SpatialSurroundRange) GetDefault() SpatialSurround {
	if o == nil {
		var ret SpatialSurround
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *SpatialSurroundRange) GetDefaultOk() (*SpatialSurround, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *SpatialSurroundRange) SetDefault(v SpatialSurround) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *SpatialSurroundRange) GetRange() []SpatialSurround {
	if o == nil {
		var ret []SpatialSurround
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *SpatialSurroundRange) GetRangeOk() ([]SpatialSurround, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *SpatialSurroundRange) SetRange(v []SpatialSurround) {
	o.Range = v
}

func (o SpatialSurroundRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpatialSurroundRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *SpatialSurroundRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpatialSurroundRange := _SpatialSurroundRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpatialSurroundRange)

	if err != nil {
		return err
	}

	*o = SpatialSurroundRange(varSpatialSurroundRange)

	return err
}

type NullableSpatialSurroundRange struct {
	value *SpatialSurroundRange
	isSet bool
}

func (v NullableSpatialSurroundRange) Get() *SpatialSurroundRange {
	return v.value
}

func (v *NullableSpatialSurroundRange) Set(val *SpatialSurroundRange) {
	v.value = val
	v.isSet = true
}

func (v NullableSpatialSurroundRange) IsSet() bool {
	return v.isSet
}

func (v *NullableSpatialSurroundRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpatialSurroundRange(val *SpatialSurroundRange) *NullableSpatialSurroundRange {
	return &NullableSpatialSurroundRange{value: val, isSet: true}
}

func (v NullableSpatialSurroundRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpatialSurroundRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
