/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BassManagementRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BassManagementRange{}

// BassManagementRange struct for BassManagementRange
type BassManagementRange struct {
	Default BassManagement `json:"default"`
	// bass-management range
	Range []BassManagement `json:"range"`
}

type _BassManagementRange BassManagementRange

// NewBassManagementRange instantiates a new BassManagementRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBassManagementRange(default_ BassManagement, range_ []BassManagement) *BassManagementRange {
	this := BassManagementRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewBassManagementRangeWithDefaults instantiates a new BassManagementRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBassManagementRangeWithDefaults() *BassManagementRange {
	this := BassManagementRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *BassManagementRange) GetDefault() BassManagement {
	if o == nil {
		var ret BassManagement
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *BassManagementRange) GetDefaultOk() (*BassManagement, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *BassManagementRange) SetDefault(v BassManagement) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *BassManagementRange) GetRange() []BassManagement {
	if o == nil {
		var ret []BassManagement
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *BassManagementRange) GetRangeOk() ([]BassManagement, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *BassManagementRange) SetRange(v []BassManagement) {
	o.Range = v
}

func (o BassManagementRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BassManagementRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *BassManagementRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBassManagementRange := _BassManagementRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBassManagementRange)

	if err != nil {
		return err
	}

	*o = BassManagementRange(varBassManagementRange)

	return err
}

type NullableBassManagementRange struct {
	value *BassManagementRange
	isSet bool
}

func (v NullableBassManagementRange) Get() *BassManagementRange {
	return v.value
}

func (v *NullableBassManagementRange) Set(val *BassManagementRange) {
	v.value = val
	v.isSet = true
}

func (v NullableBassManagementRange) IsSet() bool {
	return v.isSet
}

func (v *NullableBassManagementRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBassManagementRange(val *BassManagementRange) *NullableBassManagementRange {
	return &NullableBassManagementRange{value: val, isSet: true}
}

func (v NullableBassManagementRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBassManagementRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
