/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventVolume type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventVolume{}

// WebSocketEventVolume struct for WebSocketEventVolume
type WebSocketEventVolume struct {
	EventData *VolumeState `json:"eventData,omitempty"`
	EventType *string      `json:"eventType,omitempty"`
}

// NewWebSocketEventVolume instantiates a new WebSocketEventVolume object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventVolume() *WebSocketEventVolume {
	this := WebSocketEventVolume{}
	return &this
}

// NewWebSocketEventVolumeWithDefaults instantiates a new WebSocketEventVolume object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventVolumeWithDefaults() *WebSocketEventVolume {
	this := WebSocketEventVolume{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventVolume) GetEventData() VolumeState {
	if o == nil || IsNil(o.EventData) {
		var ret VolumeState
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventVolume) GetEventDataOk() (*VolumeState, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventVolume) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given VolumeState and assigns it to the EventData field.
func (o *WebSocketEventVolume) SetEventData(v VolumeState) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventVolume) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventVolume) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventVolume) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventVolume) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventVolume) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventVolume) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventVolume struct {
	value *WebSocketEventVolume
	isSet bool
}

func (v NullableWebSocketEventVolume) Get() *WebSocketEventVolume {
	return v.value
}

func (v *NullableWebSocketEventVolume) Set(val *WebSocketEventVolume) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventVolume) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventVolume) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventVolume(val *WebSocketEventVolume) *NullableWebSocketEventVolume {
	return &NullableWebSocketEventVolume{value: val, isSet: true}
}

func (v NullableWebSocketEventVolume) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventVolume) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
