/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the TvSoundSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TvSoundSettings{}

// TvSoundSettings struct for TvSoundSettings
type TvSoundSettings struct {
	Lge *LgeTvSoundSettings `json:"lge,omitempty"`
}

// NewTvSoundSettings instantiates a new TvSoundSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTvSoundSettings() *TvSoundSettings {
	this := TvSoundSettings{}
	return &this
}

// NewTvSoundSettingsWithDefaults instantiates a new TvSoundSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTvSoundSettingsWithDefaults() *TvSoundSettings {
	this := TvSoundSettings{}
	return &this
}

// GetLge returns the Lge field value if set, zero value otherwise.
func (o *TvSoundSettings) GetLge() LgeTvSoundSettings {
	if o == nil || IsNil(o.Lge) {
		var ret LgeTvSoundSettings
		return ret
	}
	return *o.Lge
}

// GetLgeOk returns a tuple with the Lge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TvSoundSettings) GetLgeOk() (*LgeTvSoundSettings, bool) {
	if o == nil || IsNil(o.Lge) {
		return nil, false
	}
	return o.Lge, true
}

// HasLge returns a boolean if a field has been set.
func (o *TvSoundSettings) HasLge() bool {
	if o != nil && !IsNil(o.Lge) {
		return true
	}

	return false
}

// SetLge gets a reference to the given LgeTvSoundSettings and assigns it to the Lge field.
func (o *TvSoundSettings) SetLge(v LgeTvSoundSettings) {
	o.Lge = &v
}

func (o TvSoundSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TvSoundSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Lge) {
		toSerialize["lge"] = o.Lge
	}
	return toSerialize, nil
}

type NullableTvSoundSettings struct {
	value *TvSoundSettings
	isSet bool
}

func (v NullableTvSoundSettings) Get() *TvSoundSettings {
	return v.value
}

func (v *NullableTvSoundSettings) Set(val *TvSoundSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableTvSoundSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableTvSoundSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTvSoundSettings(val *TvSoundSettings) *NullableTvSoundSettings {
	return &NullableTvSoundSettings{value: val, isSet: true}
}

func (v NullableTvSoundSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTvSoundSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
