/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the PlayQueueSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayQueueSettings{}

// PlayQueueSettings struct for PlayQueueSettings
type PlayQueueSettings struct {
	Consume *bool   `json:"consume,omitempty"`
	Gapless *bool   `json:"gapless,omitempty"`
	Repeat  *string `json:"repeat,omitempty"`
	Shuffle *bool   `json:"shuffle,omitempty"`
}

// NewPlayQueueSettings instantiates a new PlayQueueSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayQueueSettings() *PlayQueueSettings {
	this := PlayQueueSettings{}
	return &this
}

// NewPlayQueueSettingsWithDefaults instantiates a new PlayQueueSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayQueueSettingsWithDefaults() *PlayQueueSettings {
	this := PlayQueueSettings{}
	return &this
}

// GetConsume returns the Consume field value if set, zero value otherwise.
func (o *PlayQueueSettings) GetConsume() bool {
	if o == nil || IsNil(o.Consume) {
		var ret bool
		return ret
	}
	return *o.Consume
}

// GetConsumeOk returns a tuple with the Consume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayQueueSettings) GetConsumeOk() (*bool, bool) {
	if o == nil || IsNil(o.Consume) {
		return nil, false
	}
	return o.Consume, true
}

// HasConsume returns a boolean if a field has been set.
func (o *PlayQueueSettings) HasConsume() bool {
	if o != nil && !IsNil(o.Consume) {
		return true
	}

	return false
}

// SetConsume gets a reference to the given bool and assigns it to the Consume field.
func (o *PlayQueueSettings) SetConsume(v bool) {
	o.Consume = &v
}

// GetGapless returns the Gapless field value if set, zero value otherwise.
func (o *PlayQueueSettings) GetGapless() bool {
	if o == nil || IsNil(o.Gapless) {
		var ret bool
		return ret
	}
	return *o.Gapless
}

// GetGaplessOk returns a tuple with the Gapless field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayQueueSettings) GetGaplessOk() (*bool, bool) {
	if o == nil || IsNil(o.Gapless) {
		return nil, false
	}
	return o.Gapless, true
}

// HasGapless returns a boolean if a field has been set.
func (o *PlayQueueSettings) HasGapless() bool {
	if o != nil && !IsNil(o.Gapless) {
		return true
	}

	return false
}

// SetGapless gets a reference to the given bool and assigns it to the Gapless field.
func (o *PlayQueueSettings) SetGapless(v bool) {
	o.Gapless = &v
}

// GetRepeat returns the Repeat field value if set, zero value otherwise.
func (o *PlayQueueSettings) GetRepeat() string {
	if o == nil || IsNil(o.Repeat) {
		var ret string
		return ret
	}
	return *o.Repeat
}

// GetRepeatOk returns a tuple with the Repeat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayQueueSettings) GetRepeatOk() (*string, bool) {
	if o == nil || IsNil(o.Repeat) {
		return nil, false
	}
	return o.Repeat, true
}

// HasRepeat returns a boolean if a field has been set.
func (o *PlayQueueSettings) HasRepeat() bool {
	if o != nil && !IsNil(o.Repeat) {
		return true
	}

	return false
}

// SetRepeat gets a reference to the given string and assigns it to the Repeat field.
func (o *PlayQueueSettings) SetRepeat(v string) {
	o.Repeat = &v
}

// GetShuffle returns the Shuffle field value if set, zero value otherwise.
func (o *PlayQueueSettings) GetShuffle() bool {
	if o == nil || IsNil(o.Shuffle) {
		var ret bool
		return ret
	}
	return *o.Shuffle
}

// GetShuffleOk returns a tuple with the Shuffle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlayQueueSettings) GetShuffleOk() (*bool, bool) {
	if o == nil || IsNil(o.Shuffle) {
		return nil, false
	}
	return o.Shuffle, true
}

// HasShuffle returns a boolean if a field has been set.
func (o *PlayQueueSettings) HasShuffle() bool {
	if o != nil && !IsNil(o.Shuffle) {
		return true
	}

	return false
}

// SetShuffle gets a reference to the given bool and assigns it to the Shuffle field.
func (o *PlayQueueSettings) SetShuffle(v bool) {
	o.Shuffle = &v
}

func (o PlayQueueSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayQueueSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Consume) {
		toSerialize["consume"] = o.Consume
	}
	if !IsNil(o.Gapless) {
		toSerialize["gapless"] = o.Gapless
	}
	if !IsNil(o.Repeat) {
		toSerialize["repeat"] = o.Repeat
	}
	if !IsNil(o.Shuffle) {
		toSerialize["shuffle"] = o.Shuffle
	}
	return toSerialize, nil
}

type NullablePlayQueueSettings struct {
	value *PlayQueueSettings
	isSet bool
}

func (v NullablePlayQueueSettings) Get() *PlayQueueSettings {
	return v.value
}

func (v *NullablePlayQueueSettings) Set(val *PlayQueueSettings) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayQueueSettings) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayQueueSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayQueueSettings(val *PlayQueueSettings) *NullablePlayQueueSettings {
	return &NullablePlayQueueSettings{value: val, isSet: true}
}

func (v NullablePlayQueueSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayQueueSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
