/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AdvancedBeamformingRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedBeamformingRange{}

// AdvancedBeamformingRange struct for AdvancedBeamformingRange
type AdvancedBeamformingRange struct {
	Default AdvancedBeamforming `json:"default"`
	// Product and role specific Advanced Beamforming range
	Range []AdvancedBeamforming `json:"range"`
}

type _AdvancedBeamformingRange AdvancedBeamformingRange

// NewAdvancedBeamformingRange instantiates a new AdvancedBeamformingRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedBeamformingRange(default_ AdvancedBeamforming, range_ []AdvancedBeamforming) *AdvancedBeamformingRange {
	this := AdvancedBeamformingRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewAdvancedBeamformingRangeWithDefaults instantiates a new AdvancedBeamformingRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedBeamformingRangeWithDefaults() *AdvancedBeamformingRange {
	this := AdvancedBeamformingRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *AdvancedBeamformingRange) GetDefault() AdvancedBeamforming {
	if o == nil {
		var ret AdvancedBeamforming
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *AdvancedBeamformingRange) GetDefaultOk() (*AdvancedBeamforming, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *AdvancedBeamformingRange) SetDefault(v AdvancedBeamforming) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *AdvancedBeamformingRange) GetRange() []AdvancedBeamforming {
	if o == nil {
		var ret []AdvancedBeamforming
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *AdvancedBeamformingRange) GetRangeOk() ([]AdvancedBeamforming, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *AdvancedBeamformingRange) SetRange(v []AdvancedBeamforming) {
	o.Range = v
}

func (o AdvancedBeamformingRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedBeamformingRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *AdvancedBeamformingRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdvancedBeamformingRange := _AdvancedBeamformingRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdvancedBeamformingRange)

	if err != nil {
		return err
	}

	*o = AdvancedBeamformingRange(varAdvancedBeamformingRange)

	return err
}

type NullableAdvancedBeamformingRange struct {
	value *AdvancedBeamformingRange
	isSet bool
}

func (v NullableAdvancedBeamformingRange) Get() *AdvancedBeamformingRange {
	return v.value
}

func (v *NullableAdvancedBeamformingRange) Set(val *AdvancedBeamformingRange) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedBeamformingRange) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedBeamformingRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedBeamformingRange(val *AdvancedBeamformingRange) *NullableAdvancedBeamformingRange {
	return &NullableAdvancedBeamformingRange{value: val, isSet: true}
}

func (v NullableAdvancedBeamformingRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedBeamformingRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
