/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BalanceFeature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BalanceFeature{}

// BalanceFeature struct for BalanceFeature
type BalanceFeature struct {
	// Selected balance value
	Value   float64 `json:"value"`
	Default Balance `json:"default"`
	// balance range
	Range []Balance `json:"range"`
}

type _BalanceFeature BalanceFeature

// NewBalanceFeature instantiates a new BalanceFeature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBalanceFeature(value float64, default_ Balance, range_ []Balance) *BalanceFeature {
	this := BalanceFeature{}
	this.Value = value
	this.Default = default_
	this.Range = range_
	return &this
}

// NewBalanceFeatureWithDefaults instantiates a new BalanceFeature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBalanceFeatureWithDefaults() *BalanceFeature {
	this := BalanceFeature{}
	return &this
}

// GetValue returns the Value field value
func (o *BalanceFeature) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BalanceFeature) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BalanceFeature) SetValue(v float64) {
	o.Value = v
}

// GetDefault returns the Default field value
func (o *BalanceFeature) GetDefault() Balance {
	if o == nil {
		var ret Balance
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *BalanceFeature) GetDefaultOk() (*Balance, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *BalanceFeature) SetDefault(v Balance) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *BalanceFeature) GetRange() []Balance {
	if o == nil {
		var ret []Balance
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *BalanceFeature) GetRangeOk() ([]Balance, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *BalanceFeature) SetRange(v []Balance) {
	o.Range = v
}

func (o BalanceFeature) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BalanceFeature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *BalanceFeature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBalanceFeature := _BalanceFeature{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBalanceFeature)

	if err != nil {
		return err
	}

	*o = BalanceFeature(varBalanceFeature)

	return err
}

type NullableBalanceFeature struct {
	value *BalanceFeature
	isSet bool
}

func (v NullableBalanceFeature) Get() *BalanceFeature {
	return v.value
}

func (v *NullableBalanceFeature) Set(val *BalanceFeature) {
	v.value = val
	v.isSet = true
}

func (v NullableBalanceFeature) IsSet() bool {
	return v.isSet
}

func (v *NullableBalanceFeature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBalanceFeature(val *BalanceFeature) *NullableBalanceFeature {
	return &NullableBalanceFeature{value: val, isSet: true}
}

func (v NullableBalanceFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBalanceFeature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
