/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the AlarmTimerEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlarmTimerEventData{}

// AlarmTimerEventData struct for AlarmTimerEventData
type AlarmTimerEventData struct {
	Event *string `json:"event,omitempty"`
	Id    *string `json:"id,omitempty"`
	Type  *string `json:"type,omitempty"`
}

// NewAlarmTimerEventData instantiates a new AlarmTimerEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlarmTimerEventData() *AlarmTimerEventData {
	this := AlarmTimerEventData{}
	return &this
}

// NewAlarmTimerEventDataWithDefaults instantiates a new AlarmTimerEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlarmTimerEventDataWithDefaults() *AlarmTimerEventData {
	this := AlarmTimerEventData{}
	return &this
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *AlarmTimerEventData) GetEvent() string {
	if o == nil || IsNil(o.Event) {
		var ret string
		return ret
	}
	return *o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlarmTimerEventData) GetEventOk() (*string, bool) {
	if o == nil || IsNil(o.Event) {
		return nil, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *AlarmTimerEventData) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given string and assigns it to the Event field.
func (o *AlarmTimerEventData) SetEvent(v string) {
	o.Event = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AlarmTimerEventData) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlarmTimerEventData) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AlarmTimerEventData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AlarmTimerEventData) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AlarmTimerEventData) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlarmTimerEventData) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AlarmTimerEventData) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AlarmTimerEventData) SetType(v string) {
	o.Type = &v
}

func (o AlarmTimerEventData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlarmTimerEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableAlarmTimerEventData struct {
	value *AlarmTimerEventData
	isSet bool
}

func (v NullableAlarmTimerEventData) Get() *AlarmTimerEventData {
	return v.value
}

func (v *NullableAlarmTimerEventData) Set(val *AlarmTimerEventData) {
	v.value = val
	v.isSet = true
}

func (v NullableAlarmTimerEventData) IsSet() bool {
	return v.isSet
}

func (v *NullableAlarmTimerEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlarmTimerEventData(val *AlarmTimerEventData) *NullableAlarmTimerEventData {
	return &NullableAlarmTimerEventData{value: val, isSet: true}
}

func (v NullableAlarmTimerEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlarmTimerEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
