/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventTvBnOMode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventTvBnOMode{}

// WebSocketEventTvBnOMode struct for WebSocketEventTvBnOMode
type WebSocketEventTvBnOMode struct {
	EventData NullableTvBnOModeStatus `json:"eventData,omitempty"`
	EventType *string                 `json:"eventType,omitempty"`
}

// NewWebSocketEventTvBnOMode instantiates a new WebSocketEventTvBnOMode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventTvBnOMode() *WebSocketEventTvBnOMode {
	this := WebSocketEventTvBnOMode{}
	return &this
}

// NewWebSocketEventTvBnOModeWithDefaults instantiates a new WebSocketEventTvBnOMode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventTvBnOModeWithDefaults() *WebSocketEventTvBnOMode {
	this := WebSocketEventTvBnOMode{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebSocketEventTvBnOMode) GetEventData() TvBnOModeStatus {
	if o == nil || IsNil(o.EventData.Get()) {
		var ret TvBnOModeStatus
		return ret
	}
	return *o.EventData.Get()
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebSocketEventTvBnOMode) GetEventDataOk() (*TvBnOModeStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventData.Get(), o.EventData.IsSet()
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventTvBnOMode) HasEventData() bool {
	if o != nil && o.EventData.IsSet() {
		return true
	}

	return false
}

// SetEventData gets a reference to the given NullableTvBnOModeStatus and assigns it to the EventData field.
func (o *WebSocketEventTvBnOMode) SetEventData(v TvBnOModeStatus) {
	o.EventData.Set(&v)
}

// SetEventDataNil sets the value for EventData to be an explicit nil
func (o *WebSocketEventTvBnOMode) SetEventDataNil() {
	o.EventData.Set(nil)
}

// UnsetEventData ensures that no value is present for EventData, not even an explicit nil
func (o *WebSocketEventTvBnOMode) UnsetEventData() {
	o.EventData.Unset()
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventTvBnOMode) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventTvBnOMode) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventTvBnOMode) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventTvBnOMode) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventTvBnOMode) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventTvBnOMode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.EventData.IsSet() {
		toSerialize["eventData"] = o.EventData.Get()
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventTvBnOMode struct {
	value *WebSocketEventTvBnOMode
	isSet bool
}

func (v NullableWebSocketEventTvBnOMode) Get() *WebSocketEventTvBnOMode {
	return v.value
}

func (v *NullableWebSocketEventTvBnOMode) Set(val *WebSocketEventTvBnOMode) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventTvBnOMode) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventTvBnOMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventTvBnOMode(val *WebSocketEventTvBnOMode) *NullableWebSocketEventTvBnOMode {
	return &NullableWebSocketEventTvBnOMode{value: val, isSet: true}
}

func (v NullableWebSocketEventTvBnOMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventTvBnOMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
