/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the SourceTypeEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceTypeEnum{}

// SourceTypeEnum struct for SourceTypeEnum
type SourceTypeEnum struct {
	// - beolink - bluetooth - dlna - qplay - airPlay - lineIn - chromeCast - uriStreamer - netRadio - local - generator - spotify - spdif - pl - wpl - tv - deezer - classicsAdapter - usbIn - tidal - tidalConnect - unknown
	Value *string `json:"value,omitempty"`
}

// NewSourceTypeEnum instantiates a new SourceTypeEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceTypeEnum() *SourceTypeEnum {
	this := SourceTypeEnum{}
	return &this
}

// NewSourceTypeEnumWithDefaults instantiates a new SourceTypeEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceTypeEnumWithDefaults() *SourceTypeEnum {
	this := SourceTypeEnum{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SourceTypeEnum) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceTypeEnum) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SourceTypeEnum) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SourceTypeEnum) SetValue(v string) {
	o.Value = &v
}

func (o SourceTypeEnum) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceTypeEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableSourceTypeEnum struct {
	value *SourceTypeEnum
	isSet bool
}

func (v NullableSourceTypeEnum) Get() *SourceTypeEnum {
	return v.value
}

func (v *NullableSourceTypeEnum) Set(val *SourceTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceTypeEnum(val *SourceTypeEnum) *NullableSourceTypeEnum {
	return &NullableSourceTypeEnum{value: val, isSet: true}
}

func (v NullableSourceTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
