/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Scene type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Scene{}

// Scene struct for Scene
type Scene struct {
	// An ordered list of Actions to run on the product
	ActionList []Action `json:"actionList"`
	// An optional generic string property supplied from the client. If supplied it will overwrite any currently stored clientContext. If not supplied any stored clientContext will be left unchanged.
	ClientContext NullableString `json:"clientContext,omitempty"`
	Label         NullableString `json:"label,omitempty"`
	// A list of user defined tags. This allows a client to create virtual lists
	Tags []string `json:"tags,omitempty"`
	// The classification of Scene
	Classification NullableString `json:"classification,omitempty"`
}

type _Scene Scene

// NewScene instantiates a new Scene object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScene(actionList []Action) *Scene {
	this := Scene{}
	this.ActionList = actionList
	return &this
}

// NewSceneWithDefaults instantiates a new Scene object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSceneWithDefaults() *Scene {
	this := Scene{}
	return &this
}

// GetActionList returns the ActionList field value
func (o *Scene) GetActionList() []Action {
	if o == nil {
		var ret []Action
		return ret
	}

	return o.ActionList
}

// GetActionListOk returns a tuple with the ActionList field value
// and a boolean to check if the value has been set.
func (o *Scene) GetActionListOk() ([]Action, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActionList, true
}

// SetActionList sets field value
func (o *Scene) SetActionList(v []Action) {
	o.ActionList = v
}

// GetClientContext returns the ClientContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Scene) GetClientContext() string {
	if o == nil || IsNil(o.ClientContext.Get()) {
		var ret string
		return ret
	}
	return *o.ClientContext.Get()
}

// GetClientContextOk returns a tuple with the ClientContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Scene) GetClientContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientContext.Get(), o.ClientContext.IsSet()
}

// HasClientContext returns a boolean if a field has been set.
func (o *Scene) HasClientContext() bool {
	if o != nil && o.ClientContext.IsSet() {
		return true
	}

	return false
}

// SetClientContext gets a reference to the given NullableString and assigns it to the ClientContext field.
func (o *Scene) SetClientContext(v string) {
	o.ClientContext.Set(&v)
}

// SetClientContextNil sets the value for ClientContext to be an explicit nil
func (o *Scene) SetClientContextNil() {
	o.ClientContext.Set(nil)
}

// UnsetClientContext ensures that no value is present for ClientContext, not even an explicit nil
func (o *Scene) UnsetClientContext() {
	o.ClientContext.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Scene) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Scene) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *Scene) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *Scene) SetLabel(v string) {
	o.Label.Set(&v)
}

// SetLabelNil sets the value for Label to be an explicit nil
func (o *Scene) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *Scene) UnsetLabel() {
	o.Label.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Scene) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Scene) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Scene) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Scene) SetTags(v []string) {
	o.Tags = v
}

// GetClassification returns the Classification field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Scene) GetClassification() string {
	if o == nil || IsNil(o.Classification.Get()) {
		var ret string
		return ret
	}
	return *o.Classification.Get()
}

// GetClassificationOk returns a tuple with the Classification field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Scene) GetClassificationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Classification.Get(), o.Classification.IsSet()
}

// HasClassification returns a boolean if a field has been set.
func (o *Scene) HasClassification() bool {
	if o != nil && o.Classification.IsSet() {
		return true
	}

	return false
}

// SetClassification gets a reference to the given NullableString and assigns it to the Classification field.
func (o *Scene) SetClassification(v string) {
	o.Classification.Set(&v)
}

// SetClassificationNil sets the value for Classification to be an explicit nil
func (o *Scene) SetClassificationNil() {
	o.Classification.Set(nil)
}

// UnsetClassification ensures that no value is present for Classification, not even an explicit nil
func (o *Scene) UnsetClassification() {
	o.Classification.Unset()
}

func (o Scene) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Scene) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actionList"] = o.ActionList
	if o.ClientContext.IsSet() {
		toSerialize["clientContext"] = o.ClientContext.Get()
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Classification.IsSet() {
		toSerialize["classification"] = o.Classification.Get()
	}
	return toSerialize, nil
}

func (o *Scene) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actionList",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScene := _Scene{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScene)

	if err != nil {
		return err
	}

	*o = Scene(varScene)

	return err
}

type NullableScene struct {
	value *Scene
	isSet bool
}

func (v NullableScene) Get() *Scene {
	return v.value
}

func (v *NullableScene) Set(val *Scene) {
	v.value = val
	v.isSet = true
}

func (v NullableScene) IsSet() bool {
	return v.isSet
}

func (v *NullableScene) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScene(val *Scene) *NullableScene {
	return &NullableScene{value: val, isSet: true}
}

func (v NullableScene) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScene) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
