/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the ButtonEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ButtonEvent{}

// ButtonEvent struct for ButtonEvent
type ButtonEvent struct {
	// identifies the button
	Button *string `json:"button,omitempty"`
	// identifies the state change
	State *string `json:"state,omitempty"`
}

// NewButtonEvent instantiates a new ButtonEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewButtonEvent() *ButtonEvent {
	this := ButtonEvent{}
	return &this
}

// NewButtonEventWithDefaults instantiates a new ButtonEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewButtonEventWithDefaults() *ButtonEvent {
	this := ButtonEvent{}
	return &this
}

// GetButton returns the Button field value if set, zero value otherwise.
func (o *ButtonEvent) GetButton() string {
	if o == nil || IsNil(o.Button) {
		var ret string
		return ret
	}
	return *o.Button
}

// GetButtonOk returns a tuple with the Button field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ButtonEvent) GetButtonOk() (*string, bool) {
	if o == nil || IsNil(o.Button) {
		return nil, false
	}
	return o.Button, true
}

// HasButton returns a boolean if a field has been set.
func (o *ButtonEvent) HasButton() bool {
	if o != nil && !IsNil(o.Button) {
		return true
	}

	return false
}

// SetButton gets a reference to the given string and assigns it to the Button field.
func (o *ButtonEvent) SetButton(v string) {
	o.Button = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ButtonEvent) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ButtonEvent) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ButtonEvent) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ButtonEvent) SetState(v string) {
	o.State = &v
}

func (o ButtonEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ButtonEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Button) {
		toSerialize["button"] = o.Button
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableButtonEvent struct {
	value *ButtonEvent
	isSet bool
}

func (v NullableButtonEvent) Get() *ButtonEvent {
	return v.value
}

func (v *NullableButtonEvent) Set(val *ButtonEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableButtonEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableButtonEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableButtonEvent(val *ButtonEvent) *NullableButtonEvent {
	return &NullableButtonEvent{value: val, isSet: true}
}

func (v NullableButtonEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableButtonEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
