/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the StandStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandStatus{}

// StandStatus struct for StandStatus
type StandStatus struct {
	Manuallyadjusted *bool                `json:"manuallyadjusted,omitempty"`
	Movementstatus   *StandMovementStatus `json:"movementstatus,omitempty"`
	Position         *StandPosition       `json:"position,omitempty"`
	TargetAngle      *float32             `json:"targetAngle,omitempty"`
}

// NewStandStatus instantiates a new StandStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandStatus() *StandStatus {
	this := StandStatus{}
	return &this
}

// NewStandStatusWithDefaults instantiates a new StandStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandStatusWithDefaults() *StandStatus {
	this := StandStatus{}
	return &this
}

// GetManuallyadjusted returns the Manuallyadjusted field value if set, zero value otherwise.
func (o *StandStatus) GetManuallyadjusted() bool {
	if o == nil || IsNil(o.Manuallyadjusted) {
		var ret bool
		return ret
	}
	return *o.Manuallyadjusted
}

// GetManuallyadjustedOk returns a tuple with the Manuallyadjusted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandStatus) GetManuallyadjustedOk() (*bool, bool) {
	if o == nil || IsNil(o.Manuallyadjusted) {
		return nil, false
	}
	return o.Manuallyadjusted, true
}

// HasManuallyadjusted returns a boolean if a field has been set.
func (o *StandStatus) HasManuallyadjusted() bool {
	if o != nil && !IsNil(o.Manuallyadjusted) {
		return true
	}

	return false
}

// SetManuallyadjusted gets a reference to the given bool and assigns it to the Manuallyadjusted field.
func (o *StandStatus) SetManuallyadjusted(v bool) {
	o.Manuallyadjusted = &v
}

// GetMovementstatus returns the Movementstatus field value if set, zero value otherwise.
func (o *StandStatus) GetMovementstatus() StandMovementStatus {
	if o == nil || IsNil(o.Movementstatus) {
		var ret StandMovementStatus
		return ret
	}
	return *o.Movementstatus
}

// GetMovementstatusOk returns a tuple with the Movementstatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandStatus) GetMovementstatusOk() (*StandMovementStatus, bool) {
	if o == nil || IsNil(o.Movementstatus) {
		return nil, false
	}
	return o.Movementstatus, true
}

// HasMovementstatus returns a boolean if a field has been set.
func (o *StandStatus) HasMovementstatus() bool {
	if o != nil && !IsNil(o.Movementstatus) {
		return true
	}

	return false
}

// SetMovementstatus gets a reference to the given StandMovementStatus and assigns it to the Movementstatus field.
func (o *StandStatus) SetMovementstatus(v StandMovementStatus) {
	o.Movementstatus = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *StandStatus) GetPosition() StandPosition {
	if o == nil || IsNil(o.Position) {
		var ret StandPosition
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandStatus) GetPositionOk() (*StandPosition, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *StandStatus) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given StandPosition and assigns it to the Position field.
func (o *StandStatus) SetPosition(v StandPosition) {
	o.Position = &v
}

// GetTargetAngle returns the TargetAngle field value if set, zero value otherwise.
func (o *StandStatus) GetTargetAngle() float32 {
	if o == nil || IsNil(o.TargetAngle) {
		var ret float32
		return ret
	}
	return *o.TargetAngle
}

// GetTargetAngleOk returns a tuple with the TargetAngle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandStatus) GetTargetAngleOk() (*float32, bool) {
	if o == nil || IsNil(o.TargetAngle) {
		return nil, false
	}
	return o.TargetAngle, true
}

// HasTargetAngle returns a boolean if a field has been set.
func (o *StandStatus) HasTargetAngle() bool {
	if o != nil && !IsNil(o.TargetAngle) {
		return true
	}

	return false
}

// SetTargetAngle gets a reference to the given float32 and assigns it to the TargetAngle field.
func (o *StandStatus) SetTargetAngle(v float32) {
	o.TargetAngle = &v
}

func (o StandStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Manuallyadjusted) {
		toSerialize["manuallyadjusted"] = o.Manuallyadjusted
	}
	if !IsNil(o.Movementstatus) {
		toSerialize["movementstatus"] = o.Movementstatus
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.TargetAngle) {
		toSerialize["targetAngle"] = o.TargetAngle
	}
	return toSerialize, nil
}

type NullableStandStatus struct {
	value *StandStatus
	isSet bool
}

func (v NullableStandStatus) Get() *StandStatus {
	return v.value
}

func (v *NullableStandStatus) Set(val *StandStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableStandStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableStandStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandStatus(val *StandStatus) *NullableStandStatus {
	return &NullableStandStatus{value: val, isSet: true}
}

func (v NullableStandStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
