/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the Uri type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Uri{}

// Uri struct for Uri
type Uri struct {
	Location *string `json:"location,omitempty"`
}

// NewUri instantiates a new Uri object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUri() *Uri {
	this := Uri{}
	return &this
}

// NewUriWithDefaults instantiates a new Uri object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUriWithDefaults() *Uri {
	this := Uri{}
	return &this
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Uri) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Uri) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Uri) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *Uri) SetLocation(v string) {
	o.Location = &v
}

func (o Uri) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Uri) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	return toSerialize, nil
}

type NullableUri struct {
	value *Uri
	isSet bool
}

func (v NullableUri) Get() *Uri {
	return v.value
}

func (v *NullableUri) Set(val *Uri) {
	v.value = val
	v.isSet = true
}

func (v NullableUri) IsSet() bool {
	return v.isSet
}

func (v *NullableUri) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUri(val *Uri) *NullableUri {
	return &NullableUri{value: val, isSet: true}
}

func (v NullableUri) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUri) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
