/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the ContentItemWithId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentItemWithId{}

// ContentItemWithId struct for ContentItemWithId
type ContentItemWithId struct {
	Content *ContentItem `json:"content,omitempty"`
	Id      *string      `json:"id,omitempty"`
}

// NewContentItemWithId instantiates a new ContentItemWithId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentItemWithId() *ContentItemWithId {
	this := ContentItemWithId{}
	return &this
}

// NewContentItemWithIdWithDefaults instantiates a new ContentItemWithId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentItemWithIdWithDefaults() *ContentItemWithId {
	this := ContentItemWithId{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ContentItemWithId) GetContent() ContentItem {
	if o == nil || IsNil(o.Content) {
		var ret ContentItem
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentItemWithId) GetContentOk() (*ContentItem, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ContentItemWithId) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given ContentItem and assigns it to the Content field.
func (o *ContentItemWithId) SetContent(v ContentItem) {
	o.Content = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContentItemWithId) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContentItemWithId) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContentItemWithId) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ContentItemWithId) SetId(v string) {
	o.Id = &v
}

func (o ContentItemWithId) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentItemWithId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableContentItemWithId struct {
	value *ContentItemWithId
	isSet bool
}

func (v NullableContentItemWithId) Get() *ContentItemWithId {
	return v.value
}

func (v *NullableContentItemWithId) Set(val *ContentItemWithId) {
	v.value = val
	v.isSet = true
}

func (v NullableContentItemWithId) IsSet() bool {
	return v.isSet
}

func (v *NullableContentItemWithId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentItemWithId(val *ContentItemWithId) *NullableContentItemWithId {
	return &NullableContentItemWithId{value: val, isSet: true}
}

func (v NullableContentItemWithId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentItemWithId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
