/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the RoomCompensationInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoomCompensationInfo{}

// RoomCompensationInfo struct for RoomCompensationInfo
type RoomCompensationInfo struct {
	Debug      *RoomCompensationDebug   `json:"debug,omitempty"`
	Enabled    *RoomCompensationEnabled `json:"enabled,omitempty"`
	LastResult *RoomCompensationResult  `json:"lastResult,omitempty"`
	LastRun    *RoomCompensationState   `json:"lastRun,omitempty"`
	Type       *RoomCompensationType    `json:"type,omitempty"`
	Version    *RoomCompensationVersion `json:"version,omitempty"`
}

// NewRoomCompensationInfo instantiates a new RoomCompensationInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoomCompensationInfo() *RoomCompensationInfo {
	this := RoomCompensationInfo{}
	return &this
}

// NewRoomCompensationInfoWithDefaults instantiates a new RoomCompensationInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoomCompensationInfoWithDefaults() *RoomCompensationInfo {
	this := RoomCompensationInfo{}
	return &this
}

// GetDebug returns the Debug field value if set, zero value otherwise.
func (o *RoomCompensationInfo) GetDebug() RoomCompensationDebug {
	if o == nil || IsNil(o.Debug) {
		var ret RoomCompensationDebug
		return ret
	}
	return *o.Debug
}

// GetDebugOk returns a tuple with the Debug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationInfo) GetDebugOk() (*RoomCompensationDebug, bool) {
	if o == nil || IsNil(o.Debug) {
		return nil, false
	}
	return o.Debug, true
}

// HasDebug returns a boolean if a field has been set.
func (o *RoomCompensationInfo) HasDebug() bool {
	if o != nil && !IsNil(o.Debug) {
		return true
	}

	return false
}

// SetDebug gets a reference to the given RoomCompensationDebug and assigns it to the Debug field.
func (o *RoomCompensationInfo) SetDebug(v RoomCompensationDebug) {
	o.Debug = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *RoomCompensationInfo) GetEnabled() RoomCompensationEnabled {
	if o == nil || IsNil(o.Enabled) {
		var ret RoomCompensationEnabled
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationInfo) GetEnabledOk() (*RoomCompensationEnabled, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *RoomCompensationInfo) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given RoomCompensationEnabled and assigns it to the Enabled field.
func (o *RoomCompensationInfo) SetEnabled(v RoomCompensationEnabled) {
	o.Enabled = &v
}

// GetLastResult returns the LastResult field value if set, zero value otherwise.
func (o *RoomCompensationInfo) GetLastResult() RoomCompensationResult {
	if o == nil || IsNil(o.LastResult) {
		var ret RoomCompensationResult
		return ret
	}
	return *o.LastResult
}

// GetLastResultOk returns a tuple with the LastResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationInfo) GetLastResultOk() (*RoomCompensationResult, bool) {
	if o == nil || IsNil(o.LastResult) {
		return nil, false
	}
	return o.LastResult, true
}

// HasLastResult returns a boolean if a field has been set.
func (o *RoomCompensationInfo) HasLastResult() bool {
	if o != nil && !IsNil(o.LastResult) {
		return true
	}

	return false
}

// SetLastResult gets a reference to the given RoomCompensationResult and assigns it to the LastResult field.
func (o *RoomCompensationInfo) SetLastResult(v RoomCompensationResult) {
	o.LastResult = &v
}

// GetLastRun returns the LastRun field value if set, zero value otherwise.
func (o *RoomCompensationInfo) GetLastRun() RoomCompensationState {
	if o == nil || IsNil(o.LastRun) {
		var ret RoomCompensationState
		return ret
	}
	return *o.LastRun
}

// GetLastRunOk returns a tuple with the LastRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationInfo) GetLastRunOk() (*RoomCompensationState, bool) {
	if o == nil || IsNil(o.LastRun) {
		return nil, false
	}
	return o.LastRun, true
}

// HasLastRun returns a boolean if a field has been set.
func (o *RoomCompensationInfo) HasLastRun() bool {
	if o != nil && !IsNil(o.LastRun) {
		return true
	}

	return false
}

// SetLastRun gets a reference to the given RoomCompensationState and assigns it to the LastRun field.
func (o *RoomCompensationInfo) SetLastRun(v RoomCompensationState) {
	o.LastRun = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *RoomCompensationInfo) GetType() RoomCompensationType {
	if o == nil || IsNil(o.Type) {
		var ret RoomCompensationType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationInfo) GetTypeOk() (*RoomCompensationType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *RoomCompensationInfo) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given RoomCompensationType and assigns it to the Type field.
func (o *RoomCompensationInfo) SetType(v RoomCompensationType) {
	o.Type = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *RoomCompensationInfo) GetVersion() RoomCompensationVersion {
	if o == nil || IsNil(o.Version) {
		var ret RoomCompensationVersion
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationInfo) GetVersionOk() (*RoomCompensationVersion, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *RoomCompensationInfo) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given RoomCompensationVersion and assigns it to the Version field.
func (o *RoomCompensationInfo) SetVersion(v RoomCompensationVersion) {
	o.Version = &v
}

func (o RoomCompensationInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoomCompensationInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Debug) {
		toSerialize["debug"] = o.Debug
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.LastResult) {
		toSerialize["lastResult"] = o.LastResult
	}
	if !IsNil(o.LastRun) {
		toSerialize["lastRun"] = o.LastRun
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableRoomCompensationInfo struct {
	value *RoomCompensationInfo
	isSet bool
}

func (v NullableRoomCompensationInfo) Get() *RoomCompensationInfo {
	return v.value
}

func (v *NullableRoomCompensationInfo) Set(val *RoomCompensationInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableRoomCompensationInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableRoomCompensationInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoomCompensationInfo(val *RoomCompensationInfo) *NullableRoomCompensationInfo {
	return &NullableRoomCompensationInfo{value: val, isSet: true}
}

func (v NullableRoomCompensationInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoomCompensationInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
