/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpatialHeightRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpatialHeightRange{}

// SpatialHeightRange struct for SpatialHeightRange
type SpatialHeightRange struct {
	Default SpatialHeight `json:"default"`
	// spatial-height range
	Range []SpatialHeight `json:"range"`
}

type _SpatialHeightRange SpatialHeightRange

// NewSpatialHeightRange instantiates a new SpatialHeightRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpatialHeightRange(default_ SpatialHeight, range_ []SpatialHeight) *SpatialHeightRange {
	this := SpatialHeightRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewSpatialHeightRangeWithDefaults instantiates a new SpatialHeightRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpatialHeightRangeWithDefaults() *SpatialHeightRange {
	this := SpatialHeightRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *SpatialHeightRange) GetDefault() SpatialHeight {
	if o == nil {
		var ret SpatialHeight
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *SpatialHeightRange) GetDefaultOk() (*SpatialHeight, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *SpatialHeightRange) SetDefault(v SpatialHeight) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *SpatialHeightRange) GetRange() []SpatialHeight {
	if o == nil {
		var ret []SpatialHeight
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *SpatialHeightRange) GetRangeOk() ([]SpatialHeight, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *SpatialHeightRange) SetRange(v []SpatialHeight) {
	o.Range = v
}

func (o SpatialHeightRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpatialHeightRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *SpatialHeightRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpatialHeightRange := _SpatialHeightRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpatialHeightRange)

	if err != nil {
		return err
	}

	*o = SpatialHeightRange(varSpatialHeightRange)

	return err
}

type NullableSpatialHeightRange struct {
	value *SpatialHeightRange
	isSet bool
}

func (v NullableSpatialHeightRange) Get() *SpatialHeightRange {
	return v.value
}

func (v *NullableSpatialHeightRange) Set(val *SpatialHeightRange) {
	v.value = val
	v.isSet = true
}

func (v NullableSpatialHeightRange) IsSet() bool {
	return v.isSet
}

func (v *NullableSpatialHeightRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpatialHeightRange(val *SpatialHeightRange) *NullableSpatialHeightRange {
	return &NullableSpatialHeightRange{value: val, isSet: true}
}

func (v NullableSpatialHeightRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpatialHeightRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
