/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ToneTouchTypeRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToneTouchTypeRange{}

// ToneTouchTypeRange struct for ToneTouchTypeRange
type ToneTouchTypeRange struct {
	Default ToneTouchType `json:"default"`
	// Product and role specific tone touch X or Y range
	Range []ToneTouchType `json:"range"`
}

type _ToneTouchTypeRange ToneTouchTypeRange

// NewToneTouchTypeRange instantiates a new ToneTouchTypeRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToneTouchTypeRange(default_ ToneTouchType, range_ []ToneTouchType) *ToneTouchTypeRange {
	this := ToneTouchTypeRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewToneTouchTypeRangeWithDefaults instantiates a new ToneTouchTypeRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToneTouchTypeRangeWithDefaults() *ToneTouchTypeRange {
	this := ToneTouchTypeRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *ToneTouchTypeRange) GetDefault() ToneTouchType {
	if o == nil {
		var ret ToneTouchType
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *ToneTouchTypeRange) GetDefaultOk() (*ToneTouchType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *ToneTouchTypeRange) SetDefault(v ToneTouchType) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *ToneTouchTypeRange) GetRange() []ToneTouchType {
	if o == nil {
		var ret []ToneTouchType
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *ToneTouchTypeRange) GetRangeOk() ([]ToneTouchType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *ToneTouchTypeRange) SetRange(v []ToneTouchType) {
	o.Range = v
}

func (o ToneTouchTypeRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToneTouchTypeRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *ToneTouchTypeRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToneTouchTypeRange := _ToneTouchTypeRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToneTouchTypeRange)

	if err != nil {
		return err
	}

	*o = ToneTouchTypeRange(varToneTouchTypeRange)

	return err
}

type NullableToneTouchTypeRange struct {
	value *ToneTouchTypeRange
	isSet bool
}

func (v NullableToneTouchTypeRange) Get() *ToneTouchTypeRange {
	return v.value
}

func (v *NullableToneTouchTypeRange) Set(val *ToneTouchTypeRange) {
	v.value = val
	v.isSet = true
}

func (v NullableToneTouchTypeRange) IsSet() bool {
	return v.isSet
}

func (v *NullableToneTouchTypeRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToneTouchTypeRange(val *ToneTouchTypeRange) *NullableToneTouchTypeRange {
	return &NullableToneTouchTypeRange{value: val, isSet: true}
}

func (v NullableToneTouchTypeRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToneTouchTypeRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
