/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the PairedRemoteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PairedRemoteResponse{}

// PairedRemoteResponse struct for PairedRemoteResponse
type PairedRemoteResponse struct {
	Items []PairedRemote `json:"items,omitempty"`
}

// NewPairedRemoteResponse instantiates a new PairedRemoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPairedRemoteResponse() *PairedRemoteResponse {
	this := PairedRemoteResponse{}
	return &this
}

// NewPairedRemoteResponseWithDefaults instantiates a new PairedRemoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPairedRemoteResponseWithDefaults() *PairedRemoteResponse {
	this := PairedRemoteResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PairedRemoteResponse) GetItems() []PairedRemote {
	if o == nil || IsNil(o.Items) {
		var ret []PairedRemote
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PairedRemoteResponse) GetItemsOk() ([]PairedRemote, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PairedRemoteResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PairedRemote and assigns it to the Items field.
func (o *PairedRemoteResponse) SetItems(v []PairedRemote) {
	o.Items = v
}

func (o PairedRemoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PairedRemoteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullablePairedRemoteResponse struct {
	value *PairedRemoteResponse
	isSet bool
}

func (v NullablePairedRemoteResponse) Get() *PairedRemoteResponse {
	return v.value
}

func (v *NullablePairedRemoteResponse) Set(val *PairedRemoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePairedRemoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePairedRemoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePairedRemoteResponse(val *PairedRemoteResponse) *NullablePairedRemoteResponse {
	return &NullablePairedRemoteResponse{value: val, isSet: true}
}

func (v NullablePairedRemoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePairedRemoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
