/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventPucInstallRemoteIdStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventPucInstallRemoteIdStatus{}

// WebSocketEventPucInstallRemoteIdStatus struct for WebSocketEventPucInstallRemoteIdStatus
type WebSocketEventPucInstallRemoteIdStatus struct {
	EventData *InstallRecordIdState `json:"eventData,omitempty"`
	EventType *string               `json:"eventType,omitempty"`
}

// NewWebSocketEventPucInstallRemoteIdStatus instantiates a new WebSocketEventPucInstallRemoteIdStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventPucInstallRemoteIdStatus() *WebSocketEventPucInstallRemoteIdStatus {
	this := WebSocketEventPucInstallRemoteIdStatus{}
	return &this
}

// NewWebSocketEventPucInstallRemoteIdStatusWithDefaults instantiates a new WebSocketEventPucInstallRemoteIdStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventPucInstallRemoteIdStatusWithDefaults() *WebSocketEventPucInstallRemoteIdStatus {
	this := WebSocketEventPucInstallRemoteIdStatus{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventPucInstallRemoteIdStatus) GetEventData() InstallRecordIdState {
	if o == nil || IsNil(o.EventData) {
		var ret InstallRecordIdState
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventPucInstallRemoteIdStatus) GetEventDataOk() (*InstallRecordIdState, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventPucInstallRemoteIdStatus) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given InstallRecordIdState and assigns it to the EventData field.
func (o *WebSocketEventPucInstallRemoteIdStatus) SetEventData(v InstallRecordIdState) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventPucInstallRemoteIdStatus) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventPucInstallRemoteIdStatus) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventPucInstallRemoteIdStatus) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventPucInstallRemoteIdStatus) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventPucInstallRemoteIdStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventPucInstallRemoteIdStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventPucInstallRemoteIdStatus struct {
	value *WebSocketEventPucInstallRemoteIdStatus
	isSet bool
}

func (v NullableWebSocketEventPucInstallRemoteIdStatus) Get() *WebSocketEventPucInstallRemoteIdStatus {
	return v.value
}

func (v *NullableWebSocketEventPucInstallRemoteIdStatus) Set(val *WebSocketEventPucInstallRemoteIdStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventPucInstallRemoteIdStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventPucInstallRemoteIdStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventPucInstallRemoteIdStatus(val *WebSocketEventPucInstallRemoteIdStatus) *NullableWebSocketEventPucInstallRemoteIdStatus {
	return &NullableWebSocketEventPucInstallRemoteIdStatus{value: val, isSet: true}
}

func (v NullableWebSocketEventPucInstallRemoteIdStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventPucInstallRemoteIdStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
