/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the SoundFeatureSet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoundFeatureSet{}

// SoundFeatureSet struct for SoundFeatureSet
type SoundFeatureSet struct {
	AdvancedBeamforming *AdvancedBeamformingFeature `json:"advancedBeamforming,omitempty"`
	Ambience            *AmbienceFeature            `json:"ambience,omitempty"`
	Balance             *BalanceFeature             `json:"balance,omitempty"`
	Bass                *BassFeature                `json:"bass,omitempty"`
	BassManagement      *BassManagementFeature      `json:"bass-management,omitempty"`
	Compression         *CompressionFeature         `json:"compression,omitempty"`
	Directivity         *DirectivityFeature         `json:"directivity,omitempty"`
	Fader               *FaderFeature               `json:"fader,omitempty"`
	RoomCompensation    *RoomCompensationFeature    `json:"roomCompensation,omitempty"`
	SpatialEnvelopment  *SpatialEnvelopmentFeature  `json:"spatial-envelopment,omitempty"`
	SpatialHeight       *SpatialHeightFeature       `json:"spatial-height,omitempty"`
	SpatialProcessing   *SpatialProcessingFeature   `json:"spatial-processing,omitempty"`
	SpatialSurround     *SpatialSurroundFeature     `json:"spatial-surround,omitempty"`
	SpatialWidth        *SpatialWidthFeature        `json:"spatial-width,omitempty"`
	SpeechEnhance       *SpeechEnhanceFeature       `json:"speech-enhance,omitempty"`
	ToneTouchX          *ToneTouchXFeature          `json:"toneTouchX,omitempty"`
	ToneTouchY          *ToneTouchYFeature          `json:"toneTouchY,omitempty"`
	Treble              *TrebleFeature              `json:"treble,omitempty"`
}

// NewSoundFeatureSet instantiates a new SoundFeatureSet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoundFeatureSet() *SoundFeatureSet {
	this := SoundFeatureSet{}
	return &this
}

// NewSoundFeatureSetWithDefaults instantiates a new SoundFeatureSet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoundFeatureSetWithDefaults() *SoundFeatureSet {
	this := SoundFeatureSet{}
	return &this
}

// GetAdvancedBeamforming returns the AdvancedBeamforming field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetAdvancedBeamforming() AdvancedBeamformingFeature {
	if o == nil || IsNil(o.AdvancedBeamforming) {
		var ret AdvancedBeamformingFeature
		return ret
	}
	return *o.AdvancedBeamforming
}

// GetAdvancedBeamformingOk returns a tuple with the AdvancedBeamforming field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetAdvancedBeamformingOk() (*AdvancedBeamformingFeature, bool) {
	if o == nil || IsNil(o.AdvancedBeamforming) {
		return nil, false
	}
	return o.AdvancedBeamforming, true
}

// HasAdvancedBeamforming returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasAdvancedBeamforming() bool {
	if o != nil && !IsNil(o.AdvancedBeamforming) {
		return true
	}

	return false
}

// SetAdvancedBeamforming gets a reference to the given AdvancedBeamformingFeature and assigns it to the AdvancedBeamforming field.
func (o *SoundFeatureSet) SetAdvancedBeamforming(v AdvancedBeamformingFeature) {
	o.AdvancedBeamforming = &v
}

// GetAmbience returns the Ambience field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetAmbience() AmbienceFeature {
	if o == nil || IsNil(o.Ambience) {
		var ret AmbienceFeature
		return ret
	}
	return *o.Ambience
}

// GetAmbienceOk returns a tuple with the Ambience field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetAmbienceOk() (*AmbienceFeature, bool) {
	if o == nil || IsNil(o.Ambience) {
		return nil, false
	}
	return o.Ambience, true
}

// HasAmbience returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasAmbience() bool {
	if o != nil && !IsNil(o.Ambience) {
		return true
	}

	return false
}

// SetAmbience gets a reference to the given AmbienceFeature and assigns it to the Ambience field.
func (o *SoundFeatureSet) SetAmbience(v AmbienceFeature) {
	o.Ambience = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetBalance() BalanceFeature {
	if o == nil || IsNil(o.Balance) {
		var ret BalanceFeature
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetBalanceOk() (*BalanceFeature, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given BalanceFeature and assigns it to the Balance field.
func (o *SoundFeatureSet) SetBalance(v BalanceFeature) {
	o.Balance = &v
}

// GetBass returns the Bass field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetBass() BassFeature {
	if o == nil || IsNil(o.Bass) {
		var ret BassFeature
		return ret
	}
	return *o.Bass
}

// GetBassOk returns a tuple with the Bass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetBassOk() (*BassFeature, bool) {
	if o == nil || IsNil(o.Bass) {
		return nil, false
	}
	return o.Bass, true
}

// HasBass returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasBass() bool {
	if o != nil && !IsNil(o.Bass) {
		return true
	}

	return false
}

// SetBass gets a reference to the given BassFeature and assigns it to the Bass field.
func (o *SoundFeatureSet) SetBass(v BassFeature) {
	o.Bass = &v
}

// GetBassManagement returns the BassManagement field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetBassManagement() BassManagementFeature {
	if o == nil || IsNil(o.BassManagement) {
		var ret BassManagementFeature
		return ret
	}
	return *o.BassManagement
}

// GetBassManagementOk returns a tuple with the BassManagement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetBassManagementOk() (*BassManagementFeature, bool) {
	if o == nil || IsNil(o.BassManagement) {
		return nil, false
	}
	return o.BassManagement, true
}

// HasBassManagement returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasBassManagement() bool {
	if o != nil && !IsNil(o.BassManagement) {
		return true
	}

	return false
}

// SetBassManagement gets a reference to the given BassManagementFeature and assigns it to the BassManagement field.
func (o *SoundFeatureSet) SetBassManagement(v BassManagementFeature) {
	o.BassManagement = &v
}

// GetCompression returns the Compression field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetCompression() CompressionFeature {
	if o == nil || IsNil(o.Compression) {
		var ret CompressionFeature
		return ret
	}
	return *o.Compression
}

// GetCompressionOk returns a tuple with the Compression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetCompressionOk() (*CompressionFeature, bool) {
	if o == nil || IsNil(o.Compression) {
		return nil, false
	}
	return o.Compression, true
}

// HasCompression returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasCompression() bool {
	if o != nil && !IsNil(o.Compression) {
		return true
	}

	return false
}

// SetCompression gets a reference to the given CompressionFeature and assigns it to the Compression field.
func (o *SoundFeatureSet) SetCompression(v CompressionFeature) {
	o.Compression = &v
}

// GetDirectivity returns the Directivity field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetDirectivity() DirectivityFeature {
	if o == nil || IsNil(o.Directivity) {
		var ret DirectivityFeature
		return ret
	}
	return *o.Directivity
}

// GetDirectivityOk returns a tuple with the Directivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetDirectivityOk() (*DirectivityFeature, bool) {
	if o == nil || IsNil(o.Directivity) {
		return nil, false
	}
	return o.Directivity, true
}

// HasDirectivity returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasDirectivity() bool {
	if o != nil && !IsNil(o.Directivity) {
		return true
	}

	return false
}

// SetDirectivity gets a reference to the given DirectivityFeature and assigns it to the Directivity field.
func (o *SoundFeatureSet) SetDirectivity(v DirectivityFeature) {
	o.Directivity = &v
}

// GetFader returns the Fader field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetFader() FaderFeature {
	if o == nil || IsNil(o.Fader) {
		var ret FaderFeature
		return ret
	}
	return *o.Fader
}

// GetFaderOk returns a tuple with the Fader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetFaderOk() (*FaderFeature, bool) {
	if o == nil || IsNil(o.Fader) {
		return nil, false
	}
	return o.Fader, true
}

// HasFader returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasFader() bool {
	if o != nil && !IsNil(o.Fader) {
		return true
	}

	return false
}

// SetFader gets a reference to the given FaderFeature and assigns it to the Fader field.
func (o *SoundFeatureSet) SetFader(v FaderFeature) {
	o.Fader = &v
}

// GetRoomCompensation returns the RoomCompensation field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetRoomCompensation() RoomCompensationFeature {
	if o == nil || IsNil(o.RoomCompensation) {
		var ret RoomCompensationFeature
		return ret
	}
	return *o.RoomCompensation
}

// GetRoomCompensationOk returns a tuple with the RoomCompensation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetRoomCompensationOk() (*RoomCompensationFeature, bool) {
	if o == nil || IsNil(o.RoomCompensation) {
		return nil, false
	}
	return o.RoomCompensation, true
}

// HasRoomCompensation returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasRoomCompensation() bool {
	if o != nil && !IsNil(o.RoomCompensation) {
		return true
	}

	return false
}

// SetRoomCompensation gets a reference to the given RoomCompensationFeature and assigns it to the RoomCompensation field.
func (o *SoundFeatureSet) SetRoomCompensation(v RoomCompensationFeature) {
	o.RoomCompensation = &v
}

// GetSpatialEnvelopment returns the SpatialEnvelopment field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetSpatialEnvelopment() SpatialEnvelopmentFeature {
	if o == nil || IsNil(o.SpatialEnvelopment) {
		var ret SpatialEnvelopmentFeature
		return ret
	}
	return *o.SpatialEnvelopment
}

// GetSpatialEnvelopmentOk returns a tuple with the SpatialEnvelopment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetSpatialEnvelopmentOk() (*SpatialEnvelopmentFeature, bool) {
	if o == nil || IsNil(o.SpatialEnvelopment) {
		return nil, false
	}
	return o.SpatialEnvelopment, true
}

// HasSpatialEnvelopment returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasSpatialEnvelopment() bool {
	if o != nil && !IsNil(o.SpatialEnvelopment) {
		return true
	}

	return false
}

// SetSpatialEnvelopment gets a reference to the given SpatialEnvelopmentFeature and assigns it to the SpatialEnvelopment field.
func (o *SoundFeatureSet) SetSpatialEnvelopment(v SpatialEnvelopmentFeature) {
	o.SpatialEnvelopment = &v
}

// GetSpatialHeight returns the SpatialHeight field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetSpatialHeight() SpatialHeightFeature {
	if o == nil || IsNil(o.SpatialHeight) {
		var ret SpatialHeightFeature
		return ret
	}
	return *o.SpatialHeight
}

// GetSpatialHeightOk returns a tuple with the SpatialHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetSpatialHeightOk() (*SpatialHeightFeature, bool) {
	if o == nil || IsNil(o.SpatialHeight) {
		return nil, false
	}
	return o.SpatialHeight, true
}

// HasSpatialHeight returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasSpatialHeight() bool {
	if o != nil && !IsNil(o.SpatialHeight) {
		return true
	}

	return false
}

// SetSpatialHeight gets a reference to the given SpatialHeightFeature and assigns it to the SpatialHeight field.
func (o *SoundFeatureSet) SetSpatialHeight(v SpatialHeightFeature) {
	o.SpatialHeight = &v
}

// GetSpatialProcessing returns the SpatialProcessing field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetSpatialProcessing() SpatialProcessingFeature {
	if o == nil || IsNil(o.SpatialProcessing) {
		var ret SpatialProcessingFeature
		return ret
	}
	return *o.SpatialProcessing
}

// GetSpatialProcessingOk returns a tuple with the SpatialProcessing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetSpatialProcessingOk() (*SpatialProcessingFeature, bool) {
	if o == nil || IsNil(o.SpatialProcessing) {
		return nil, false
	}
	return o.SpatialProcessing, true
}

// HasSpatialProcessing returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasSpatialProcessing() bool {
	if o != nil && !IsNil(o.SpatialProcessing) {
		return true
	}

	return false
}

// SetSpatialProcessing gets a reference to the given SpatialProcessingFeature and assigns it to the SpatialProcessing field.
func (o *SoundFeatureSet) SetSpatialProcessing(v SpatialProcessingFeature) {
	o.SpatialProcessing = &v
}

// GetSpatialSurround returns the SpatialSurround field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetSpatialSurround() SpatialSurroundFeature {
	if o == nil || IsNil(o.SpatialSurround) {
		var ret SpatialSurroundFeature
		return ret
	}
	return *o.SpatialSurround
}

// GetSpatialSurroundOk returns a tuple with the SpatialSurround field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetSpatialSurroundOk() (*SpatialSurroundFeature, bool) {
	if o == nil || IsNil(o.SpatialSurround) {
		return nil, false
	}
	return o.SpatialSurround, true
}

// HasSpatialSurround returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasSpatialSurround() bool {
	if o != nil && !IsNil(o.SpatialSurround) {
		return true
	}

	return false
}

// SetSpatialSurround gets a reference to the given SpatialSurroundFeature and assigns it to the SpatialSurround field.
func (o *SoundFeatureSet) SetSpatialSurround(v SpatialSurroundFeature) {
	o.SpatialSurround = &v
}

// GetSpatialWidth returns the SpatialWidth field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetSpatialWidth() SpatialWidthFeature {
	if o == nil || IsNil(o.SpatialWidth) {
		var ret SpatialWidthFeature
		return ret
	}
	return *o.SpatialWidth
}

// GetSpatialWidthOk returns a tuple with the SpatialWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetSpatialWidthOk() (*SpatialWidthFeature, bool) {
	if o == nil || IsNil(o.SpatialWidth) {
		return nil, false
	}
	return o.SpatialWidth, true
}

// HasSpatialWidth returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasSpatialWidth() bool {
	if o != nil && !IsNil(o.SpatialWidth) {
		return true
	}

	return false
}

// SetSpatialWidth gets a reference to the given SpatialWidthFeature and assigns it to the SpatialWidth field.
func (o *SoundFeatureSet) SetSpatialWidth(v SpatialWidthFeature) {
	o.SpatialWidth = &v
}

// GetSpeechEnhance returns the SpeechEnhance field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetSpeechEnhance() SpeechEnhanceFeature {
	if o == nil || IsNil(o.SpeechEnhance) {
		var ret SpeechEnhanceFeature
		return ret
	}
	return *o.SpeechEnhance
}

// GetSpeechEnhanceOk returns a tuple with the SpeechEnhance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetSpeechEnhanceOk() (*SpeechEnhanceFeature, bool) {
	if o == nil || IsNil(o.SpeechEnhance) {
		return nil, false
	}
	return o.SpeechEnhance, true
}

// HasSpeechEnhance returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasSpeechEnhance() bool {
	if o != nil && !IsNil(o.SpeechEnhance) {
		return true
	}

	return false
}

// SetSpeechEnhance gets a reference to the given SpeechEnhanceFeature and assigns it to the SpeechEnhance field.
func (o *SoundFeatureSet) SetSpeechEnhance(v SpeechEnhanceFeature) {
	o.SpeechEnhance = &v
}

// GetToneTouchX returns the ToneTouchX field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetToneTouchX() ToneTouchXFeature {
	if o == nil || IsNil(o.ToneTouchX) {
		var ret ToneTouchXFeature
		return ret
	}
	return *o.ToneTouchX
}

// GetToneTouchXOk returns a tuple with the ToneTouchX field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetToneTouchXOk() (*ToneTouchXFeature, bool) {
	if o == nil || IsNil(o.ToneTouchX) {
		return nil, false
	}
	return o.ToneTouchX, true
}

// HasToneTouchX returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasToneTouchX() bool {
	if o != nil && !IsNil(o.ToneTouchX) {
		return true
	}

	return false
}

// SetToneTouchX gets a reference to the given ToneTouchXFeature and assigns it to the ToneTouchX field.
func (o *SoundFeatureSet) SetToneTouchX(v ToneTouchXFeature) {
	o.ToneTouchX = &v
}

// GetToneTouchY returns the ToneTouchY field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetToneTouchY() ToneTouchYFeature {
	if o == nil || IsNil(o.ToneTouchY) {
		var ret ToneTouchYFeature
		return ret
	}
	return *o.ToneTouchY
}

// GetToneTouchYOk returns a tuple with the ToneTouchY field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetToneTouchYOk() (*ToneTouchYFeature, bool) {
	if o == nil || IsNil(o.ToneTouchY) {
		return nil, false
	}
	return o.ToneTouchY, true
}

// HasToneTouchY returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasToneTouchY() bool {
	if o != nil && !IsNil(o.ToneTouchY) {
		return true
	}

	return false
}

// SetToneTouchY gets a reference to the given ToneTouchYFeature and assigns it to the ToneTouchY field.
func (o *SoundFeatureSet) SetToneTouchY(v ToneTouchYFeature) {
	o.ToneTouchY = &v
}

// GetTreble returns the Treble field value if set, zero value otherwise.
func (o *SoundFeatureSet) GetTreble() TrebleFeature {
	if o == nil || IsNil(o.Treble) {
		var ret TrebleFeature
		return ret
	}
	return *o.Treble
}

// GetTrebleOk returns a tuple with the Treble field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundFeatureSet) GetTrebleOk() (*TrebleFeature, bool) {
	if o == nil || IsNil(o.Treble) {
		return nil, false
	}
	return o.Treble, true
}

// HasTreble returns a boolean if a field has been set.
func (o *SoundFeatureSet) HasTreble() bool {
	if o != nil && !IsNil(o.Treble) {
		return true
	}

	return false
}

// SetTreble gets a reference to the given TrebleFeature and assigns it to the Treble field.
func (o *SoundFeatureSet) SetTreble(v TrebleFeature) {
	o.Treble = &v
}

func (o SoundFeatureSet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoundFeatureSet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdvancedBeamforming) {
		toSerialize["advancedBeamforming"] = o.AdvancedBeamforming
	}
	if !IsNil(o.Ambience) {
		toSerialize["ambience"] = o.Ambience
	}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.Bass) {
		toSerialize["bass"] = o.Bass
	}
	if !IsNil(o.BassManagement) {
		toSerialize["bass-management"] = o.BassManagement
	}
	if !IsNil(o.Compression) {
		toSerialize["compression"] = o.Compression
	}
	if !IsNil(o.Directivity) {
		toSerialize["directivity"] = o.Directivity
	}
	if !IsNil(o.Fader) {
		toSerialize["fader"] = o.Fader
	}
	if !IsNil(o.RoomCompensation) {
		toSerialize["roomCompensation"] = o.RoomCompensation
	}
	if !IsNil(o.SpatialEnvelopment) {
		toSerialize["spatial-envelopment"] = o.SpatialEnvelopment
	}
	if !IsNil(o.SpatialHeight) {
		toSerialize["spatial-height"] = o.SpatialHeight
	}
	if !IsNil(o.SpatialProcessing) {
		toSerialize["spatial-processing"] = o.SpatialProcessing
	}
	if !IsNil(o.SpatialSurround) {
		toSerialize["spatial-surround"] = o.SpatialSurround
	}
	if !IsNil(o.SpatialWidth) {
		toSerialize["spatial-width"] = o.SpatialWidth
	}
	if !IsNil(o.SpeechEnhance) {
		toSerialize["speech-enhance"] = o.SpeechEnhance
	}
	if !IsNil(o.ToneTouchX) {
		toSerialize["toneTouchX"] = o.ToneTouchX
	}
	if !IsNil(o.ToneTouchY) {
		toSerialize["toneTouchY"] = o.ToneTouchY
	}
	if !IsNil(o.Treble) {
		toSerialize["treble"] = o.Treble
	}
	return toSerialize, nil
}

type NullableSoundFeatureSet struct {
	value *SoundFeatureSet
	isSet bool
}

func (v NullableSoundFeatureSet) Get() *SoundFeatureSet {
	return v.value
}

func (v *NullableSoundFeatureSet) Set(val *SoundFeatureSet) {
	v.value = val
	v.isSet = true
}

func (v NullableSoundFeatureSet) IsSet() bool {
	return v.isSet
}

func (v *NullableSoundFeatureSet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoundFeatureSet(val *SoundFeatureSet) *NullableSoundFeatureSet {
	return &NullableSoundFeatureSet{value: val, isSet: true}
}

func (v NullableSoundFeatureSet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoundFeatureSet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
