/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the StandConnected type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandConnected{}

// StandConnected struct for StandConnected
type StandConnected struct {
	Connected *bool `json:"connected,omitempty"`
}

// NewStandConnected instantiates a new StandConnected object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandConnected() *StandConnected {
	this := StandConnected{}
	return &this
}

// NewStandConnectedWithDefaults instantiates a new StandConnected object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandConnectedWithDefaults() *StandConnected {
	this := StandConnected{}
	return &this
}

// GetConnected returns the Connected field value if set, zero value otherwise.
func (o *StandConnected) GetConnected() bool {
	if o == nil || IsNil(o.Connected) {
		var ret bool
		return ret
	}
	return *o.Connected
}

// GetConnectedOk returns a tuple with the Connected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StandConnected) GetConnectedOk() (*bool, bool) {
	if o == nil || IsNil(o.Connected) {
		return nil, false
	}
	return o.Connected, true
}

// HasConnected returns a boolean if a field has been set.
func (o *StandConnected) HasConnected() bool {
	if o != nil && !IsNil(o.Connected) {
		return true
	}

	return false
}

// SetConnected gets a reference to the given bool and assigns it to the Connected field.
func (o *StandConnected) SetConnected(v bool) {
	o.Connected = &v
}

func (o StandConnected) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandConnected) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Connected) {
		toSerialize["connected"] = o.Connected
	}
	return toSerialize, nil
}

type NullableStandConnected struct {
	value *StandConnected
	isSet bool
}

func (v NullableStandConnected) Get() *StandConnected {
	return v.value
}

func (v *NullableStandConnected) Set(val *StandConnected) {
	v.value = val
	v.isSet = true
}

func (v NullableStandConnected) IsSet() bool {
	return v.isSet
}

func (v *NullableStandConnected) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandConnected(val *StandConnected) *NullableStandConnected {
	return &NullableStandConnected{value: val, isSet: true}
}

func (v NullableStandConnected) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandConnected) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
