/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the RemoteUIKeyState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteUIKeyState{}

// RemoteUIKeyState struct for RemoteUIKeyState
type RemoteUIKeyState struct {
	// The state of the pressed key. ShortPress and LongPress's duration are determined by the remote. Whereas Down, Continue, and Release reflect the state of the key and press duration is the time between a Down and a Release state. Continue indicates that a button is pressed and the key event should be handled multiple times until a release is received.
	State *string `json:"state,omitempty"`
}

// NewRemoteUIKeyState instantiates a new RemoteUIKeyState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteUIKeyState() *RemoteUIKeyState {
	this := RemoteUIKeyState{}
	return &this
}

// NewRemoteUIKeyStateWithDefaults instantiates a new RemoteUIKeyState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteUIKeyStateWithDefaults() *RemoteUIKeyState {
	this := RemoteUIKeyState{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *RemoteUIKeyState) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoteUIKeyState) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *RemoteUIKeyState) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *RemoteUIKeyState) SetState(v string) {
	o.State = &v
}

func (o RemoteUIKeyState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteUIKeyState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableRemoteUIKeyState struct {
	value *RemoteUIKeyState
	isSet bool
}

func (v NullableRemoteUIKeyState) Get() *RemoteUIKeyState {
	return v.value
}

func (v *NullableRemoteUIKeyState) Set(val *RemoteUIKeyState) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteUIKeyState) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteUIKeyState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteUIKeyState(val *RemoteUIKeyState) *NullableRemoteUIKeyState {
	return &NullableRemoteUIKeyState{value: val, isSet: true}
}

func (v NullableRemoteUIKeyState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteUIKeyState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
