/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the TvProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TvProperties{}

// TvProperties struct for TvProperties
type TvProperties struct {
	IntegrationSupported *TvIntegrationTypes `json:"integrationSupported,omitempty"`
	Name                 NullableString      `json:"name,omitempty"`
	Year                 NullableInt32       `json:"year,omitempty"`
}

// NewTvProperties instantiates a new TvProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTvProperties() *TvProperties {
	this := TvProperties{}
	return &this
}

// NewTvPropertiesWithDefaults instantiates a new TvProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTvPropertiesWithDefaults() *TvProperties {
	this := TvProperties{}
	return &this
}

// GetIntegrationSupported returns the IntegrationSupported field value if set, zero value otherwise.
func (o *TvProperties) GetIntegrationSupported() TvIntegrationTypes {
	if o == nil || IsNil(o.IntegrationSupported) {
		var ret TvIntegrationTypes
		return ret
	}
	return *o.IntegrationSupported
}

// GetIntegrationSupportedOk returns a tuple with the IntegrationSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TvProperties) GetIntegrationSupportedOk() (*TvIntegrationTypes, bool) {
	if o == nil || IsNil(o.IntegrationSupported) {
		return nil, false
	}
	return o.IntegrationSupported, true
}

// HasIntegrationSupported returns a boolean if a field has been set.
func (o *TvProperties) HasIntegrationSupported() bool {
	if o != nil && !IsNil(o.IntegrationSupported) {
		return true
	}

	return false
}

// SetIntegrationSupported gets a reference to the given TvIntegrationTypes and assigns it to the IntegrationSupported field.
func (o *TvProperties) SetIntegrationSupported(v TvIntegrationTypes) {
	o.IntegrationSupported = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TvProperties) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TvProperties) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *TvProperties) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *TvProperties) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *TvProperties) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *TvProperties) UnsetName() {
	o.Name.Unset()
}

// GetYear returns the Year field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TvProperties) GetYear() int32 {
	if o == nil || IsNil(o.Year.Get()) {
		var ret int32
		return ret
	}
	return *o.Year.Get()
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TvProperties) GetYearOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Year.Get(), o.Year.IsSet()
}

// HasYear returns a boolean if a field has been set.
func (o *TvProperties) HasYear() bool {
	if o != nil && o.Year.IsSet() {
		return true
	}

	return false
}

// SetYear gets a reference to the given NullableInt32 and assigns it to the Year field.
func (o *TvProperties) SetYear(v int32) {
	o.Year.Set(&v)
}

// SetYearNil sets the value for Year to be an explicit nil
func (o *TvProperties) SetYearNil() {
	o.Year.Set(nil)
}

// UnsetYear ensures that no value is present for Year, not even an explicit nil
func (o *TvProperties) UnsetYear() {
	o.Year.Unset()
}

func (o TvProperties) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TvProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IntegrationSupported) {
		toSerialize["integrationSupported"] = o.IntegrationSupported
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Year.IsSet() {
		toSerialize["year"] = o.Year.Get()
	}
	return toSerialize, nil
}

type NullableTvProperties struct {
	value *TvProperties
	isSet bool
}

func (v NullableTvProperties) Get() *TvProperties {
	return v.value
}

func (v *NullableTvProperties) Set(val *TvProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableTvProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableTvProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTvProperties(val *TvProperties) *NullableTvProperties {
	return &NullableTvProperties{value: val, isSet: true}
}

func (v NullableTvProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTvProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
