/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventClassicsAdapterContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventClassicsAdapterContent{}

// WebSocketEventClassicsAdapterContent struct for WebSocketEventClassicsAdapterContent
type WebSocketEventClassicsAdapterContent struct {
	EventData *ContentItem `json:"eventData,omitempty"`
	EventType *string      `json:"eventType,omitempty"`
}

// NewWebSocketEventClassicsAdapterContent instantiates a new WebSocketEventClassicsAdapterContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventClassicsAdapterContent() *WebSocketEventClassicsAdapterContent {
	this := WebSocketEventClassicsAdapterContent{}
	return &this
}

// NewWebSocketEventClassicsAdapterContentWithDefaults instantiates a new WebSocketEventClassicsAdapterContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventClassicsAdapterContentWithDefaults() *WebSocketEventClassicsAdapterContent {
	this := WebSocketEventClassicsAdapterContent{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventClassicsAdapterContent) GetEventData() ContentItem {
	if o == nil || IsNil(o.EventData) {
		var ret ContentItem
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventClassicsAdapterContent) GetEventDataOk() (*ContentItem, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventClassicsAdapterContent) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given ContentItem and assigns it to the EventData field.
func (o *WebSocketEventClassicsAdapterContent) SetEventData(v ContentItem) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventClassicsAdapterContent) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventClassicsAdapterContent) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventClassicsAdapterContent) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventClassicsAdapterContent) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventClassicsAdapterContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventClassicsAdapterContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventClassicsAdapterContent struct {
	value *WebSocketEventClassicsAdapterContent
	isSet bool
}

func (v NullableWebSocketEventClassicsAdapterContent) Get() *WebSocketEventClassicsAdapterContent {
	return v.value
}

func (v *NullableWebSocketEventClassicsAdapterContent) Set(val *WebSocketEventClassicsAdapterContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventClassicsAdapterContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventClassicsAdapterContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventClassicsAdapterContent(val *WebSocketEventClassicsAdapterContent) *NullableWebSocketEventClassicsAdapterContent {
	return &NullableWebSocketEventClassicsAdapterContent{value: val, isSet: true}
}

func (v NullableWebSocketEventClassicsAdapterContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventClassicsAdapterContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
