/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the ChannelSurveyStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelSurveyStatus{}

// ChannelSurveyStatus struct for ChannelSurveyStatus
type ChannelSurveyStatus struct {
	Status *string `json:"status,omitempty"`
}

// NewChannelSurveyStatus instantiates a new ChannelSurveyStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelSurveyStatus() *ChannelSurveyStatus {
	this := ChannelSurveyStatus{}
	return &this
}

// NewChannelSurveyStatusWithDefaults instantiates a new ChannelSurveyStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelSurveyStatusWithDefaults() *ChannelSurveyStatus {
	this := ChannelSurveyStatus{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ChannelSurveyStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelSurveyStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ChannelSurveyStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ChannelSurveyStatus) SetStatus(v string) {
	o.Status = &v
}

func (o ChannelSurveyStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelSurveyStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableChannelSurveyStatus struct {
	value *ChannelSurveyStatus
	isSet bool
}

func (v NullableChannelSurveyStatus) Get() *ChannelSurveyStatus {
	return v.value
}

func (v *NullableChannelSurveyStatus) Set(val *ChannelSurveyStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelSurveyStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelSurveyStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelSurveyStatus(val *ChannelSurveyStatus) *NullableChannelSurveyStatus {
	return &NullableChannelSurveyStatus{value: val, isSet: true}
}

func (v NullableChannelSurveyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelSurveyStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
