/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WebSocketEventWisaOutState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventWisaOutState{}

// WebSocketEventWisaOutState Speaker Discovery State changed
type WebSocketEventWisaOutState struct {
	EventData WisaOutState `json:"eventData"`
	EventType string       `json:"eventType"`
}

type _WebSocketEventWisaOutState WebSocketEventWisaOutState

// NewWebSocketEventWisaOutState instantiates a new WebSocketEventWisaOutState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventWisaOutState(eventData WisaOutState, eventType string) *WebSocketEventWisaOutState {
	this := WebSocketEventWisaOutState{}
	this.EventData = eventData
	this.EventType = eventType
	return &this
}

// NewWebSocketEventWisaOutStateWithDefaults instantiates a new WebSocketEventWisaOutState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventWisaOutStateWithDefaults() *WebSocketEventWisaOutState {
	this := WebSocketEventWisaOutState{}
	return &this
}

// GetEventData returns the EventData field value
func (o *WebSocketEventWisaOutState) GetEventData() WisaOutState {
	if o == nil {
		var ret WisaOutState
		return ret
	}

	return o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value
// and a boolean to check if the value has been set.
func (o *WebSocketEventWisaOutState) GetEventDataOk() (*WisaOutState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventData, true
}

// SetEventData sets field value
func (o *WebSocketEventWisaOutState) SetEventData(v WisaOutState) {
	o.EventData = v
}

// GetEventType returns the EventType field value
func (o *WebSocketEventWisaOutState) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *WebSocketEventWisaOutState) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *WebSocketEventWisaOutState) SetEventType(v string) {
	o.EventType = v
}

func (o WebSocketEventWisaOutState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventWisaOutState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["eventData"] = o.EventData
	toSerialize["eventType"] = o.EventType
	return toSerialize, nil
}

func (o *WebSocketEventWisaOutState) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"eventData",
		"eventType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebSocketEventWisaOutState := _WebSocketEventWisaOutState{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebSocketEventWisaOutState)

	if err != nil {
		return err
	}

	*o = WebSocketEventWisaOutState(varWebSocketEventWisaOutState)

	return err
}

type NullableWebSocketEventWisaOutState struct {
	value *WebSocketEventWisaOutState
	isSet bool
}

func (v NullableWebSocketEventWisaOutState) Get() *WebSocketEventWisaOutState {
	return v.value
}

func (v *NullableWebSocketEventWisaOutState) Set(val *WebSocketEventWisaOutState) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventWisaOutState) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventWisaOutState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventWisaOutState(val *WebSocketEventWisaOutState) *NullableWebSocketEventWisaOutState {
	return &NullableWebSocketEventWisaOutState{value: val, isSet: true}
}

func (v NullableWebSocketEventWisaOutState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventWisaOutState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
