/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BeolinkSelf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeolinkSelf{}

// BeolinkSelf struct for BeolinkSelf
type BeolinkSelf struct {
	FriendlyName string `json:"friendlyName"`
	// Beolink peer ID
	Jid string `json:"jid"`
}

type _BeolinkSelf BeolinkSelf

// NewBeolinkSelf instantiates a new BeolinkSelf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeolinkSelf(friendlyName string, jid string) *BeolinkSelf {
	this := BeolinkSelf{}
	this.FriendlyName = friendlyName
	this.Jid = jid
	return &this
}

// NewBeolinkSelfWithDefaults instantiates a new BeolinkSelf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeolinkSelfWithDefaults() *BeolinkSelf {
	this := BeolinkSelf{}
	return &this
}

// GetFriendlyName returns the FriendlyName field value
func (o *BeolinkSelf) GetFriendlyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FriendlyName
}

// GetFriendlyNameOk returns a tuple with the FriendlyName field value
// and a boolean to check if the value has been set.
func (o *BeolinkSelf) GetFriendlyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FriendlyName, true
}

// SetFriendlyName sets field value
func (o *BeolinkSelf) SetFriendlyName(v string) {
	o.FriendlyName = v
}

// GetJid returns the Jid field value
func (o *BeolinkSelf) GetJid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jid
}

// GetJidOk returns a tuple with the Jid field value
// and a boolean to check if the value has been set.
func (o *BeolinkSelf) GetJidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jid, true
}

// SetJid sets field value
func (o *BeolinkSelf) SetJid(v string) {
	o.Jid = v
}

func (o BeolinkSelf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeolinkSelf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["friendlyName"] = o.FriendlyName
	toSerialize["jid"] = o.Jid
	return toSerialize, nil
}

func (o *BeolinkSelf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"friendlyName",
		"jid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBeolinkSelf := _BeolinkSelf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBeolinkSelf)

	if err != nil {
		return err
	}

	*o = BeolinkSelf(varBeolinkSelf)

	return err
}

type NullableBeolinkSelf struct {
	value *BeolinkSelf
	isSet bool
}

func (v NullableBeolinkSelf) Get() *BeolinkSelf {
	return v.value
}

func (v *NullableBeolinkSelf) Set(val *BeolinkSelf) {
	v.value = val
	v.isSet = true
}

func (v NullableBeolinkSelf) IsSet() bool {
	return v.isSet
}

func (v *NullableBeolinkSelf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeolinkSelf(val *BeolinkSelf) *NullableBeolinkSelf {
	return &NullableBeolinkSelf{value: val, isSet: true}
}

func (v NullableBeolinkSelf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeolinkSelf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
