/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the VolumeSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumeSettings{}

// VolumeSettings struct for VolumeSettings
type VolumeSettings struct {
	Default *VolumeLevel `json:"default,omitempty"`
	Maximum *VolumeLevel `json:"maximum,omitempty"`
}

// NewVolumeSettings instantiates a new VolumeSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeSettings() *VolumeSettings {
	this := VolumeSettings{}
	return &this
}

// NewVolumeSettingsWithDefaults instantiates a new VolumeSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeSettingsWithDefaults() *VolumeSettings {
	this := VolumeSettings{}
	return &this
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *VolumeSettings) GetDefault() VolumeLevel {
	if o == nil || IsNil(o.Default) {
		var ret VolumeLevel
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeSettings) GetDefaultOk() (*VolumeLevel, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *VolumeSettings) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given VolumeLevel and assigns it to the Default field.
func (o *VolumeSettings) SetDefault(v VolumeLevel) {
	o.Default = &v
}

// GetMaximum returns the Maximum field value if set, zero value otherwise.
func (o *VolumeSettings) GetMaximum() VolumeLevel {
	if o == nil || IsNil(o.Maximum) {
		var ret VolumeLevel
		return ret
	}
	return *o.Maximum
}

// GetMaximumOk returns a tuple with the Maximum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeSettings) GetMaximumOk() (*VolumeLevel, bool) {
	if o == nil || IsNil(o.Maximum) {
		return nil, false
	}
	return o.Maximum, true
}

// HasMaximum returns a boolean if a field has been set.
func (o *VolumeSettings) HasMaximum() bool {
	if o != nil && !IsNil(o.Maximum) {
		return true
	}

	return false
}

// SetMaximum gets a reference to the given VolumeLevel and assigns it to the Maximum field.
func (o *VolumeSettings) SetMaximum(v VolumeLevel) {
	o.Maximum = &v
}

func (o VolumeSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumeSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if !IsNil(o.Maximum) {
		toSerialize["maximum"] = o.Maximum
	}
	return toSerialize, nil
}

type NullableVolumeSettings struct {
	value *VolumeSettings
	isSet bool
}

func (v NullableVolumeSettings) Get() *VolumeSettings {
	return v.value
}

func (v *NullableVolumeSettings) Set(val *VolumeSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeSettings(val *VolumeSettings) *NullableVolumeSettings {
	return &NullableVolumeSettings{value: val, isSet: true}
}

func (v NullableVolumeSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
