/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the VideoPixelFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VideoPixelFormat{}

// VideoPixelFormat struct for VideoPixelFormat
type VideoPixelFormat struct {
	Bitdepth        *string `json:"bitdepth,omitempty"`
	ChromaSubsample *string `json:"chromaSubsample,omitempty"`
	Colorimetry     *string `json:"colorimetry,omitempty"`
	FullRange       *bool   `json:"fullRange,omitempty"`
}

// NewVideoPixelFormat instantiates a new VideoPixelFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoPixelFormat() *VideoPixelFormat {
	this := VideoPixelFormat{}
	return &this
}

// NewVideoPixelFormatWithDefaults instantiates a new VideoPixelFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoPixelFormatWithDefaults() *VideoPixelFormat {
	this := VideoPixelFormat{}
	return &this
}

// GetBitdepth returns the Bitdepth field value if set, zero value otherwise.
func (o *VideoPixelFormat) GetBitdepth() string {
	if o == nil || IsNil(o.Bitdepth) {
		var ret string
		return ret
	}
	return *o.Bitdepth
}

// GetBitdepthOk returns a tuple with the Bitdepth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoPixelFormat) GetBitdepthOk() (*string, bool) {
	if o == nil || IsNil(o.Bitdepth) {
		return nil, false
	}
	return o.Bitdepth, true
}

// HasBitdepth returns a boolean if a field has been set.
func (o *VideoPixelFormat) HasBitdepth() bool {
	if o != nil && !IsNil(o.Bitdepth) {
		return true
	}

	return false
}

// SetBitdepth gets a reference to the given string and assigns it to the Bitdepth field.
func (o *VideoPixelFormat) SetBitdepth(v string) {
	o.Bitdepth = &v
}

// GetChromaSubsample returns the ChromaSubsample field value if set, zero value otherwise.
func (o *VideoPixelFormat) GetChromaSubsample() string {
	if o == nil || IsNil(o.ChromaSubsample) {
		var ret string
		return ret
	}
	return *o.ChromaSubsample
}

// GetChromaSubsampleOk returns a tuple with the ChromaSubsample field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoPixelFormat) GetChromaSubsampleOk() (*string, bool) {
	if o == nil || IsNil(o.ChromaSubsample) {
		return nil, false
	}
	return o.ChromaSubsample, true
}

// HasChromaSubsample returns a boolean if a field has been set.
func (o *VideoPixelFormat) HasChromaSubsample() bool {
	if o != nil && !IsNil(o.ChromaSubsample) {
		return true
	}

	return false
}

// SetChromaSubsample gets a reference to the given string and assigns it to the ChromaSubsample field.
func (o *VideoPixelFormat) SetChromaSubsample(v string) {
	o.ChromaSubsample = &v
}

// GetColorimetry returns the Colorimetry field value if set, zero value otherwise.
func (o *VideoPixelFormat) GetColorimetry() string {
	if o == nil || IsNil(o.Colorimetry) {
		var ret string
		return ret
	}
	return *o.Colorimetry
}

// GetColorimetryOk returns a tuple with the Colorimetry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoPixelFormat) GetColorimetryOk() (*string, bool) {
	if o == nil || IsNil(o.Colorimetry) {
		return nil, false
	}
	return o.Colorimetry, true
}

// HasColorimetry returns a boolean if a field has been set.
func (o *VideoPixelFormat) HasColorimetry() bool {
	if o != nil && !IsNil(o.Colorimetry) {
		return true
	}

	return false
}

// SetColorimetry gets a reference to the given string and assigns it to the Colorimetry field.
func (o *VideoPixelFormat) SetColorimetry(v string) {
	o.Colorimetry = &v
}

// GetFullRange returns the FullRange field value if set, zero value otherwise.
func (o *VideoPixelFormat) GetFullRange() bool {
	if o == nil || IsNil(o.FullRange) {
		var ret bool
		return ret
	}
	return *o.FullRange
}

// GetFullRangeOk returns a tuple with the FullRange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoPixelFormat) GetFullRangeOk() (*bool, bool) {
	if o == nil || IsNil(o.FullRange) {
		return nil, false
	}
	return o.FullRange, true
}

// HasFullRange returns a boolean if a field has been set.
func (o *VideoPixelFormat) HasFullRange() bool {
	if o != nil && !IsNil(o.FullRange) {
		return true
	}

	return false
}

// SetFullRange gets a reference to the given bool and assigns it to the FullRange field.
func (o *VideoPixelFormat) SetFullRange(v bool) {
	o.FullRange = &v
}

func (o VideoPixelFormat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VideoPixelFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bitdepth) {
		toSerialize["bitdepth"] = o.Bitdepth
	}
	if !IsNil(o.ChromaSubsample) {
		toSerialize["chromaSubsample"] = o.ChromaSubsample
	}
	if !IsNil(o.Colorimetry) {
		toSerialize["colorimetry"] = o.Colorimetry
	}
	if !IsNil(o.FullRange) {
		toSerialize["fullRange"] = o.FullRange
	}
	return toSerialize, nil
}

type NullableVideoPixelFormat struct {
	value *VideoPixelFormat
	isSet bool
}

func (v NullableVideoPixelFormat) Get() *VideoPixelFormat {
	return v.value
}

func (v *NullableVideoPixelFormat) Set(val *VideoPixelFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoPixelFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoPixelFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoPixelFormat(val *VideoPixelFormat) *NullableVideoPixelFormat {
	return &NullableVideoPixelFormat{value: val, isSet: true}
}

func (v NullableVideoPixelFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoPixelFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
