/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpeechEnhanceRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpeechEnhanceRange{}

// SpeechEnhanceRange struct for SpeechEnhanceRange
type SpeechEnhanceRange struct {
	Default SpeechEnhance `json:"default"`
	// speech-enhance range
	Range []SpeechEnhance `json:"range"`
}

type _SpeechEnhanceRange SpeechEnhanceRange

// NewSpeechEnhanceRange instantiates a new SpeechEnhanceRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpeechEnhanceRange(default_ SpeechEnhance, range_ []SpeechEnhance) *SpeechEnhanceRange {
	this := SpeechEnhanceRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewSpeechEnhanceRangeWithDefaults instantiates a new SpeechEnhanceRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpeechEnhanceRangeWithDefaults() *SpeechEnhanceRange {
	this := SpeechEnhanceRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *SpeechEnhanceRange) GetDefault() SpeechEnhance {
	if o == nil {
		var ret SpeechEnhance
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *SpeechEnhanceRange) GetDefaultOk() (*SpeechEnhance, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *SpeechEnhanceRange) SetDefault(v SpeechEnhance) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *SpeechEnhanceRange) GetRange() []SpeechEnhance {
	if o == nil {
		var ret []SpeechEnhance
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *SpeechEnhanceRange) GetRangeOk() ([]SpeechEnhance, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *SpeechEnhanceRange) SetRange(v []SpeechEnhance) {
	o.Range = v
}

func (o SpeechEnhanceRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpeechEnhanceRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *SpeechEnhanceRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpeechEnhanceRange := _SpeechEnhanceRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpeechEnhanceRange)

	if err != nil {
		return err
	}

	*o = SpeechEnhanceRange(varSpeechEnhanceRange)

	return err
}

type NullableSpeechEnhanceRange struct {
	value *SpeechEnhanceRange
	isSet bool
}

func (v NullableSpeechEnhanceRange) Get() *SpeechEnhanceRange {
	return v.value
}

func (v *NullableSpeechEnhanceRange) Set(val *SpeechEnhanceRange) {
	v.value = val
	v.isSet = true
}

func (v NullableSpeechEnhanceRange) IsSet() bool {
	return v.isSet
}

func (v *NullableSpeechEnhanceRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpeechEnhanceRange(val *SpeechEnhanceRange) *NullableSpeechEnhanceRange {
	return &NullableSpeechEnhanceRange{value: val, isSet: true}
}

func (v NullableSpeechEnhanceRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpeechEnhanceRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
