/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the PowerLinkTrigger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PowerLinkTrigger{}

// PowerLinkTrigger struct for PowerLinkTrigger
type PowerLinkTrigger struct {
	// Despite the name, this preset is used anytime a speaker is used as a secondary as a way for the primary to indicate which directivity (and possibly other characteristics in the future) should be used on a speaker by speaker basis. It is used when a speaker is a powerlink speaker (hence the name), WISA speaker or a speakerlink secondary in multichannel.
	PowerLinkPreset *int32 `json:"powerLinkPreset,omitempty"`
}

// NewPowerLinkTrigger instantiates a new PowerLinkTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPowerLinkTrigger() *PowerLinkTrigger {
	this := PowerLinkTrigger{}
	return &this
}

// NewPowerLinkTriggerWithDefaults instantiates a new PowerLinkTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPowerLinkTriggerWithDefaults() *PowerLinkTrigger {
	this := PowerLinkTrigger{}
	return &this
}

// GetPowerLinkPreset returns the PowerLinkPreset field value if set, zero value otherwise.
func (o *PowerLinkTrigger) GetPowerLinkPreset() int32 {
	if o == nil || IsNil(o.PowerLinkPreset) {
		var ret int32
		return ret
	}
	return *o.PowerLinkPreset
}

// GetPowerLinkPresetOk returns a tuple with the PowerLinkPreset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerLinkTrigger) GetPowerLinkPresetOk() (*int32, bool) {
	if o == nil || IsNil(o.PowerLinkPreset) {
		return nil, false
	}
	return o.PowerLinkPreset, true
}

// HasPowerLinkPreset returns a boolean if a field has been set.
func (o *PowerLinkTrigger) HasPowerLinkPreset() bool {
	if o != nil && !IsNil(o.PowerLinkPreset) {
		return true
	}

	return false
}

// SetPowerLinkPreset gets a reference to the given int32 and assigns it to the PowerLinkPreset field.
func (o *PowerLinkTrigger) SetPowerLinkPreset(v int32) {
	o.PowerLinkPreset = &v
}

func (o PowerLinkTrigger) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PowerLinkTrigger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PowerLinkPreset) {
		toSerialize["powerLinkPreset"] = o.PowerLinkPreset
	}
	return toSerialize, nil
}

type NullablePowerLinkTrigger struct {
	value *PowerLinkTrigger
	isSet bool
}

func (v NullablePowerLinkTrigger) Get() *PowerLinkTrigger {
	return v.value
}

func (v *NullablePowerLinkTrigger) Set(val *PowerLinkTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullablePowerLinkTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullablePowerLinkTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePowerLinkTrigger(val *PowerLinkTrigger) *NullablePowerLinkTrigger {
	return &NullablePowerLinkTrigger{value: val, isSet: true}
}

func (v NullablePowerLinkTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePowerLinkTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
