/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BeolinkAvailableListener type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeolinkAvailableListener{}

// BeolinkAvailableListener struct for BeolinkAvailableListener
type BeolinkAvailableListener struct {
	// Beolink peer ID
	Jid string `json:"jid"`
}

type _BeolinkAvailableListener BeolinkAvailableListener

// NewBeolinkAvailableListener instantiates a new BeolinkAvailableListener object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeolinkAvailableListener(jid string) *BeolinkAvailableListener {
	this := BeolinkAvailableListener{}
	this.Jid = jid
	return &this
}

// NewBeolinkAvailableListenerWithDefaults instantiates a new BeolinkAvailableListener object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeolinkAvailableListenerWithDefaults() *BeolinkAvailableListener {
	this := BeolinkAvailableListener{}
	return &this
}

// GetJid returns the Jid field value
func (o *BeolinkAvailableListener) GetJid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jid
}

// GetJidOk returns a tuple with the Jid field value
// and a boolean to check if the value has been set.
func (o *BeolinkAvailableListener) GetJidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jid, true
}

// SetJid sets field value
func (o *BeolinkAvailableListener) SetJid(v string) {
	o.Jid = v
}

func (o BeolinkAvailableListener) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeolinkAvailableListener) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jid"] = o.Jid
	return toSerialize, nil
}

func (o *BeolinkAvailableListener) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBeolinkAvailableListener := _BeolinkAvailableListener{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBeolinkAvailableListener)

	if err != nil {
		return err
	}

	*o = BeolinkAvailableListener(varBeolinkAvailableListener)

	return err
}

type NullableBeolinkAvailableListener struct {
	value *BeolinkAvailableListener
	isSet bool
}

func (v NullableBeolinkAvailableListener) Get() *BeolinkAvailableListener {
	return v.value
}

func (v *NullableBeolinkAvailableListener) Set(val *BeolinkAvailableListener) {
	v.value = val
	v.isSet = true
}

func (v NullableBeolinkAvailableListener) IsSet() bool {
	return v.isSet
}

func (v *NullableBeolinkAvailableListener) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeolinkAvailableListener(val *BeolinkAvailableListener) *NullableBeolinkAvailableListener {
	return &NullableBeolinkAvailableListener{value: val, isSet: true}
}

func (v NullableBeolinkAvailableListener) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeolinkAvailableListener) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
