/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpeakerGroupMemberLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpeakerGroupMemberLocation{}

// SpeakerGroupMemberLocation Coordinates of the speaker position in cm. Location is only relevant when the group is based on the automatic role assignment of advanced room compensation. The location is relative to the external microphone used during advanced room compensation measurements:   x=0, y=0, z=0: The location of the external microphone used during measurement.   x<0: To the left of the external microphone.   x>0: To the right of the external microphone.   y<0: Behind the external microphone.   y>0: In front of the external microphone.   z<0: Above the external microphone (may not be reliable).   z>0: Below the external microphone (may not be reliable).
type SpeakerGroupMemberLocation struct {
	X int32 `json:"x"`
	Y int32 `json:"y"`
	Z int32 `json:"z"`
}

type _SpeakerGroupMemberLocation SpeakerGroupMemberLocation

// NewSpeakerGroupMemberLocation instantiates a new SpeakerGroupMemberLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpeakerGroupMemberLocation(x int32, y int32, z int32) *SpeakerGroupMemberLocation {
	this := SpeakerGroupMemberLocation{}
	this.X = x
	this.Y = y
	this.Z = z
	return &this
}

// NewSpeakerGroupMemberLocationWithDefaults instantiates a new SpeakerGroupMemberLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpeakerGroupMemberLocationWithDefaults() *SpeakerGroupMemberLocation {
	this := SpeakerGroupMemberLocation{}
	return &this
}

// GetX returns the X field value
func (o *SpeakerGroupMemberLocation) GetX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *SpeakerGroupMemberLocation) GetXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *SpeakerGroupMemberLocation) SetX(v int32) {
	o.X = v
}

// GetY returns the Y field value
func (o *SpeakerGroupMemberLocation) GetY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *SpeakerGroupMemberLocation) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *SpeakerGroupMemberLocation) SetY(v int32) {
	o.Y = v
}

// GetZ returns the Z field value
func (o *SpeakerGroupMemberLocation) GetZ() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Z
}

// GetZOk returns a tuple with the Z field value
// and a boolean to check if the value has been set.
func (o *SpeakerGroupMemberLocation) GetZOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Z, true
}

// SetZ sets field value
func (o *SpeakerGroupMemberLocation) SetZ(v int32) {
	o.Z = v
}

func (o SpeakerGroupMemberLocation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpeakerGroupMemberLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y
	toSerialize["z"] = o.Z
	return toSerialize, nil
}

func (o *SpeakerGroupMemberLocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"x",
		"y",
		"z",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpeakerGroupMemberLocation := _SpeakerGroupMemberLocation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpeakerGroupMemberLocation)

	if err != nil {
		return err
	}

	*o = SpeakerGroupMemberLocation(varSpeakerGroupMemberLocation)

	return err
}

type NullableSpeakerGroupMemberLocation struct {
	value *SpeakerGroupMemberLocation
	isSet bool
}

func (v NullableSpeakerGroupMemberLocation) Get() *SpeakerGroupMemberLocation {
	return v.value
}

func (v *NullableSpeakerGroupMemberLocation) Set(val *SpeakerGroupMemberLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableSpeakerGroupMemberLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableSpeakerGroupMemberLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpeakerGroupMemberLocation(val *SpeakerGroupMemberLocation) *NullableSpeakerGroupMemberLocation {
	return &NullableSpeakerGroupMemberLocation{value: val, isSet: true}
}

func (v NullableSpeakerGroupMemberLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpeakerGroupMemberLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
