/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the Source type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Source{}

// Source struct for Source
type Source struct {
	Id *string `json:"id,omitempty"`
	// some sources require an explicit activation or accept of terms before being enabled
	IsEnabled            *bool           `json:"isEnabled,omitempty"`
	IsMultiroomAvailable *bool           `json:"isMultiroomAvailable,omitempty"`
	IsPlayable           *bool           `json:"isPlayable,omitempty"`
	IsSeekable           *bool           `json:"isSeekable,omitempty"`
	Name                 *string         `json:"name,omitempty"`
	Type                 *SourceTypeEnum `json:"type,omitempty"`
}

// NewSource instantiates a new Source object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSource() *Source {
	this := Source{}
	return &this
}

// NewSourceWithDefaults instantiates a new Source object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceWithDefaults() *Source {
	this := Source{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Source) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Source) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Source) SetId(v string) {
	o.Id = &v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *Source) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *Source) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *Source) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetIsMultiroomAvailable returns the IsMultiroomAvailable field value if set, zero value otherwise.
func (o *Source) GetIsMultiroomAvailable() bool {
	if o == nil || IsNil(o.IsMultiroomAvailable) {
		var ret bool
		return ret
	}
	return *o.IsMultiroomAvailable
}

// GetIsMultiroomAvailableOk returns a tuple with the IsMultiroomAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetIsMultiroomAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMultiroomAvailable) {
		return nil, false
	}
	return o.IsMultiroomAvailable, true
}

// HasIsMultiroomAvailable returns a boolean if a field has been set.
func (o *Source) HasIsMultiroomAvailable() bool {
	if o != nil && !IsNil(o.IsMultiroomAvailable) {
		return true
	}

	return false
}

// SetIsMultiroomAvailable gets a reference to the given bool and assigns it to the IsMultiroomAvailable field.
func (o *Source) SetIsMultiroomAvailable(v bool) {
	o.IsMultiroomAvailable = &v
}

// GetIsPlayable returns the IsPlayable field value if set, zero value otherwise.
func (o *Source) GetIsPlayable() bool {
	if o == nil || IsNil(o.IsPlayable) {
		var ret bool
		return ret
	}
	return *o.IsPlayable
}

// GetIsPlayableOk returns a tuple with the IsPlayable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetIsPlayableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPlayable) {
		return nil, false
	}
	return o.IsPlayable, true
}

// HasIsPlayable returns a boolean if a field has been set.
func (o *Source) HasIsPlayable() bool {
	if o != nil && !IsNil(o.IsPlayable) {
		return true
	}

	return false
}

// SetIsPlayable gets a reference to the given bool and assigns it to the IsPlayable field.
func (o *Source) SetIsPlayable(v bool) {
	o.IsPlayable = &v
}

// GetIsSeekable returns the IsSeekable field value if set, zero value otherwise.
func (o *Source) GetIsSeekable() bool {
	if o == nil || IsNil(o.IsSeekable) {
		var ret bool
		return ret
	}
	return *o.IsSeekable
}

// GetIsSeekableOk returns a tuple with the IsSeekable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetIsSeekableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSeekable) {
		return nil, false
	}
	return o.IsSeekable, true
}

// HasIsSeekable returns a boolean if a field has been set.
func (o *Source) HasIsSeekable() bool {
	if o != nil && !IsNil(o.IsSeekable) {
		return true
	}

	return false
}

// SetIsSeekable gets a reference to the given bool and assigns it to the IsSeekable field.
func (o *Source) SetIsSeekable(v bool) {
	o.IsSeekable = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Source) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Source) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Source) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Source) GetType() SourceTypeEnum {
	if o == nil || IsNil(o.Type) {
		var ret SourceTypeEnum
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Source) GetTypeOk() (*SourceTypeEnum, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Source) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given SourceTypeEnum and assigns it to the Type field.
func (o *Source) SetType(v SourceTypeEnum) {
	o.Type = &v
}

func (o Source) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Source) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["isEnabled"] = o.IsEnabled
	}
	if !IsNil(o.IsMultiroomAvailable) {
		toSerialize["isMultiroomAvailable"] = o.IsMultiroomAvailable
	}
	if !IsNil(o.IsPlayable) {
		toSerialize["isPlayable"] = o.IsPlayable
	}
	if !IsNil(o.IsSeekable) {
		toSerialize["isSeekable"] = o.IsSeekable
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableSource struct {
	value *Source
	isSet bool
}

func (v NullableSource) Get() *Source {
	return v.value
}

func (v *NullableSource) Set(val *Source) {
	v.value = val
	v.isSet = true
}

func (v NullableSource) IsSet() bool {
	return v.isSet
}

func (v *NullableSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSource(val *Source) *NullableSource {
	return &NullableSource{value: val, isSet: true}
}

func (v NullableSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
