/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventBattery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventBattery{}

// WebSocketEventBattery struct for WebSocketEventBattery
type WebSocketEventBattery struct {
	EventData *BatteryState `json:"eventData,omitempty"`
	EventType *string       `json:"eventType,omitempty"`
}

// NewWebSocketEventBattery instantiates a new WebSocketEventBattery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventBattery() *WebSocketEventBattery {
	this := WebSocketEventBattery{}
	return &this
}

// NewWebSocketEventBatteryWithDefaults instantiates a new WebSocketEventBattery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventBatteryWithDefaults() *WebSocketEventBattery {
	this := WebSocketEventBattery{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventBattery) GetEventData() BatteryState {
	if o == nil || IsNil(o.EventData) {
		var ret BatteryState
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventBattery) GetEventDataOk() (*BatteryState, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventBattery) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given BatteryState and assigns it to the EventData field.
func (o *WebSocketEventBattery) SetEventData(v BatteryState) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventBattery) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventBattery) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventBattery) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventBattery) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventBattery) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventBattery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventBattery struct {
	value *WebSocketEventBattery
	isSet bool
}

func (v NullableWebSocketEventBattery) Get() *WebSocketEventBattery {
	return v.value
}

func (v *NullableWebSocketEventBattery) Set(val *WebSocketEventBattery) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventBattery) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventBattery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventBattery(val *WebSocketEventBattery) *NullableWebSocketEventBattery {
	return &NullableWebSocketEventBattery{value: val, isSet: true}
}

func (v NullableWebSocketEventBattery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventBattery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
