/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpeakerGroupOverview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpeakerGroupOverview{}

// SpeakerGroupOverview struct for SpeakerGroupOverview
type SpeakerGroupOverview struct {
	FriendlyName string `json:"friendlyName"`
	Id           string `json:"id"`
	IsDeleteable bool   `json:"isDeleteable"`
}

type _SpeakerGroupOverview SpeakerGroupOverview

// NewSpeakerGroupOverview instantiates a new SpeakerGroupOverview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpeakerGroupOverview(friendlyName string, id string, isDeleteable bool) *SpeakerGroupOverview {
	this := SpeakerGroupOverview{}
	this.FriendlyName = friendlyName
	this.Id = id
	this.IsDeleteable = isDeleteable
	return &this
}

// NewSpeakerGroupOverviewWithDefaults instantiates a new SpeakerGroupOverview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpeakerGroupOverviewWithDefaults() *SpeakerGroupOverview {
	this := SpeakerGroupOverview{}
	return &this
}

// GetFriendlyName returns the FriendlyName field value
func (o *SpeakerGroupOverview) GetFriendlyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FriendlyName
}

// GetFriendlyNameOk returns a tuple with the FriendlyName field value
// and a boolean to check if the value has been set.
func (o *SpeakerGroupOverview) GetFriendlyNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FriendlyName, true
}

// SetFriendlyName sets field value
func (o *SpeakerGroupOverview) SetFriendlyName(v string) {
	o.FriendlyName = v
}

// GetId returns the Id field value
func (o *SpeakerGroupOverview) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SpeakerGroupOverview) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SpeakerGroupOverview) SetId(v string) {
	o.Id = v
}

// GetIsDeleteable returns the IsDeleteable field value
func (o *SpeakerGroupOverview) GetIsDeleteable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDeleteable
}

// GetIsDeleteableOk returns a tuple with the IsDeleteable field value
// and a boolean to check if the value has been set.
func (o *SpeakerGroupOverview) GetIsDeleteableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeleteable, true
}

// SetIsDeleteable sets field value
func (o *SpeakerGroupOverview) SetIsDeleteable(v bool) {
	o.IsDeleteable = v
}

func (o SpeakerGroupOverview) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpeakerGroupOverview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["friendlyName"] = o.FriendlyName
	toSerialize["id"] = o.Id
	toSerialize["isDeleteable"] = o.IsDeleteable
	return toSerialize, nil
}

func (o *SpeakerGroupOverview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"friendlyName",
		"id",
		"isDeleteable",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpeakerGroupOverview := _SpeakerGroupOverview{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpeakerGroupOverview)

	if err != nil {
		return err
	}

	*o = SpeakerGroupOverview(varSpeakerGroupOverview)

	return err
}

type NullableSpeakerGroupOverview struct {
	value *SpeakerGroupOverview
	isSet bool
}

func (v NullableSpeakerGroupOverview) Get() *SpeakerGroupOverview {
	return v.value
}

func (v *NullableSpeakerGroupOverview) Set(val *SpeakerGroupOverview) {
	v.value = val
	v.isSet = true
}

func (v NullableSpeakerGroupOverview) IsSet() bool {
	return v.isSet
}

func (v *NullableSpeakerGroupOverview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpeakerGroupOverview(val *SpeakerGroupOverview) *NullableSpeakerGroupOverview {
	return &NullableSpeakerGroupOverview{value: val, isSet: true}
}

func (v NullableSpeakerGroupOverview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpeakerGroupOverview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
