/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the Art type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Art{}

// Art struct for Art
type Art struct {
	HasLocalImage *bool   `json:"hasLocalImage,omitempty"`
	Key           *string `json:"key,omitempty"`
	Size          *string `json:"size,omitempty"`
	Type          *string `json:"type,omitempty"`
	Url           *string `json:"url,omitempty"`
}

// NewArt instantiates a new Art object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArt() *Art {
	this := Art{}
	return &this
}

// NewArtWithDefaults instantiates a new Art object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtWithDefaults() *Art {
	this := Art{}
	return &this
}

// GetHasLocalImage returns the HasLocalImage field value if set, zero value otherwise.
func (o *Art) GetHasLocalImage() bool {
	if o == nil || IsNil(o.HasLocalImage) {
		var ret bool
		return ret
	}
	return *o.HasLocalImage
}

// GetHasLocalImageOk returns a tuple with the HasLocalImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Art) GetHasLocalImageOk() (*bool, bool) {
	if o == nil || IsNil(o.HasLocalImage) {
		return nil, false
	}
	return o.HasLocalImage, true
}

// HasHasLocalImage returns a boolean if a field has been set.
func (o *Art) HasHasLocalImage() bool {
	if o != nil && !IsNil(o.HasLocalImage) {
		return true
	}

	return false
}

// SetHasLocalImage gets a reference to the given bool and assigns it to the HasLocalImage field.
func (o *Art) SetHasLocalImage(v bool) {
	o.HasLocalImage = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *Art) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Art) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *Art) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *Art) SetKey(v string) {
	o.Key = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Art) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Art) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Art) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *Art) SetSize(v string) {
	o.Size = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Art) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Art) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Art) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Art) SetType(v string) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Art) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Art) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Art) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Art) SetUrl(v string) {
	o.Url = &v
}

func (o Art) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Art) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasLocalImage) {
		toSerialize["hasLocalImage"] = o.HasLocalImage
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableArt struct {
	value *Art
	isSet bool
}

func (v NullableArt) Get() *Art {
	return v.value
}

func (v *NullableArt) Set(val *Art) {
	v.value = val
	v.isSet = true
}

func (v NullableArt) IsSet() bool {
	return v.isSet
}

func (v *NullableArt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArt(val *Art) *NullableArt {
	return &NullableArt{value: val, isSet: true}
}

func (v NullableArt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
