/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BassManagement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BassManagement{}

// BassManagement struct for BassManagement
type BassManagement struct {
	// Selected bass-management value
	Value string `json:"value"`
}

type _BassManagement BassManagement

// NewBassManagement instantiates a new BassManagement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBassManagement(value string) *BassManagement {
	this := BassManagement{}
	this.Value = value
	return &this
}

// NewBassManagementWithDefaults instantiates a new BassManagement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBassManagementWithDefaults() *BassManagement {
	this := BassManagement{}
	return &this
}

// GetValue returns the Value field value
func (o *BassManagement) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BassManagement) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BassManagement) SetValue(v string) {
	o.Value = v
}

func (o BassManagement) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BassManagement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *BassManagement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBassManagement := _BassManagement{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBassManagement)

	if err != nil {
		return err
	}

	*o = BassManagement(varBassManagement)

	return err
}

type NullableBassManagement struct {
	value *BassManagement
	isSet bool
}

func (v NullableBassManagement) Get() *BassManagement {
	return v.value
}

func (v *NullableBassManagement) Set(val *BassManagement) {
	v.value = val
	v.isSet = true
}

func (v NullableBassManagement) IsSet() bool {
	return v.isSet
}

func (v *NullableBassManagement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBassManagement(val *BassManagement) *NullableBassManagement {
	return &NullableBassManagement{value: val, isSet: true}
}

func (v NullableBassManagement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBassManagement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
