/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the RoomCompensationMeasurementError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoomCompensationMeasurementError{}

// RoomCompensationMeasurementError struct for RoomCompensationMeasurementError
type RoomCompensationMeasurementError struct {
	// noError:   The measurement went OK. lowSignal:   When there is too low signal in the recording, e.g. due to a loudspeaker being placed at   too great a distance from the microphone. speakerSilent:   No signal could be measured.   Could be because:     - The speaker is powered off or not connected.     - The left/right switch on a wired powerlink speaker is set in the wrong position.     - The speaker is placed in another room behind closed doors. noisy<Left/Right/External>Microphone:   When the recording of the given microphone is too noisy.   Could be because:     - Something is blocking the microphone externalMicrophoneLocation:   When the location of the external microphone is invalid. externalMicrophoneMissing:   If the external microphone was missing/disconnected during a measurement. microphonesDisabled:   If the microphones are either muted or disabled. noisyMeasurement:   When too much background noise has been detected during the measurement internalError:   Something went wrong internally - can not be fixed by the user. Try again.
	Error     *string `json:"error,omitempty"`
	SpeakerId *string `json:"speakerId,omitempty"`
}

// NewRoomCompensationMeasurementError instantiates a new RoomCompensationMeasurementError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoomCompensationMeasurementError() *RoomCompensationMeasurementError {
	this := RoomCompensationMeasurementError{}
	return &this
}

// NewRoomCompensationMeasurementErrorWithDefaults instantiates a new RoomCompensationMeasurementError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoomCompensationMeasurementErrorWithDefaults() *RoomCompensationMeasurementError {
	this := RoomCompensationMeasurementError{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *RoomCompensationMeasurementError) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationMeasurementError) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *RoomCompensationMeasurementError) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *RoomCompensationMeasurementError) SetError(v string) {
	o.Error = &v
}

// GetSpeakerId returns the SpeakerId field value if set, zero value otherwise.
func (o *RoomCompensationMeasurementError) GetSpeakerId() string {
	if o == nil || IsNil(o.SpeakerId) {
		var ret string
		return ret
	}
	return *o.SpeakerId
}

// GetSpeakerIdOk returns a tuple with the SpeakerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoomCompensationMeasurementError) GetSpeakerIdOk() (*string, bool) {
	if o == nil || IsNil(o.SpeakerId) {
		return nil, false
	}
	return o.SpeakerId, true
}

// HasSpeakerId returns a boolean if a field has been set.
func (o *RoomCompensationMeasurementError) HasSpeakerId() bool {
	if o != nil && !IsNil(o.SpeakerId) {
		return true
	}

	return false
}

// SetSpeakerId gets a reference to the given string and assigns it to the SpeakerId field.
func (o *RoomCompensationMeasurementError) SetSpeakerId(v string) {
	o.SpeakerId = &v
}

func (o RoomCompensationMeasurementError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoomCompensationMeasurementError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.SpeakerId) {
		toSerialize["speakerId"] = o.SpeakerId
	}
	return toSerialize, nil
}

type NullableRoomCompensationMeasurementError struct {
	value *RoomCompensationMeasurementError
	isSet bool
}

func (v NullableRoomCompensationMeasurementError) Get() *RoomCompensationMeasurementError {
	return v.value
}

func (v *NullableRoomCompensationMeasurementError) Set(val *RoomCompensationMeasurementError) {
	v.value = val
	v.isSet = true
}

func (v NullableRoomCompensationMeasurementError) IsSet() bool {
	return v.isSet
}

func (v *NullableRoomCompensationMeasurementError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoomCompensationMeasurementError(val *RoomCompensationMeasurementError) *NullableRoomCompensationMeasurementError {
	return &NullableRoomCompensationMeasurementError{value: val, isSet: true}
}

func (v NullableRoomCompensationMeasurementError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoomCompensationMeasurementError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
