/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the SoundSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoundSettings{}

// SoundSettings struct for SoundSettings
type SoundSettings struct {
	Adjustments      *SoundAdjustments     `json:"adjustments,omitempty"`
	RoomCompensation *RoomCompensationInfo `json:"roomCompensation,omitempty"`
	ToneTouch        *SoundToneTouch       `json:"toneTouch,omitempty"`
}

// NewSoundSettings instantiates a new SoundSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoundSettings() *SoundSettings {
	this := SoundSettings{}
	return &this
}

// NewSoundSettingsWithDefaults instantiates a new SoundSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoundSettingsWithDefaults() *SoundSettings {
	this := SoundSettings{}
	return &this
}

// GetAdjustments returns the Adjustments field value if set, zero value otherwise.
func (o *SoundSettings) GetAdjustments() SoundAdjustments {
	if o == nil || IsNil(o.Adjustments) {
		var ret SoundAdjustments
		return ret
	}
	return *o.Adjustments
}

// GetAdjustmentsOk returns a tuple with the Adjustments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundSettings) GetAdjustmentsOk() (*SoundAdjustments, bool) {
	if o == nil || IsNil(o.Adjustments) {
		return nil, false
	}
	return o.Adjustments, true
}

// HasAdjustments returns a boolean if a field has been set.
func (o *SoundSettings) HasAdjustments() bool {
	if o != nil && !IsNil(o.Adjustments) {
		return true
	}

	return false
}

// SetAdjustments gets a reference to the given SoundAdjustments and assigns it to the Adjustments field.
func (o *SoundSettings) SetAdjustments(v SoundAdjustments) {
	o.Adjustments = &v
}

// GetRoomCompensation returns the RoomCompensation field value if set, zero value otherwise.
func (o *SoundSettings) GetRoomCompensation() RoomCompensationInfo {
	if o == nil || IsNil(o.RoomCompensation) {
		var ret RoomCompensationInfo
		return ret
	}
	return *o.RoomCompensation
}

// GetRoomCompensationOk returns a tuple with the RoomCompensation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundSettings) GetRoomCompensationOk() (*RoomCompensationInfo, bool) {
	if o == nil || IsNil(o.RoomCompensation) {
		return nil, false
	}
	return o.RoomCompensation, true
}

// HasRoomCompensation returns a boolean if a field has been set.
func (o *SoundSettings) HasRoomCompensation() bool {
	if o != nil && !IsNil(o.RoomCompensation) {
		return true
	}

	return false
}

// SetRoomCompensation gets a reference to the given RoomCompensationInfo and assigns it to the RoomCompensation field.
func (o *SoundSettings) SetRoomCompensation(v RoomCompensationInfo) {
	o.RoomCompensation = &v
}

// GetToneTouch returns the ToneTouch field value if set, zero value otherwise.
func (o *SoundSettings) GetToneTouch() SoundToneTouch {
	if o == nil || IsNil(o.ToneTouch) {
		var ret SoundToneTouch
		return ret
	}
	return *o.ToneTouch
}

// GetToneTouchOk returns a tuple with the ToneTouch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoundSettings) GetToneTouchOk() (*SoundToneTouch, bool) {
	if o == nil || IsNil(o.ToneTouch) {
		return nil, false
	}
	return o.ToneTouch, true
}

// HasToneTouch returns a boolean if a field has been set.
func (o *SoundSettings) HasToneTouch() bool {
	if o != nil && !IsNil(o.ToneTouch) {
		return true
	}

	return false
}

// SetToneTouch gets a reference to the given SoundToneTouch and assigns it to the ToneTouch field.
func (o *SoundSettings) SetToneTouch(v SoundToneTouch) {
	o.ToneTouch = &v
}

func (o SoundSettings) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoundSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Adjustments) {
		toSerialize["adjustments"] = o.Adjustments
	}
	if !IsNil(o.RoomCompensation) {
		toSerialize["roomCompensation"] = o.RoomCompensation
	}
	if !IsNil(o.ToneTouch) {
		toSerialize["toneTouch"] = o.ToneTouch
	}
	return toSerialize, nil
}

type NullableSoundSettings struct {
	value *SoundSettings
	isSet bool
}

func (v NullableSoundSettings) Get() *SoundSettings {
	return v.value
}

func (v *NullableSoundSettings) Set(val *SoundSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableSoundSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSoundSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoundSettings(val *SoundSettings) *NullableSoundSettings {
	return &NullableSoundSettings{value: val, isSet: true}
}

func (v NullableSoundSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoundSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
