/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SpatialEnvelopmentFeature type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SpatialEnvelopmentFeature{}

// SpatialEnvelopmentFeature struct for SpatialEnvelopmentFeature
type SpatialEnvelopmentFeature struct {
	// Selected spatial-envelopment value
	Value   float64            `json:"value"`
	Default SpatialEnvelopment `json:"default"`
	// spatial-envelopment range
	Range []SpatialEnvelopment `json:"range"`
}

type _SpatialEnvelopmentFeature SpatialEnvelopmentFeature

// NewSpatialEnvelopmentFeature instantiates a new SpatialEnvelopmentFeature object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSpatialEnvelopmentFeature(value float64, default_ SpatialEnvelopment, range_ []SpatialEnvelopment) *SpatialEnvelopmentFeature {
	this := SpatialEnvelopmentFeature{}
	this.Value = value
	this.Default = default_
	this.Range = range_
	return &this
}

// NewSpatialEnvelopmentFeatureWithDefaults instantiates a new SpatialEnvelopmentFeature object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSpatialEnvelopmentFeatureWithDefaults() *SpatialEnvelopmentFeature {
	this := SpatialEnvelopmentFeature{}
	return &this
}

// GetValue returns the Value field value
func (o *SpatialEnvelopmentFeature) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SpatialEnvelopmentFeature) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SpatialEnvelopmentFeature) SetValue(v float64) {
	o.Value = v
}

// GetDefault returns the Default field value
func (o *SpatialEnvelopmentFeature) GetDefault() SpatialEnvelopment {
	if o == nil {
		var ret SpatialEnvelopment
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *SpatialEnvelopmentFeature) GetDefaultOk() (*SpatialEnvelopment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *SpatialEnvelopmentFeature) SetDefault(v SpatialEnvelopment) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *SpatialEnvelopmentFeature) GetRange() []SpatialEnvelopment {
	if o == nil {
		var ret []SpatialEnvelopment
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *SpatialEnvelopmentFeature) GetRangeOk() ([]SpatialEnvelopment, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *SpatialEnvelopmentFeature) SetRange(v []SpatialEnvelopment) {
	o.Range = v
}

func (o SpatialEnvelopmentFeature) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SpatialEnvelopmentFeature) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *SpatialEnvelopmentFeature) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSpatialEnvelopmentFeature := _SpatialEnvelopmentFeature{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSpatialEnvelopmentFeature)

	if err != nil {
		return err
	}

	*o = SpatialEnvelopmentFeature(varSpatialEnvelopmentFeature)

	return err
}

type NullableSpatialEnvelopmentFeature struct {
	value *SpatialEnvelopmentFeature
	isSet bool
}

func (v NullableSpatialEnvelopmentFeature) Get() *SpatialEnvelopmentFeature {
	return v.value
}

func (v *NullableSpatialEnvelopmentFeature) Set(val *SpatialEnvelopmentFeature) {
	v.value = val
	v.isSet = true
}

func (v NullableSpatialEnvelopmentFeature) IsSet() bool {
	return v.isSet
}

func (v *NullableSpatialEnvelopmentFeature) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSpatialEnvelopmentFeature(val *SpatialEnvelopmentFeature) *NullableSpatialEnvelopmentFeature {
	return &NullableSpatialEnvelopmentFeature{value: val, isSet: true}
}

func (v NullableSpatialEnvelopmentFeature) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSpatialEnvelopmentFeature) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
