/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the SourceArray type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceArray{}

// SourceArray struct for SourceArray
type SourceArray struct {
	Items []Source `json:"items,omitempty"`
}

// NewSourceArray instantiates a new SourceArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceArray() *SourceArray {
	this := SourceArray{}
	return &this
}

// NewSourceArrayWithDefaults instantiates a new SourceArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceArrayWithDefaults() *SourceArray {
	this := SourceArray{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *SourceArray) GetItems() []Source {
	if o == nil || IsNil(o.Items) {
		var ret []Source
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourceArray) GetItemsOk() ([]Source, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SourceArray) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Source and assigns it to the Items field.
func (o *SourceArray) SetItems(v []Source) {
	o.Items = v
}

func (o SourceArray) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceArray) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableSourceArray struct {
	value *SourceArray
	isSet bool
}

func (v NullableSourceArray) Get() *SourceArray {
	return v.value
}

func (v *NullableSourceArray) Set(val *SourceArray) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceArray) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceArray(val *SourceArray) *NullableSourceArray {
	return &NullableSourceArray{value: val, isSet: true}
}

func (v NullableSourceArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
