/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventRole{}

// WebSocketEventRole struct for WebSocketEventRole
type WebSocketEventRole struct {
	EventData *SpeakerRoleEnum `json:"eventData,omitempty"`
	EventType *string          `json:"eventType,omitempty"`
}

// NewWebSocketEventRole instantiates a new WebSocketEventRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventRole() *WebSocketEventRole {
	this := WebSocketEventRole{}
	return &this
}

// NewWebSocketEventRoleWithDefaults instantiates a new WebSocketEventRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventRoleWithDefaults() *WebSocketEventRole {
	this := WebSocketEventRole{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventRole) GetEventData() SpeakerRoleEnum {
	if o == nil || IsNil(o.EventData) {
		var ret SpeakerRoleEnum
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventRole) GetEventDataOk() (*SpeakerRoleEnum, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventRole) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given SpeakerRoleEnum and assigns it to the EventData field.
func (o *WebSocketEventRole) SetEventData(v SpeakerRoleEnum) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventRole) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventRole) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventRole) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventRole) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventRole) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventRole struct {
	value *WebSocketEventRole
	isSet bool
}

func (v NullableWebSocketEventRole) Get() *WebSocketEventRole {
	return v.value
}

func (v *NullableWebSocketEventRole) Set(val *WebSocketEventRole) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventRole) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventRole(val *WebSocketEventRole) *NullableWebSocketEventRole {
	return &NullableWebSocketEventRole{value: val, isSet: true}
}

func (v NullableWebSocketEventRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
