/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OverlayPlayRequestTextToSpeechTextToSpeech type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverlayPlayRequestTextToSpeechTextToSpeech{}

// OverlayPlayRequestTextToSpeechTextToSpeech Object used for performing a text-to-speech operation on the product.
type OverlayPlayRequestTextToSpeechTextToSpeech struct {
	// An optional specification of the language to use. The default value is ultimately decided by the BeoCloud API, but currently it defaults to `en-us`.
	Lang NullableString `json:"lang,omitempty"`
	// Required field containing the actual text that will be converted to speech (audio). A maximum length of 2048 characters is allowed.
	Text string `json:"text"`
}

type _OverlayPlayRequestTextToSpeechTextToSpeech OverlayPlayRequestTextToSpeechTextToSpeech

// NewOverlayPlayRequestTextToSpeechTextToSpeech instantiates a new OverlayPlayRequestTextToSpeechTextToSpeech object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverlayPlayRequestTextToSpeechTextToSpeech(text string) *OverlayPlayRequestTextToSpeechTextToSpeech {
	this := OverlayPlayRequestTextToSpeechTextToSpeech{}
	this.Text = text
	return &this
}

// NewOverlayPlayRequestTextToSpeechTextToSpeechWithDefaults instantiates a new OverlayPlayRequestTextToSpeechTextToSpeech object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverlayPlayRequestTextToSpeechTextToSpeechWithDefaults() *OverlayPlayRequestTextToSpeechTextToSpeech {
	this := OverlayPlayRequestTextToSpeechTextToSpeech{}
	return &this
}

// GetLang returns the Lang field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) GetLang() string {
	if o == nil || IsNil(o.Lang.Get()) {
		var ret string
		return ret
	}
	return *o.Lang.Get()
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) GetLangOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lang.Get(), o.Lang.IsSet()
}

// HasLang returns a boolean if a field has been set.
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) HasLang() bool {
	if o != nil && o.Lang.IsSet() {
		return true
	}

	return false
}

// SetLang gets a reference to the given NullableString and assigns it to the Lang field.
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) SetLang(v string) {
	o.Lang.Set(&v)
}

// SetLangNil sets the value for Lang to be an explicit nil
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) SetLangNil() {
	o.Lang.Set(nil)
}

// UnsetLang ensures that no value is present for Lang, not even an explicit nil
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) UnsetLang() {
	o.Lang.Unset()
}

// GetText returns the Text field value
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *OverlayPlayRequestTextToSpeechTextToSpeech) SetText(v string) {
	o.Text = v
}

func (o OverlayPlayRequestTextToSpeechTextToSpeech) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverlayPlayRequestTextToSpeechTextToSpeech) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Lang.IsSet() {
		toSerialize["lang"] = o.Lang.Get()
	}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *OverlayPlayRequestTextToSpeechTextToSpeech) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOverlayPlayRequestTextToSpeechTextToSpeech := _OverlayPlayRequestTextToSpeechTextToSpeech{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOverlayPlayRequestTextToSpeechTextToSpeech)

	if err != nil {
		return err
	}

	*o = OverlayPlayRequestTextToSpeechTextToSpeech(varOverlayPlayRequestTextToSpeechTextToSpeech)

	return err
}

type NullableOverlayPlayRequestTextToSpeechTextToSpeech struct {
	value *OverlayPlayRequestTextToSpeechTextToSpeech
	isSet bool
}

func (v NullableOverlayPlayRequestTextToSpeechTextToSpeech) Get() *OverlayPlayRequestTextToSpeechTextToSpeech {
	return v.value
}

func (v *NullableOverlayPlayRequestTextToSpeechTextToSpeech) Set(val *OverlayPlayRequestTextToSpeechTextToSpeech) {
	v.value = val
	v.isSet = true
}

func (v NullableOverlayPlayRequestTextToSpeechTextToSpeech) IsSet() bool {
	return v.isSet
}

func (v *NullableOverlayPlayRequestTextToSpeechTextToSpeech) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverlayPlayRequestTextToSpeechTextToSpeech(val *OverlayPlayRequestTextToSpeechTextToSpeech) *NullableOverlayPlayRequestTextToSpeechTextToSpeech {
	return &NullableOverlayPlayRequestTextToSpeechTextToSpeech{value: val, isSet: true}
}

func (v NullableOverlayPlayRequestTextToSpeechTextToSpeech) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverlayPlayRequestTextToSpeechTextToSpeech) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
