/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the BatteryState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatteryState{}

// BatteryState struct for BatteryState
type BatteryState struct {
	// Battery level in percent
	BatteryLevel *int32 `json:"batteryLevel,omitempty"`
	IsCharging   *bool  `json:"isCharging,omitempty"`
	// Remaining charging time in minutes
	RemainingChargingTimeMinutes *int32 `json:"remainingChargingTimeMinutes,omitempty"`
	// Remaining playing time in minutes
	RemainingPlayingTimeMinutes *int32  `json:"remainingPlayingTimeMinutes,omitempty"`
	State                       *string `json:"state,omitempty"`
}

// NewBatteryState instantiates a new BatteryState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatteryState() *BatteryState {
	this := BatteryState{}
	return &this
}

// NewBatteryStateWithDefaults instantiates a new BatteryState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatteryStateWithDefaults() *BatteryState {
	this := BatteryState{}
	return &this
}

// GetBatteryLevel returns the BatteryLevel field value if set, zero value otherwise.
func (o *BatteryState) GetBatteryLevel() int32 {
	if o == nil || IsNil(o.BatteryLevel) {
		var ret int32
		return ret
	}
	return *o.BatteryLevel
}

// GetBatteryLevelOk returns a tuple with the BatteryLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatteryState) GetBatteryLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.BatteryLevel) {
		return nil, false
	}
	return o.BatteryLevel, true
}

// HasBatteryLevel returns a boolean if a field has been set.
func (o *BatteryState) HasBatteryLevel() bool {
	if o != nil && !IsNil(o.BatteryLevel) {
		return true
	}

	return false
}

// SetBatteryLevel gets a reference to the given int32 and assigns it to the BatteryLevel field.
func (o *BatteryState) SetBatteryLevel(v int32) {
	o.BatteryLevel = &v
}

// GetIsCharging returns the IsCharging field value if set, zero value otherwise.
func (o *BatteryState) GetIsCharging() bool {
	if o == nil || IsNil(o.IsCharging) {
		var ret bool
		return ret
	}
	return *o.IsCharging
}

// GetIsChargingOk returns a tuple with the IsCharging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatteryState) GetIsChargingOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCharging) {
		return nil, false
	}
	return o.IsCharging, true
}

// HasIsCharging returns a boolean if a field has been set.
func (o *BatteryState) HasIsCharging() bool {
	if o != nil && !IsNil(o.IsCharging) {
		return true
	}

	return false
}

// SetIsCharging gets a reference to the given bool and assigns it to the IsCharging field.
func (o *BatteryState) SetIsCharging(v bool) {
	o.IsCharging = &v
}

// GetRemainingChargingTimeMinutes returns the RemainingChargingTimeMinutes field value if set, zero value otherwise.
func (o *BatteryState) GetRemainingChargingTimeMinutes() int32 {
	if o == nil || IsNil(o.RemainingChargingTimeMinutes) {
		var ret int32
		return ret
	}
	return *o.RemainingChargingTimeMinutes
}

// GetRemainingChargingTimeMinutesOk returns a tuple with the RemainingChargingTimeMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatteryState) GetRemainingChargingTimeMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.RemainingChargingTimeMinutes) {
		return nil, false
	}
	return o.RemainingChargingTimeMinutes, true
}

// HasRemainingChargingTimeMinutes returns a boolean if a field has been set.
func (o *BatteryState) HasRemainingChargingTimeMinutes() bool {
	if o != nil && !IsNil(o.RemainingChargingTimeMinutes) {
		return true
	}

	return false
}

// SetRemainingChargingTimeMinutes gets a reference to the given int32 and assigns it to the RemainingChargingTimeMinutes field.
func (o *BatteryState) SetRemainingChargingTimeMinutes(v int32) {
	o.RemainingChargingTimeMinutes = &v
}

// GetRemainingPlayingTimeMinutes returns the RemainingPlayingTimeMinutes field value if set, zero value otherwise.
func (o *BatteryState) GetRemainingPlayingTimeMinutes() int32 {
	if o == nil || IsNil(o.RemainingPlayingTimeMinutes) {
		var ret int32
		return ret
	}
	return *o.RemainingPlayingTimeMinutes
}

// GetRemainingPlayingTimeMinutesOk returns a tuple with the RemainingPlayingTimeMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatteryState) GetRemainingPlayingTimeMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.RemainingPlayingTimeMinutes) {
		return nil, false
	}
	return o.RemainingPlayingTimeMinutes, true
}

// HasRemainingPlayingTimeMinutes returns a boolean if a field has been set.
func (o *BatteryState) HasRemainingPlayingTimeMinutes() bool {
	if o != nil && !IsNil(o.RemainingPlayingTimeMinutes) {
		return true
	}

	return false
}

// SetRemainingPlayingTimeMinutes gets a reference to the given int32 and assigns it to the RemainingPlayingTimeMinutes field.
func (o *BatteryState) SetRemainingPlayingTimeMinutes(v int32) {
	o.RemainingPlayingTimeMinutes = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *BatteryState) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatteryState) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *BatteryState) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *BatteryState) SetState(v string) {
	o.State = &v
}

func (o BatteryState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatteryState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BatteryLevel) {
		toSerialize["batteryLevel"] = o.BatteryLevel
	}
	if !IsNil(o.IsCharging) {
		toSerialize["isCharging"] = o.IsCharging
	}
	if !IsNil(o.RemainingChargingTimeMinutes) {
		toSerialize["remainingChargingTimeMinutes"] = o.RemainingChargingTimeMinutes
	}
	if !IsNil(o.RemainingPlayingTimeMinutes) {
		toSerialize["remainingPlayingTimeMinutes"] = o.RemainingPlayingTimeMinutes
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableBatteryState struct {
	value *BatteryState
	isSet bool
}

func (v NullableBatteryState) Get() *BatteryState {
	return v.value
}

func (v *NullableBatteryState) Set(val *BatteryState) {
	v.value = val
	v.isSet = true
}

func (v NullableBatteryState) IsSet() bool {
	return v.isSet
}

func (v *NullableBatteryState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatteryState(val *BatteryState) *NullableBatteryState {
	return &NullableBatteryState{value: val, isSet: true}
}

func (v NullableBatteryState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatteryState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
