/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the MicrophoneState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MicrophoneState{}

// MicrophoneState struct for MicrophoneState
type MicrophoneState struct {
	Value *string `json:"value,omitempty"`
}

// NewMicrophoneState instantiates a new MicrophoneState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMicrophoneState() *MicrophoneState {
	this := MicrophoneState{}
	return &this
}

// NewMicrophoneStateWithDefaults instantiates a new MicrophoneState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMicrophoneStateWithDefaults() *MicrophoneState {
	this := MicrophoneState{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MicrophoneState) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MicrophoneState) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MicrophoneState) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *MicrophoneState) SetValue(v string) {
	o.Value = &v
}

func (o MicrophoneState) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MicrophoneState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableMicrophoneState struct {
	value *MicrophoneState
	isSet bool
}

func (v NullableMicrophoneState) Get() *MicrophoneState {
	return v.value
}

func (v *NullableMicrophoneState) Set(val *MicrophoneState) {
	v.value = val
	v.isSet = true
}

func (v NullableMicrophoneState) IsSet() bool {
	return v.isSet
}

func (v *NullableMicrophoneState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMicrophoneState(val *MicrophoneState) *NullableMicrophoneState {
	return &NullableMicrophoneState{value: val, isSet: true}
}

func (v NullableMicrophoneState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMicrophoneState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
