/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BeolinkJoinRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeolinkJoinRequest{}

// BeolinkJoinRequest struct for BeolinkJoinRequest
type BeolinkJoinRequest struct {
	// Beolink peer ID
	Jid *string `json:"jid,omitempty"`
	// Beolink request ID
	RequestID string `json:"requestID"`
	// Relative URL of the join result
	Result string `json:"result"`
}

type _BeolinkJoinRequest BeolinkJoinRequest

// NewBeolinkJoinRequest instantiates a new BeolinkJoinRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeolinkJoinRequest(requestID string, result string) *BeolinkJoinRequest {
	this := BeolinkJoinRequest{}
	this.RequestID = requestID
	this.Result = result
	return &this
}

// NewBeolinkJoinRequestWithDefaults instantiates a new BeolinkJoinRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeolinkJoinRequestWithDefaults() *BeolinkJoinRequest {
	this := BeolinkJoinRequest{}
	return &this
}

// GetJid returns the Jid field value if set, zero value otherwise.
func (o *BeolinkJoinRequest) GetJid() string {
	if o == nil || IsNil(o.Jid) {
		var ret string
		return ret
	}
	return *o.Jid
}

// GetJidOk returns a tuple with the Jid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeolinkJoinRequest) GetJidOk() (*string, bool) {
	if o == nil || IsNil(o.Jid) {
		return nil, false
	}
	return o.Jid, true
}

// HasJid returns a boolean if a field has been set.
func (o *BeolinkJoinRequest) HasJid() bool {
	if o != nil && !IsNil(o.Jid) {
		return true
	}

	return false
}

// SetJid gets a reference to the given string and assigns it to the Jid field.
func (o *BeolinkJoinRequest) SetJid(v string) {
	o.Jid = &v
}

// GetRequestID returns the RequestID field value
func (o *BeolinkJoinRequest) GetRequestID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestID
}

// GetRequestIDOk returns a tuple with the RequestID field value
// and a boolean to check if the value has been set.
func (o *BeolinkJoinRequest) GetRequestIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestID, true
}

// SetRequestID sets field value
func (o *BeolinkJoinRequest) SetRequestID(v string) {
	o.RequestID = v
}

// GetResult returns the Result field value
func (o *BeolinkJoinRequest) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *BeolinkJoinRequest) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *BeolinkJoinRequest) SetResult(v string) {
	o.Result = v
}

func (o BeolinkJoinRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeolinkJoinRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Jid) {
		toSerialize["jid"] = o.Jid
	}
	toSerialize["requestID"] = o.RequestID
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *BeolinkJoinRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestID",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBeolinkJoinRequest := _BeolinkJoinRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBeolinkJoinRequest)

	if err != nil {
		return err
	}

	*o = BeolinkJoinRequest(varBeolinkJoinRequest)

	return err
}

type NullableBeolinkJoinRequest struct {
	value *BeolinkJoinRequest
	isSet bool
}

func (v NullableBeolinkJoinRequest) Get() *BeolinkJoinRequest {
	return v.value
}

func (v *NullableBeolinkJoinRequest) Set(val *BeolinkJoinRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBeolinkJoinRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBeolinkJoinRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeolinkJoinRequest(val *BeolinkJoinRequest) *NullableBeolinkJoinRequest {
	return &NullableBeolinkJoinRequest{value: val, isSet: true}
}

func (v NullableBeolinkJoinRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeolinkJoinRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
