/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BassRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BassRange{}

// BassRange struct for BassRange
type BassRange struct {
	Default Bass `json:"default"`
	// Product and role specific bass range
	Range []Bass `json:"range"`
}

type _BassRange BassRange

// NewBassRange instantiates a new BassRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBassRange(default_ Bass, range_ []Bass) *BassRange {
	this := BassRange{}
	this.Default = default_
	this.Range = range_
	return &this
}

// NewBassRangeWithDefaults instantiates a new BassRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBassRangeWithDefaults() *BassRange {
	this := BassRange{}
	return &this
}

// GetDefault returns the Default field value
func (o *BassRange) GetDefault() Bass {
	if o == nil {
		var ret Bass
		return ret
	}

	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value
// and a boolean to check if the value has been set.
func (o *BassRange) GetDefaultOk() (*Bass, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Default, true
}

// SetDefault sets field value
func (o *BassRange) SetDefault(v Bass) {
	o.Default = v
}

// GetRange returns the Range field value
func (o *BassRange) GetRange() []Bass {
	if o == nil {
		var ret []Bass
		return ret
	}

	return o.Range
}

// GetRangeOk returns a tuple with the Range field value
// and a boolean to check if the value has been set.
func (o *BassRange) GetRangeOk() ([]Bass, bool) {
	if o == nil {
		return nil, false
	}
	return o.Range, true
}

// SetRange sets field value
func (o *BassRange) SetRange(v []Bass) {
	o.Range = v
}

func (o BassRange) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BassRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["default"] = o.Default
	toSerialize["range"] = o.Range
	return toSerialize, nil
}

func (o *BassRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default",
		"range",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBassRange := _BassRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBassRange)

	if err != nil {
		return err
	}

	*o = BassRange(varBassRange)

	return err
}

type NullableBassRange struct {
	value *BassRange
	isSet bool
}

func (v NullableBassRange) Get() *BassRange {
	return v.value
}

func (v *NullableBassRange) Set(val *BassRange) {
	v.value = val
	v.isSet = true
}

func (v NullableBassRange) IsSet() bool {
	return v.isSet
}

func (v *NullableBassRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBassRange(val *BassRange) *NullableBassRange {
	return &NullableBassRange{value: val, isSet: true}
}

func (v NullableBassRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBassRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
