/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the OverlayPlayRequestTextToSpeech type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverlayPlayRequestTextToSpeech{}

// OverlayPlayRequestTextToSpeech struct for OverlayPlayRequestTextToSpeech
type OverlayPlayRequestTextToSpeech struct {
	TextToSpeech *OverlayPlayRequestTextToSpeechTextToSpeech `json:"textToSpeech,omitempty"`
}

// NewOverlayPlayRequestTextToSpeech instantiates a new OverlayPlayRequestTextToSpeech object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverlayPlayRequestTextToSpeech() *OverlayPlayRequestTextToSpeech {
	this := OverlayPlayRequestTextToSpeech{}
	return &this
}

// NewOverlayPlayRequestTextToSpeechWithDefaults instantiates a new OverlayPlayRequestTextToSpeech object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverlayPlayRequestTextToSpeechWithDefaults() *OverlayPlayRequestTextToSpeech {
	this := OverlayPlayRequestTextToSpeech{}
	return &this
}

// GetTextToSpeech returns the TextToSpeech field value if set, zero value otherwise.
func (o *OverlayPlayRequestTextToSpeech) GetTextToSpeech() OverlayPlayRequestTextToSpeechTextToSpeech {
	if o == nil || IsNil(o.TextToSpeech) {
		var ret OverlayPlayRequestTextToSpeechTextToSpeech
		return ret
	}
	return *o.TextToSpeech
}

// GetTextToSpeechOk returns a tuple with the TextToSpeech field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverlayPlayRequestTextToSpeech) GetTextToSpeechOk() (*OverlayPlayRequestTextToSpeechTextToSpeech, bool) {
	if o == nil || IsNil(o.TextToSpeech) {
		return nil, false
	}
	return o.TextToSpeech, true
}

// HasTextToSpeech returns a boolean if a field has been set.
func (o *OverlayPlayRequestTextToSpeech) HasTextToSpeech() bool {
	if o != nil && !IsNil(o.TextToSpeech) {
		return true
	}

	return false
}

// SetTextToSpeech gets a reference to the given OverlayPlayRequestTextToSpeechTextToSpeech and assigns it to the TextToSpeech field.
func (o *OverlayPlayRequestTextToSpeech) SetTextToSpeech(v OverlayPlayRequestTextToSpeechTextToSpeech) {
	o.TextToSpeech = &v
}

func (o OverlayPlayRequestTextToSpeech) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverlayPlayRequestTextToSpeech) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TextToSpeech) {
		toSerialize["textToSpeech"] = o.TextToSpeech
	}
	return toSerialize, nil
}

type NullableOverlayPlayRequestTextToSpeech struct {
	value *OverlayPlayRequestTextToSpeech
	isSet bool
}

func (v NullableOverlayPlayRequestTextToSpeech) Get() *OverlayPlayRequestTextToSpeech {
	return v.value
}

func (v *NullableOverlayPlayRequestTextToSpeech) Set(val *OverlayPlayRequestTextToSpeech) {
	v.value = val
	v.isSet = true
}

func (v NullableOverlayPlayRequestTextToSpeech) IsSet() bool {
	return v.isSet
}

func (v *NullableOverlayPlayRequestTextToSpeech) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverlayPlayRequestTextToSpeech(val *OverlayPlayRequestTextToSpeech) *NullableOverlayPlayRequestTextToSpeech {
	return &NullableOverlayPlayRequestTextToSpeech{value: val, isSet: true}
}

func (v NullableOverlayPlayRequestTextToSpeech) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverlayPlayRequestTextToSpeech) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
