/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the WebSocketEventSpeakerLinkStatusChanged type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketEventSpeakerLinkStatusChanged{}

// WebSocketEventSpeakerLinkStatusChanged struct for WebSocketEventSpeakerLinkStatusChanged
type WebSocketEventSpeakerLinkStatusChanged struct {
	EventData *SpeakerLinkStatus `json:"eventData,omitempty"`
	EventType *string            `json:"eventType,omitempty"`
}

// NewWebSocketEventSpeakerLinkStatusChanged instantiates a new WebSocketEventSpeakerLinkStatusChanged object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketEventSpeakerLinkStatusChanged() *WebSocketEventSpeakerLinkStatusChanged {
	this := WebSocketEventSpeakerLinkStatusChanged{}
	return &this
}

// NewWebSocketEventSpeakerLinkStatusChangedWithDefaults instantiates a new WebSocketEventSpeakerLinkStatusChanged object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketEventSpeakerLinkStatusChangedWithDefaults() *WebSocketEventSpeakerLinkStatusChanged {
	this := WebSocketEventSpeakerLinkStatusChanged{}
	return &this
}

// GetEventData returns the EventData field value if set, zero value otherwise.
func (o *WebSocketEventSpeakerLinkStatusChanged) GetEventData() SpeakerLinkStatus {
	if o == nil || IsNil(o.EventData) {
		var ret SpeakerLinkStatus
		return ret
	}
	return *o.EventData
}

// GetEventDataOk returns a tuple with the EventData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventSpeakerLinkStatusChanged) GetEventDataOk() (*SpeakerLinkStatus, bool) {
	if o == nil || IsNil(o.EventData) {
		return nil, false
	}
	return o.EventData, true
}

// HasEventData returns a boolean if a field has been set.
func (o *WebSocketEventSpeakerLinkStatusChanged) HasEventData() bool {
	if o != nil && !IsNil(o.EventData) {
		return true
	}

	return false
}

// SetEventData gets a reference to the given SpeakerLinkStatus and assigns it to the EventData field.
func (o *WebSocketEventSpeakerLinkStatusChanged) SetEventData(v SpeakerLinkStatus) {
	o.EventData = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *WebSocketEventSpeakerLinkStatusChanged) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSocketEventSpeakerLinkStatusChanged) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *WebSocketEventSpeakerLinkStatusChanged) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *WebSocketEventSpeakerLinkStatusChanged) SetEventType(v string) {
	o.EventType = &v
}

func (o WebSocketEventSpeakerLinkStatusChanged) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketEventSpeakerLinkStatusChanged) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EventData) {
		toSerialize["eventData"] = o.EventData
	}
	if !IsNil(o.EventType) {
		toSerialize["eventType"] = o.EventType
	}
	return toSerialize, nil
}

type NullableWebSocketEventSpeakerLinkStatusChanged struct {
	value *WebSocketEventSpeakerLinkStatusChanged
	isSet bool
}

func (v NullableWebSocketEventSpeakerLinkStatusChanged) Get() *WebSocketEventSpeakerLinkStatusChanged {
	return v.value
}

func (v *NullableWebSocketEventSpeakerLinkStatusChanged) Set(val *WebSocketEventSpeakerLinkStatusChanged) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketEventSpeakerLinkStatusChanged) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketEventSpeakerLinkStatusChanged) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketEventSpeakerLinkStatusChanged(val *WebSocketEventSpeakerLinkStatusChanged) *NullableWebSocketEventSpeakerLinkStatusChanged {
	return &NullableWebSocketEventSpeakerLinkStatusChanged{value: val, isSet: true}
}

func (v NullableWebSocketEventSpeakerLinkStatusChanged) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketEventSpeakerLinkStatusChanged) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
