/*
Mozart platform API

API for interacting with the Mozart platform.

API version: 0.2.0
Contact: support@bang-olufsen.dk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mozartapi

import (
	"encoding/json"
)

// checks if the BluetoothDeviceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BluetoothDeviceList{}

// BluetoothDeviceList struct for BluetoothDeviceList
type BluetoothDeviceList struct {
	Items []BluetoothDevice `json:"items,omitempty"`
}

// NewBluetoothDeviceList instantiates a new BluetoothDeviceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBluetoothDeviceList() *BluetoothDeviceList {
	this := BluetoothDeviceList{}
	return &this
}

// NewBluetoothDeviceListWithDefaults instantiates a new BluetoothDeviceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBluetoothDeviceListWithDefaults() *BluetoothDeviceList {
	this := BluetoothDeviceList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *BluetoothDeviceList) GetItems() []BluetoothDevice {
	if o == nil || IsNil(o.Items) {
		var ret []BluetoothDevice
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BluetoothDeviceList) GetItemsOk() ([]BluetoothDevice, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *BluetoothDeviceList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []BluetoothDevice and assigns it to the Items field.
func (o *BluetoothDeviceList) SetItems(v []BluetoothDevice) {
	o.Items = v
}

func (o BluetoothDeviceList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BluetoothDeviceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableBluetoothDeviceList struct {
	value *BluetoothDeviceList
	isSet bool
}

func (v NullableBluetoothDeviceList) Get() *BluetoothDeviceList {
	return v.value
}

func (v *NullableBluetoothDeviceList) Set(val *BluetoothDeviceList) {
	v.value = val
	v.isSet = true
}

func (v NullableBluetoothDeviceList) IsSet() bool {
	return v.isSet
}

func (v *NullableBluetoothDeviceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBluetoothDeviceList(val *BluetoothDeviceList) *NullableBluetoothDeviceList {
	return &NullableBluetoothDeviceList{value: val, isSet: true}
}

func (v NullableBluetoothDeviceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBluetoothDeviceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
